//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 18/03/2026 12:29:02
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IIntegranteNfDjRepository
    {
    }
}
