//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 21/08/2026 15:09:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IUnitOfWork : IDisposable
    {
        IPaisRepository Paises { get; }
        ICiudadRepository Ciudads { get; }
        IEmpresaRepository Empresas { get; }
        IEstadoRepository Estados { get; }
        IPersonaRepository Personas { get; }
        IImagenRepository Imagens { get; }
        INivelProductoRepository NivelProductos { get; }
        ITituloRepository Titulos { get; }
        IEncuestaIniAdmisionRepository EncuestaIniAdmisions { get; }
        IProductoRepository Productos { get; }
        ISolicitudAltaRepository SolicitudAltas { get; }
        IProcesoProductoRepository ProcesoProductos { get; }
        IProcesoComienzoRepository ProcesoComienzos { get; }
        IProcesoRepository Procesos { get; }
        IDepartamentoRepository Departamentos { get; }
        IPaqueteRepository Paquetes { get; }
        ISupraofertaRepository Supraofertas { get; }
        IOfertaRepository Ofertas { get; }
        IIntereRepository Interes { get; }
        IInteresProductoRepository InteresProductos { get; }
        IInscriptoRepository Inscriptos { get; }
        IPlanPagoRepository PlanPagos { get; }
        IComienzoRepository Comienzos { get; }
        ILocalidadRepository Localidads { get; }
        ITurnoRepository Turnos { get; }
        IEscuelaRepository Escuelas { get; }
        ITipoDesercionRepository TipoDesercions { get; }
        ITituloOrtRepository TituloOrts { get; }
        ICausalInscrPagoRepository CausalInscrPagos { get; }
        IInstanciaWorkflowRepository InstanciaWorkflows { get; }
        IAccesoSitiosantanderRepository AccesoSitiosantanders { get; }
        IBachilleratoPersonaRepository BachilleratoPersonas { get; }
        IAnioBachillerRepository AnioBachillers { get; }
        IDeclaracionJuradaWebRepository DeclaracionJuradaWebs { get; }
        ITipoViviendaRepository TipoViviendas { get; }
        ITipoDescuentoRepository TipoDescuentos { get; }
        ICentroCostoRepository CentroCostos { get; }
        IInscriptoPruebaRepository InscriptoPruebas { get; }
        IPruebaRepository Pruebas { get; }
        IImagenTemporalRepository ImagenTemporals { get; }
        IMotivoOpcionesAdmisionRepository MotivoOpcionesAdmisions { get; }
        IPublicidadOpcionesAdmisionRepository PublicidadOpcionesAdmisions { get; }
        ITipoBecaNivelProductoRepository TipoBecaNivelProductos { get; }
        IAceptacionReglamentoEstRepository AceptacionReglamentoEsts { get; }
        ITipoParentescoRepository TipoParentescos { get; }
        ITipoEgresoDjRepository TipoEgresoDjs { get; }
        ICaracteristicaPaiRepository CaracteristicaPais { get; }
        IAcaTipoDocumentoRepository AcaTipoDocumentos { get; }
        IVdEsFrescoAdmisionRepository VdEsFrescoAdmisions { get; }
        IVdFrescoProductoAdmisioneRepository VdFrescoProductoAdmisiones { get; }
        IFeriadoRepository Feriados { get; }
        IPersonaAdmiteRepository PersonaAdmites { get; }
        IIngresoMensualNfDjRepository IngresoMensualNfDjs { get; }
        IEgresoMensualNfDjRepository EgresoMensualNfDjs { get; }
        IIntegranteNfDjRepository IntegranteNfDjs { get; }
        IRefreshTokenRepository RefreshTokens { get; }
        IEncuestaIniRepository EncuestaInis { get; }
        IRegistroAdmisioneRepository RegistroAdmisiones { get; }
        IInteresProductoOfertaRepository InteresProductoOfertas { get; }
        IParametrosAdmisioneRepository ParametrosAdmisiones { get; }
        IEmpresaConsideradaAdmisionRepository EmpresaConsideradaAdmisions { get; }
        IEducacionSuperiorAdmisionRepository EducacionSuperiorAdmisions { get; }
        IMotivoEleccionAdmisionRepository MotivoEleccionAdmisions { get; }
        IPublicidadEleccionAdmisionRepository PublicidadEleccionAdmisions { get; }
        IEnvioParaTivenoRepository EnvioParaTivenos { get; }
        IParametroRepository Parametros { get; }
        IMateriaRepository Materias { get; }
        IOfertaCreditoRepository OfertaCreditos { get; }
        IOfertaCreditoMateriaRepository OfertaCreditoMaterias { get; }
        IBancoRepository Bancos { get; }
        IVdOfertasDisponibles3y4Repository VdOfertasDisponibles3y4s { get; }
        IVdProcesosDisponibles1y2Repository VdProcesosDisponibles1y2s { get; }
        IInscriptoSeniaMinimumRepository InscriptoSeniaMinima { get; }
        IVdInscriptoCoordinadoreRepository VdInscriptoCoordinadores { get; }
        IVdInscriptoCreditoAlumnoRepository VdInscriptoCreditoAlumnos { get; }
        IVdProductosDisponibles1y2Repository VdProductosDisponibles1y2s { get; }
        IInstWorkflowInscripcionRepository InstWorkflowInscripcions { get; }
        IVdInscripcionesFresco1y2Repository VdInscripcionesFresco1y2s { get; }
        IVdInscripcionesFresco3y4Repository VdInscripcionesFresco3y4s { get; }
        IVdOfertasDisponibles1y2Repository VdOfertasDisponibles1y2s { get; }
        string ObtenerDbUserId();
        void Save();
        void BeginTransaction();
        void Commit();
        void Rollback();
    }
}
