//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 21/08/2026 14:27:16
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IVdOfertasDisponibles1y2Repository
    {
        ICollection<BusinessLogic.Entities.VdOfertasDisponibles1y2> GetOfertasDisponibles(
            long idProducto,
            long idProceso,
            long codigoPersona);
    }
}
