<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <SonarQubeExclude>true</SonarQubeExclude>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\DbConnectionContext\ConnectionContext.csproj" />
    <ProjectReference Include="..\..\Core\MailORT\MailORT.csproj" />
    <ProjectReference Include="..\..\Core\Modules\ModBandeja\ModAppLogic\ModBandejaAppLogic.csproj" />
    <ProjectReference Include="..\..\Core\Modules\ModBandeja\ModBusinessLogic\ModBandejaBusinessLogic.csproj" />
    <ProjectReference Include="..\..\Core\Modules\ModGenericBase\ModAppLogic\ModGenericBaseAppLogic.csproj" />
    <ProjectReference Include="..\..\Core\Modules\ModGenericBase\ModBusinessLogic\ModGenericBaseBusinessLogic.csproj" />
    <ProjectReference Include="..\..\Core\Utilities\Utilities.csproj" />
    <ProjectReference Include="..\AppLogic\AppLogic.csproj" />
    <ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
    <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\WebApiTemplate\WebApiTemplate.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Modulos\GenericBase\" />
    <Folder Include="Utilities\" />
  </ItemGroup>
</Project>