<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Core\DbConnectionContext\ConnectionContext.csproj" />
		<ProjectReference Include="..\..\Core\LdapService\LdapService.csproj" />
		<ProjectReference Include="..\..\Core\MailORT\MailORT.csproj" />
		<ProjectReference Include="..\..\Core\Modules\ModBandeja\ModAppLogic\ModBandejaAppLogic.csproj" />
		<ProjectReference Include="..\..\Core\Utilities\Utilities.csproj" />
		<ProjectReference Include="..\BusinessLogic\BusinessLogic.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="DevartDTOs\DevartConverters\" />
		<Folder Include="DevartDTOs\DevartDTO\" />
	</ItemGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel.Core" Version="2.3.9" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>
</Project>