//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/06/2026 12:18:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Banco {

        public Banco()
        {
            this.PagoSueldoBanco = @"NO";
            this.HabilitadoSistarbanc = @"NO";

        }

        [Key]
        [Required()]
        public long IdBanco { get; set; }

        [StringLength(30)]
        [Required()]
        public string NombreBanco { get; set; }

        [Required()]
        public long CodigoBanco { get; set; }

        [StringLength(200)]
        public string? ObservacionesBanco { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(6)]
        public string? BancoPsig { get; set; }

        [StringLength(6)]
        public string? BancoPsigUsd { get; set; }

        [StringLength(2)]
        public string? PagoSueldoBanco { get; set; }

        [StringLength(4)]
        public string? IdBancoSistarbanc { get; set; }

        [StringLength(2)]
        [Required()]
        public string HabilitadoSistarbanc { get; set; }

        [StringLength(30)]
        public string? GrupoBanco { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
