//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/06/2026 12:18:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class CaracteristicaPai {

        public CaracteristicaPai()
        {
            this.Personas_IdCaracteristicaPaisTel1 = new List<Persona>();
            this.Personas_IdCaracteristicaPaisTel2 = new List<Persona>();

        }

        [Key]
        [Required()]
        public long IdCaracteristicaPais { get; set; }

        [StringLength(200)]
        [Required()]
        public string NombrePais { get; set; }

        [StringLength(2)]
        [Required()]
        public string Iso2 { get; set; }

        [Required()]
        public decimal Caracteristica { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(8)]
        [Required()]
        public string HoraIngreso { get; set; }

        public virtual IList<Persona> Personas_IdCaracteristicaPaisTel1 { get; set; }

        public virtual IList<Persona> Personas_IdCaracteristicaPaisTel2 { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
