//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/07/2026 16:22:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class CausalInscrPago {

        public CausalInscrPago()
        {
            this.Inscriptos = new List<Inscripto>();

        }

        [Key]
        [Required()]
        public long IdCausalInscrPago { get; set; }

        [StringLength(30)]
        [Required()]
        public string NombreCausalInscrPago { get; set; }

        [StringLength(400)]
        public string? ObservacionesCausalInscrPag { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        public virtual IList<Inscripto> Inscriptos { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
