//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 17/03/2026 16:49:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class DeclaracionJuradaWeb {

        public DeclaracionJuradaWeb()
        {
            this.TienevehiculoNfDj = @"NO";
            this.TienecasaveraneoNfDj = @"NO";
            this.EgresoMensualNfDjs = new List<EgresoMensualNfDj>();

        }

        [Key]
        [Required()]
        public decimal IdDeclaracionjuradaWeb { get; set; }

        [Required()]
        public long CodigoPersona { get; set; }

        [Required()]
        public long IdProducto { get; set; }

        [Required()]
        public long IdTipoDescuento { get; set; }

        public DateTime? ConfirmacionDecjurada { get; set; }

        public DateTime? UltactualizacionDecjurada { get; set; }

        public decimal? IdTipoVivienda { get; set; }

        public decimal? MontoViviendaDj { get; set; }

        [StringLength(500)]
        public string? ObsOtroViviendaDj { get; set; }

        [StringLength(20)]
        public string? ObservacionesNfDj { get; set; }

        [StringLength(500)]
        public string? OtroActivosNfDj { get; set; }

        [StringLength(500)]
        public string? SolventoEstudiosNfDj { get; set; }

        [StringLength(2)]
        [Required()]
        public string TienevehiculoNfDj { get; set; }

        [StringLength(100)]
        public string? MarcavehiculoNfDj { get; set; }

        public decimal? AnioVehiculoNfDj { get; set; }

        [StringLength(2)]
        [Required()]
        public string TienecasaveraneoNfDj { get; set; }

        [StringLength(100)]
        public string? BalnearioNfDj { get; set; }

        [StringLength(500)]
        public string? ObservacionesIngresosNfDj { get; set; }

        public decimal? ResidenciaDj { get; set; }

        [StringLength(2)]
        public string? ResidiraEnmontevideoDj { get; set; }

        public decimal? IdTipoResidencia { get; set; }

        [StringLength(500)]
        public string? DetalleResideEnmontevideoDj { get; set; }

        [StringLength(500)]
        public string? CoberturasaludResideMontDj { get; set; }

        [StringLength(500)]
        public string? GastosTrasladoResideInteDj { get; set; }

        [Required()]
        public decimal IdInscriptoPrueba { get; set; }

        public DateTime? VencimientoDj { get; set; }

        public decimal? NominalOtrosingresosNfDj { get; set; }

        public decimal? LiquidoOtrosingresosNfDj { get; set; }

        [StringLength(500)]
        public string? ObservacionesEgresosNfDj { get; set; }

        public byte[]? PdfDecjurada { get; set; }

        public decimal? CodigoInstitucionBac { get; set; }

        [StringLength(100)]
        public string? FacultadUniversidadDj { get; set; }

        [StringLength(100)]
        public string? CarreraUniversitariaDj { get; set; }

        public decimal? CantMateriasAprobadasDj { get; set; }

        public decimal? CantMatExaReprobadosDj { get; set; }

        public decimal? PromTotalCalificacionesDj { get; set; }

        public decimal? PromAprlCalificacionesDj { get; set; }

        public decimal? UltimoanioSecundariaAprDj { get; set; }

        [StringLength(2)]
        public string? OtrosEstudiosDj { get; set; }

        [StringLength(500)]
        public string? DetalleOtrosEstudiosDj { get; set; }

        [StringLength(2)]
        public string? ExperienciaLaboralDj { get; set; }

        public DateTime? FechaComienzoTrabajo { get; set; }

        [StringLength(100)]
        public string? LugarTrabajoActualDj { get; set; }

        [StringLength(100)]
        public string? CargoDj { get; set; }

        [StringLength(2)]
        public string? FamiliaresCursandoEnort { get; set; }

        public decimal? CodigoInstitucionUniv { get; set; }

        [StringLength(100)]
        public string? Subestado { get; set; }

        public byte[]? PdfFormRevalidasDj { get; set; }

        [StringLength(150)]
        public string? NombrePdfRevalidasDj { get; set; }

        [StringLength(5)]
        public string? ExtensionPdfRevalidasDj { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(8)]
        public string? HoraIngreso { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public decimal? IdPdfRevalidasDjFront { get; set; }

        [StringLength(1)]
        public string? ModalidadPostulacionDj { get; set; }

        public decimal? TipoBachillerato { get; set; }

        public decimal? PromedioCalificaiones5to { get; set; }

        [StringLength(2)]
        public string? TrabajaActualmente { get; set; }

        public decimal? PromedioCalificaiones6to { get; set; }

        public long? CodigoCiudadDj { get; set; }

        public long? CodigoEstadoDj { get; set; }

        [StringLength(2)]
        public string? WarningDeclaracionJurada { get; set; }

        public virtual Persona Persona { get; set; }

        public virtual Producto Producto { get; set; }

        public virtual TipoDescuento TipoDescuento { get; set; }

        public virtual IList<EgresoMensualNfDj> EgresoMensualNfDjs { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
