//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 23/06/2026 11:41:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class EmpresaConsideradaAdmision {

        public EmpresaConsideradaAdmision()
        {

        }

        [Key]
        [Required()]
        public long IdEmpresaConsiderada { get; set; }

        public long? CodigoPersona { get; set; }

        public long? CodigoEmpresa { get; set; }

        [StringLength(90)]
        public string? NombreOtraEmpresa { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(8)]
        [Required()]
        public string HoraIngreso { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        public virtual Persona Persona { get; set; }

        public virtual Empresa Empresa { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
