//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/06/2026 14:36:07
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class EncuestaIni {

        public EncuestaIni()
        {

        }

        [Key]
        [Required()]
        public long IdEncuestaIni { get; set; }

        public long? CodigoPersona { get; set; }

        public long? IdProducto { get; set; }

        public long? IdComienzo { get; set; }

        public DateTime? FechaEncuestaIni { get; set; }

        [StringLength(30)]
        public string? DesertorEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ClaveEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AniosInstruccionEncuestaIni { get; set; }

        public long? CodigoInstSecEncuestaIni { get; set; }

        [StringLength(90)]
        public string? NombreInstSecEncuestaIni { get; set; }

        public long? CodigoTitulo { get; set; }

        [StringLength(30)]
        public string? UltimoAnioSextoEncuestaIni { get; set; }

        [StringLength(30)]
        public string? VecesSextoEncuestaIni { get; set; }

        [StringLength(30)]
        public string? CantidadPreviasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? EstudiosTercEncuestaIni { get; set; }

        public long? CodigoInstTerEncuestaIni { get; set; }

        [StringLength(60)]
        public string? NombreInstTerEncuestaIni { get; set; }

        [StringLength(60)]
        public string? CarreraTerEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UltAnioTerEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UltAnioCalTerEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AbandTerAcadEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AbandTerOrgEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AbandTerEconEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AbandTerOtrosEncuestaIni { get; set; }

        [StringLength(2000)]
        public string? TextoAbandTerEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ConocimienInglesEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InstruccionPadreEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InstruccionMadreEncuestaIni { get; set; }

        [StringLength(30)]
        public string? DecisionCarreraEncuestaIni { get; set; }

        [StringLength(30)]
        public string? DecisionUniverEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiFeriasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiCharlasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiActividadesEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiTalleresEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiGuiasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UtiWebEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforOtrasAntesEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforUcudalEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforUrEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforUmEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforOtrasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? InforUdeEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ComparPadresEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ComparOtrosEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ComparAmigoFamEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ComparNadieEncuestaIni { get; set; }

        [StringLength(30)]
        public string? ComparAmigoPropEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoPrestEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoInfraEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoAcadEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoPrecioEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoLabEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AspectoBecaEncuestaIni { get; set; }

        [StringLength(30)]
        public string? AsististeCharlaEncuestaIni { get; set; }

        [StringLength(30)]
        public string? OpinionCharlasEncuestaIni { get; set; }

        [StringLength(30)]
        public string? PlantTodasParEncuestaIni { get; set; }

        [StringLength(30)]
        public string? PlantCadaUnaEncuestaIni { get; set; }

        [StringLength(30)]
        public string? PlantPrivParEncuestaIni { get; set; }

        [StringLength(30)]
        public string? PlantCadaDestacEncuestaIni { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(2)]
        public string? ImpresoEncuestaIni { get; set; }

        [StringLength(500)]
        public string? InforOtrasLinea1Ini { get; set; }

        [StringLength(500)]
        public string? InforOtrasLinea2Ini { get; set; }

        public long? CodigoInstitucionBac { get; set; }

        [StringLength(2)]
        public string? NuevaversionEncuestaIni { get; set; }

        public bool? UltimoanioSecundariaEncuestaIni { get; set; }

        [StringLength(2)]
        public string? TieneEducacionSuperiorEncuestaIni { get; set; }

        public bool? NivelDecisionEncuestaIni { get; set; }

        [StringLength(2)]
        public string? AsesoramientoOrtEncuestaIni { get; set; }

        public bool? ValoracionAsesoramientoOrtEncuestaIni { get; set; }

        [StringLength(2)]
        public string? VistaSitioWebOrtEncuestaIni { get; set; }

        public bool? ValoracionSitioWebOrtEncuestaIni { get; set; }

        [StringLength(2)]
        public string? VistaInstalacionesOrtEncuestaIni { get; set; }

        public bool? ValoracionInstalacionesOrtEncuestaIni { get; set; }

        [StringLength(2)]
        public string? PublicidadOrtEncuestaIni { get; set; }

        [StringLength(2)]
        public string? InstruccionMadreOrtEncuestaIni { get; set; }

        [StringLength(2)]
        public string? InstruccionPadreOrtEncuestaIni { get; set; }

        public virtual Empresa Empresa { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
