//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 01/07/2026 15:40:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Estado {

        public Estado()
        {
            this.Ciudad = new List<Ciudad>();
            this.SolicitudAltas = new List<SolicitudAlta>();

        }

        [Key]
        [Required()]
        public long CodigoPais { get; set; }

        [Key]
        [Required()]
        public long CodigoEstado { get; set; }

        [StringLength(30)]
        [Required()]
        public string Nombre { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(10)]
        public string? DgiEstado { get; set; }

        public virtual Pais Pai { get; set; }

        public virtual IList<Ciudad> Ciudad { get; set; }

        public virtual IList<SolicitudAlta> SolicitudAltas { get; set; }

        #region Extensibility Method Definitions


        public override bool Equals(object obj)
        {
          Estado toCompare = obj as Estado;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.CodigoPais, toCompare.CodigoPais))
            return false;
          if (!Object.Equals(this.CodigoEstado, toCompare.CodigoEstado))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + CodigoPais.GetHashCode();
          hashCode = (hashCode * 7) + CodigoEstado.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
