//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 10/03/2026 16:41:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Feriado {

        public Feriado()
        {
            this.VtoCuotasFeriado = @"SI";
            this.ClaseFeriado = @"SI";
            this.AbreFeriado = @"SI";
            this.PruebasFeriado = @"SI";

        }

        [StringLength(80)]
        [Required()]
        public string NombreFeriado { get; set; }

        [Required()]
        public DateTime FechaFeriado { get; set; }

        [StringLength(5)]
        public string? HoraDesdeFeriado { get; set; }

        [StringLength(5)]
        public string? HoraHastaFeriado { get; set; }

        [StringLength(255)]
        public string? ObservacionesFeriado { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(8)]
        public string? HoraIngreso { get; set; }

        [StringLength(2)]
        public string? VtoCuotasFeriado { get; set; }

        [StringLength(2)]
        public string? ClaseFeriado { get; set; }

        [StringLength(2)]
        public string? AbreFeriado { get; set; }

        [StringLength(2)]
        public string? PruebasFeriado { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
