//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 01/07/2026 15:09:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class MotivoEleccionAdmision {

        public MotivoEleccionAdmision()
        {

        }

        [Key]
        [Required()]
        public long IdMotivo { get; set; }

        [Key]
        [Required()]
        public long CodigoPersona { get; set; }

        public virtual MotivoOpcionesAdmision MotivoOpcionesAdmision { get; set; }

        public virtual Persona Persona { get; set; }

        #region Extensibility Method Definitions


        public override bool Equals(object obj)
        {
          MotivoEleccionAdmision toCompare = obj as MotivoEleccionAdmision;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdMotivo, toCompare.IdMotivo))
            return false;
          if (!Object.Equals(this.CodigoPersona, toCompare.CodigoPersona))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdMotivo.GetHashCode();
          hashCode = (hashCode * 7) + CodigoPersona.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
