//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/06/2026 14:36:07
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class OfertaCreditoMateria {

        public OfertaCreditoMateria()
        {
            this.CantInscrCreditoMateria = 0;

        }

        [Key]
        [Required()]
        public long IdOfertaCredito { get; set; }

        [Key]
        [Required()]
        public long IdMateria { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(2)]
        [Required()]
        public string ExamenObligCreditoMateria { get; set; }

        public long? MinimoExonCreditoMateria { get; set; }

        public long? CantInscrCreditoMateria { get; set; }

        public long? CupoCreditoMateria { get; set; }

        public virtual Materia Materia { get; set; }

        public virtual OfertaCredito OfertaCredito { get; set; }

        #region Extensibility Method Definitions


        public override bool Equals(object obj)
        {
          OfertaCreditoMateria toCompare = obj as OfertaCreditoMateria;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.IdOfertaCredito, toCompare.IdOfertaCredito))
            return false;
          if (!Object.Equals(this.IdMateria, toCompare.IdMateria))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + IdOfertaCredito.GetHashCode();
          hashCode = (hashCode * 7) + IdMateria.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
