//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 31/03/2026 10:50:34
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Pais {

        public Pais()
        {
            this.Estado = new List<Estado>();
            this.Personas = new List<Persona>();
            this.SolicitudAltas = new List<SolicitudAlta>();

        }

        [Key]
        [Required()]
        public long CodigoPais { get; set; }

        [StringLength(50)]
        [Required()]
        public string Nombre { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(10)]
        public string? DgiPais { get; set; }

        public virtual IList<Estado> Estado { get; set; }

        public virtual IList<Persona> Personas { get; set; }

        public virtual IList<SolicitudAlta> SolicitudAltas { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
