//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 01/07/2026 15:09:52
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class ParametrosAdmisione {

        public ParametrosAdmisione()
        {

        }

        public long? DiasExtraPermiteInscr1y2 { get; set; }

        public long? DiasExtraPermiteInscr3 { get; set; }

        public long? DiasBorrarDatosEncuesta { get; set; }

        public long? DiasExtraPermiteInscr4 { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
