//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 21/08/2026 15:09:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Parametro {

        public Parametro()
        {
            this.ModificarTnsnames = @"N";
            this.InvocarWsPrevias = @"NO";
            this.InvocarWsGraduacion = @"NO";
            this.InvocarWsCert195 = @"NO";
            this.InvocarPascalPrevias = @"SI";
            this.SeLiberoNTitulos = @"NO";
            this.SeLiberoNCargos = @"NO";
            this.EstaHabilitado6m6 = @"NO";
            this.ResultadoRutinaAlDia = @"WS";
            this.CantMinimaRaquitico = 10m;
            this.CantDiasInscrTradicional = 3m;
            this.CantDiasInscr6m6 = 3m;
            this.ActualizarCodigoVigencia = @"SI";
            this.ConformeHabilitaCreditos = @"NO";
            this.ChequeaPrereqPrevias = @"SI";
            this.ApagarPrimitiva3 = @"NO";
            this.EstaHabilitadoPostulaciones = @"NO";
            this.IdFuncionario9000 = 9000m;
            this.SeLiberoTivenos = @"NO";
            this.CantDiasRasTivenos = 365m;
            this.SgiEsReadonly = @"NO";
            this.SeLiberoFrescoAdmisiones = @"NO";
            this.SeLiberoBecaFuncionarios = @"NO";
            this.SeLiberoPrecioXPaquete = @"NO";
            this.SeLiberoInscrAnticipada70 = @"NO";
            this.SeLiberoNombreWeb = @"NO";

        }

        public long? DiasPlazoPagoInternet { get; set; }

        public long? DiasPlazoPrimitiva { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        public long? DiasVtoPasswordParametros { get; set; }

        public decimal? ValorUroGenerico { get; set; }

        [StringLength(1)]
        [Required()]
        public string ModificarTnsnames { get; set; }

        public decimal? PorcSeniaMinimaVpp { get; set; }

        public double? PorcDtoGraduadoTec { get; set; }

        public double? PorcDtoGraduadoUni { get; set; }

        public DateTime? FecDesdeCtrlDocTitulos { get; set; }

        public DateTime? FecDesdeCtrlInduccion { get; set; }

        [StringLength(300)]
        public string? PasswordLdap { get; set; }

        [StringLength(2)]
        [Required()]
        public string InvocarWsPrevias { get; set; }

        [StringLength(2)]
        [Required()]
        public string InvocarWsGraduacion { get; set; }

        [StringLength(2)]
        public string? InvocarWsCert195 { get; set; }

        [StringLength(2)]
        public string? InvocarPascalPrevias { get; set; }

        [StringLength(2)]
        public string? SeLiberoNTitulos { get; set; }

        public double? PorcDtoGraduadoTecCcg { get; set; }

        public double? PorcDtoGraduadoTecNoCcg { get; set; }

        [StringLength(2)]
        public string? SeLiberoNCargos { get; set; }

        public decimal? ValorUi { get; set; }

        public decimal? CantidadUiDgi3102 { get; set; }

        public decimal? AnioDeduccion3102 { get; set; }

        [StringLength(2)]
        public string? EstaHabilitado6m6 { get; set; }

        [StringLength(30)]
        public string? ResultadoRutinaAlDia { get; set; }

        public decimal? CantMinimaRaquitico { get; set; }

        public decimal? AniomesControl3102 { get; set; }

        [StringLength(20)]
        public string? ReferenciaCartaRector { get; set; }

        public decimal? CantminimahorasPagoCuidantes { get; set; }

        public decimal? ComisionAbitab { get; set; }

        public decimal? ValorUiDiciembre { get; set; }

        public decimal? IdOfertaLegajos { get; set; }

        public decimal? CantDiasInscrTradicional { get; set; }

        public decimal? CantDiasInscr6m6 { get; set; }

        public long? CantEncuestasPosDeptonivel { get; set; }

        public long? CantEncuestasPosProducto { get; set; }

        public long? CantEncuestasCarreras { get; set; }

        public decimal? CantRespEncuestasItem { get; set; }

        public decimal? IdCaja { get; set; }

        public decimal? TopeSobregiro { get; set; }

        public decimal? IdOfertaImpresiones { get; set; }

        public decimal? IdOfertaImpresiones3d { get; set; }

        public DateTime? FechaInicioImpresiones { get; set; }

        public DateTime? FechaFinImpresiones { get; set; }

        public DateTime? Cartel3102Engestion { get; set; }

        public decimal? CantDiasVencimientoImp3d { get; set; }

        [StringLength(2)]
        public string? ActualizarCodigoVigencia { get; set; }

        [StringLength(2)]
        public string? ConformeHabilitaCreditos { get; set; }

        [StringLength(2)]
        public string? ChequeaPrereqPrevias { get; set; }

        [StringLength(2)]
        public string? ApagarPrimitiva3 { get; set; }

        [StringLength(2)]
        public string? EstaHabilitadoPostulaciones { get; set; }

        public decimal? IdFuncionario9000 { get; set; }

        [StringLength(2)]
        public string? SeLiberoTivenos { get; set; }

        public decimal? CantDiasRasTivenos { get; set; }

        [StringLength(2)]
        public string? SgiEsReadonly { get; set; }

        [StringLength(2)]
        public string? SeLiberoFrescoAdmisiones { get; set; }

        [StringLength(2)]
        public string? SeLiberoBecaFuncionarios { get; set; }

        [StringLength(2)]
        public string? SeLiberoPrecioXPaquete { get; set; }

        [StringLength(2)]
        public string? SeLiberoInscrAnticipada70 { get; set; }

        [StringLength(2)]
        public string? SeLiberoNombreWeb { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
