//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/03/2026 12:12:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Prueba {

        public Prueba()
        {
            this.DuracionPrueba = 6m;
            this.HabilitadoSitioadmiPrueba = @"SI";
            this.Accions = new List<Accion>();
            this.InscriptoPruebas = new List<InscriptoPrueba>();

        }

        [Key]
        [Required()]
        public long IdPrueba { get; set; }

        [Required()]
        public long IdComienzo { get; set; }

        [Required()]
        public long IdComienzoPrueba { get; set; }

        [Required()]
        public long IdTipoBeca { get; set; }

        public DateTime? FechaLimiteGuiaPrueba { get; set; }

        public DateTime? FechaEntregaDjPrueba { get; set; }

        [StringLength(12)]
        public string HoraExamenPrueba { get; set; }

        public long? CupoPrueba { get; set; }

        public DateTime? FechaExamenPrueba { get; set; }

        [StringLength(12)]
        public string HoraPresentacionPrueba { get; set; }

        [StringLength(12)]
        public string HoraLimiteGuiaPrueba { get; set; }

        [StringLength(12)]
        public string HoraEntregaDjPrueba { get; set; }

        public DateTime? FechaResultadoPrueba { get; set; }

        [StringLength(12)]
        public string HoraResultadoPrueba { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string HoraIngreso { get; set; }

        [StringLength(30)]
        public string UsuarioIngreso { get; set; }

        public long? IdLocalidad { get; set; }

        [StringLength(1)]
        public string EstadoPrueba { get; set; }

        public DateTime? FechaCaducidadPrueba { get; set; }

        [StringLength(2)]
        public string ControlInscrPrueba { get; set; }

        [StringLength(2)]
        public string HabilitadaPrueba { get; set; }

        [StringLength(1024)]
        public string LugarResultadoPrueba { get; set; }

        public decimal? DuracionPrueba { get; set; }

        public DateTime? FechaDifusionwebPrueba { get; set; }

        [StringLength(2)]
        public string HabilitadoSitioadmiPrueba { get; set; }

        public virtual Comienzo Comienzo { get; set; }

        public virtual TipoDescuento TipoDescuento { get; set; }

        public virtual IList<Accion> Accions { get; set; }

        public virtual IList<InscriptoPrueba> InscriptoPruebas { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
