//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 22/06/2026 13:59:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class TipoParentesco {

        public TipoParentesco()
        {
            this.IntegranteNfDjs = new List<IntegranteNfDj>();

        }

        [Key]
        [Required()]
        public decimal IdTipoParentesco { get; set; }

        [StringLength(15)]
        public string? DescripcionTp { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        public virtual IList<IntegranteNfDj> IntegranteNfDjs { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
