//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/06/2026 12:18:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class TituloOrt {

        public TituloOrt()
        {
            this.PermiteAltaPlanGuiaTitulo = @"SI";
            this.IntermedioTitulo = @"NO";
            this.SePresentaMecTitulo = @"NO";
            this.CertificadoTitulo = @"SI";
            this.Paquetes = new List<Paquete>();

        }

        [Key]
        [Required()]
        public long IdTitulo { get; set; }

        [StringLength(35)]
        [Required()]
        public string NombreTitulo { get; set; }

        [StringLength(60)]
        public string? DescripcionTitulo { get; set; }

        [StringLength(200)]
        public string? ObjetivoTitulo { get; set; }

        [StringLength(200)]
        public string? MetodologiaTitulo { get; set; }

        [StringLength(200)]
        public string? ObservacionesTitulo { get; set; }

        public DateTime? FechaCreacionTitulo { get; set; }

        public DateTime? FechaCaducidadTitulo { get; set; }

        public DateTime? FechaReconocimientoTitulo { get; set; }

        public decimal? DuracionTitulo { get; set; }

        [StringLength(1)]
        public string? DepartamentoTituloRpg { get; set; }

        [StringLength(2)]
        public string? CarreraTituloRpg { get; set; }

        [StringLength(2)]
        public string? PlanTituloRpg { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(12)]
        [Required()]
        public string HoraIngreso { get; set; }

        [Required()]
        public long MinimoMateriasTitulo { get; set; }

        public long? MinimoCreditosTitulo { get; set; }

        public decimal? MinimoPacTitulo { get; set; }

        public long? MaximoRevalidasTitulo { get; set; }

        [Required()]
        public long IdTipoDiploma { get; set; }

        [StringLength(78)]
        [Required()]
        public string NombreExtenso1Titulo { get; set; }

        [StringLength(78)]
        public string? NombreExtenso2Titulo { get; set; }

        public long? IdUnidadTiempo { get; set; }

        [Required()]
        public long IdProducto { get; set; }

        public long? IdRequisitoPac { get; set; }

        [StringLength(1)]
        public string? EstadoTitulo { get; set; }

        [StringLength(10)]
        public string? PlanTitulo { get; set; }

        [StringLength(78)]
        public string? NombreExtensoMasc1Titulo { get; set; }

        [StringLength(78)]
        public string? NombreExtensoMasc2Titulo { get; set; }

        [StringLength(78)]
        public string? NombreExtensoFem1Titulo { get; set; }

        [StringLength(78)]
        public string? NombreExtensoFem2Titulo { get; set; }

        [StringLength(10)]
        public string? ActualizacionTitulo { get; set; }

        [StringLength(2)]
        public string? PermiteAltaPlanGuiaTitulo { get; set; }

        [StringLength(2)]
        public string? IntermedioTitulo { get; set; }

        [StringLength(6)]
        public string? AnioMesPlan { get; set; }

        [StringLength(2)]
        public string? SePresentaMecTitulo { get; set; }

        public DateTime? FechaPresentacionMecTitulo { get; set; }

        public long? CodigoTitulo { get; set; }

        [StringLength(2)]
        public string? CertificadoTitulo { get; set; }

        public decimal? CantBloquesTitulo { get; set; }

        public decimal? IdRequisitoPrevia { get; set; }

        public decimal? IdRequisitoPreviaAlt { get; set; }

        public decimal? IdRequisitoPreviaOtr { get; set; }

        public DateTime? FechaUltActPrereq { get; set; }

        [StringLength(2)]
        public string? CuarentenaTitulo { get; set; }

        public long? IdFamiliaTitulo { get; set; }

        [StringLength(10)]
        public string? TipoTituloOrt { get; set; }

        public long? MaximoCreditosRev { get; set; }

        [StringLength(2)]
        public string? ValidadoTituloOrt { get; set; }

        [StringLength(2)]
        public string? PreviasParcialIgualTotal { get; set; }

        [StringLength(2)]
        public string? GenericoFamilia { get; set; }

        public virtual Producto Producto { get; set; }

        public virtual Titulo Titulo { get; set; }

        public virtual IList<Paquete> Paquetes { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
