//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/03/2026 13:43:06
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Titulo {

        public Titulo()
        {
            this.Bachillerato = @"NO";
            this.DocenteTerciarioTitulo = @"NO";
            this.Personas = new List<Persona>();
            this.SolicitudAltas = new List<SolicitudAlta>();
            this.TituloOrts = new List<TituloOrt>();
            this.BachilleratoPersonas = new List<BachilleratoPersona>();

        }

        [Key]
        [Required()]
        public long CodigoTitulo { get; set; }

        [StringLength(85)]
        [Required()]
        public string Nombre { get; set; }

        [StringLength(200)]
        public string? Observaciones { get; set; }

        [StringLength(12)]
        public string? AbreviaturaEtiqueta { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(12)]
        [Required()]
        public string HoraIngreso { get; set; }

        [StringLength(2)]
        public string? UbicacionEtiquetaIzq { get; set; }

        [StringLength(2)]
        [Required()]
        public string Bachillerato { get; set; }

        public long? IdNivelTitulo { get; set; }

        [StringLength(2)]
        public string? IdNivelPostgrado { get; set; }

        [StringLength(12)]
        public string? AbreviaturaEtiquetaFem { get; set; }

        [StringLength(50)]
        public string? OrientacionTitulo { get; set; }

        public decimal? IdAnioBachiller { get; set; }

        [StringLength(100)]
        public string? OrientacionNewTitulo { get; set; }

        [StringLength(2)]
        public string? DocenteTerciarioTitulo { get; set; }

        public virtual IList<Persona> Personas { get; set; }

        public virtual IList<SolicitudAlta> SolicitudAltas { get; set; }

        public virtual IList<TituloOrt> TituloOrts { get; set; }

        public virtual IList<BachilleratoPersona> BachilleratoPersonas { get; set; }

        public virtual AnioBachiller AnioBachiller { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
