//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 02/07/2026 16:22:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class Turno {

        public Turno()
        {
            this.EncuestaIniAdmisions = new List<EncuestaIniAdmision>();
            this.Ofertas = new List<Oferta>();
            this.InteresProductos = new List<InteresProducto>();

        }

        [Key]
        [Required()]
        public long IdTurno { get; set; }

        [StringLength(30)]
        public string? NombreTurno { get; set; }

        [StringLength(200)]
        public string? ObservacionesTurno { get; set; }

        [StringLength(1)]
        public string? CodigoRpgTurno { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        public virtual IList<EncuestaIniAdmision> EncuestaIniAdmisions { get; set; }

        public virtual IList<Oferta> Ofertas { get; set; }

        public virtual IList<InteresProducto> InteresProductos { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
