//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/06/2026 14:36:07
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class VdEsFrescoAdmision {

        public VdEsFrescoAdmision()
        {

        }

        public long? CodigoPersona { get; set; }

        public DateTime? FechaInscr { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        [Required()]
        public long IdTurno { get; set; }

        [Required()]
        public long IdProducto { get; set; }

        [Required()]
        public long IdComienzo { get; set; }

        public DateTime? FechaInicioComienzo { get; set; }

        [StringLength(2)]
        public string? TipoDocumento { get; set; }

        [StringLength(20)]
        public string? Documento { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
