//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 30/07/2026 11:49:59
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class VdInscriptoCreditoAlumno {

        public VdInscriptoCreditoAlumno()
        {

        }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public long? IdProducto { get; set; }

        [Required()]
        public long IdInscripto { get; set; }

        public long? IdOferta { get; set; }

        [StringLength(30)]
        public string? NombreOferta { get; set; }

        [StringLength(3)]
        [Required()]
        public string NombreCortoOferta { get; set; }

        public long? CodigoPersona { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerApellido { get; set; }

        [StringLength(30)]
        public string? SegundoApellido { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerNombre { get; set; }

        [StringLength(30)]
        public string? SegundoNombre { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerApellidoMay { get; set; }

        [StringLength(30)]
        public string? SegundoApellidoMay { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerNombreMay { get; set; }

        [StringLength(30)]
        public string? SegundoNombreMay { get; set; }

        [Required()]
        public long IdComienzo { get; set; }

        [StringLength(30)]
        public string? NombreComienzo { get; set; }

        public DateTime? FechaInicioComienzo { get; set; }

        public long? IdMateria { get; set; }

        [StringLength(60)]
        [Required()]
        public string DescripcionMateria { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
