//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 01/07/2026 15:40:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class VdProductosDisponibles1y2 {

        public VdProductosDisponibles1y2()
        {

        }

        [Required()]
        public long IdProducto { get; set; }

        [StringLength(1000)]
        public string? NombreWebProducto { get; set; }

        [Required()]
        public long IdNivelProducto { get; set; }

        [StringLength(30)]
        [Required()]
        public string NombreNivelProducto { get; set; }

        public long? OrdenListadoNivelProducto { get; set; }

        [Required()]
        public long IdEscuela { get; set; }

        [StringLength(60)]
        [Required()]
        public string NombreExtensoEscuela { get; set; }

        public long? OrdenListadoEscuela { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
