//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 24/06/2026 16:28:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace BusinessLogic.Entities
{
    public partial class VdProcesosDisponibles1y2 {

        public VdProcesosDisponibles1y2()
        {

        }

        [Required()]
        public long IdProducto { get; set; }

        [Required()]
        public decimal IdProceso { get; set; }

        public decimal? IdTipoProceso { get; set; }

        [StringLength(60)]
        [Required()]
        public string NombreProceso { get; set; }

        [StringLength(200)]
        public string? ObservacionesProceso { get; set; }

        public DateTime? FechaFinProceso { get; set; }

        public DateTime? ComienzoSemestre1Proceso { get; set; }

        public DateTime? Anticipada20porcientoProceso { get; set; }

        public DateTime? Anticipada30porcientoProceso { get; set; }

        public DateTime? Anticipada40porcientoProceso { get; set; }

        public DateTime? Anticipada50porcientoProceso { get; set; }

        public DateTime? Anticipada60porcientoProceso { get; set; }

        public DateTime? Anticipada70porcientoProceso { get; set; }

        #region Extensibility Method Definitions


        #endregion
    }

}
