//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoCentroCostoDevart
    {

        #region Properties

        [Key]
        [StringLength(10)]
        [Required()]
        public string IdCentroCostos { get; set; }

        [StringLength(60)]
        [Required()]
        public string NombreCentroCostos { get; set; }

        [StringLength(200)]
        public string? ObservacionesCentroCostos { get; set; }

        [StringLength(60)]
        public string? NombreCentroCostosAntespsig { get; set; }

        #endregion

        #region Navigation Properties

        public List<DtoProductoDevart> Productos { get; set; }

        #endregion
    }

}
