//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoFeriadoDevart
    {

        #region Properties

        [StringLength(80)]
        [Required()]
        public string NombreFeriado { get; set; }

        [Required()]
        public DateTime FechaFeriado { get; set; }

        [StringLength(5)]
        public string? HoraDesdeFeriado { get; set; }

        [StringLength(5)]
        public string? HoraHastaFeriado { get; set; }

        [StringLength(255)]
        public string? ObservacionesFeriado { get; set; }

        [StringLength(2)]
        public string? VtoCuotasFeriado { get; set; }

        [StringLength(2)]
        public string? ClaseFeriado { get; set; }

        [StringLength(2)]
        public string? AbreFeriado { get; set; }

        [StringLength(2)]
        public string? PruebasFeriado { get; set; }

        #endregion
    }

}
