//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoInscriptoPruebaDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdInscriptoPrueba { get; set; }

        [Required()]
        public long IdPrueba { get; set; }

        public long? IdProducto { get; set; }

        [Required()]
        public long CodigoPersona { get; set; }

        public long? PuntosVerbalInscriptoPrueba { get; set; }

        public long? PuntosMatInscriptoPrueba { get; set; }

        [StringLength(3)]
        public string? ResultadoInscriptoPrueba { get; set; }

        public decimal? DjIngresoInscriptoPrueba { get; set; }

        public decimal? DjIntegranInscriptoPrueba { get; set; }

        [StringLength(1)]
        public string? EstadoInscriptoPrueba { get; set; }

        public DateTime? FechaEstadoInscriptoPrueba { get; set; }

        public DateTime? FechaCartaInscriptoPrueba { get; set; }

        public DateTime? RenunciaInscriptoPrueba { get; set; }

        [StringLength(2)]
        public string? AplicadaInscriptoPrueba { get; set; }

        [StringLength(2)]
        public string? DefinitivoInscriptoPrueba { get; set; }

        [StringLength(30)]
        public string? UsuarioInscriptoPrueba { get; set; }

        public long? PromedioAntInscriptoPrueba { get; set; }

        public long? CodigoInstitucionBac { get; set; }

        public long? CodigoTipoBachillerato { get; set; }

        public DateTime? FechaInscriptoPrueba { get; set; }

        public DateTime? DjFechaInscriptoPrueba { get; set; }

        public long? ModeloCartaInscriptoPrueba { get; set; }

        public long? PtosMatAntInscriptoPrueba { get; set; }

        public long? PtosVblAntInscriptoPrueba { get; set; }

        public decimal? PorcBecaInscriptoPrueba { get; set; }

        public long? RankingInscriptoPrueba { get; set; }

        public long? CodigoUniversidad { get; set; }

        [StringLength(1)]
        public string? RangoInscriptoPrueba { get; set; }

        public long? MejorTotalInscriptoPrueba { get; set; }

        public decimal? PorcBecaAntInscriptoPrueba { get; set; }

        public long? IdProductoOriginal { get; set; }

        public long? IdTipoBecaOrigen { get; set; }

        public decimal? PorcOrigenInscriptoPrueba { get; set; }

        public long? ModeloAntInscriptoPrueba { get; set; }

        [StringLength(2)]
        public string? MirarDocInscriptoPrueba { get; set; }

        public decimal? PorcAcumInscriptoPrueba { get; set; }

        public long? TotalRankingInscriptoPrueba { get; set; }

        public long? DjDtoLegalInscriptoPrueba { get; set; }

        [StringLength(2)]
        public string? FamCursaOrtInscriptoPrueba { get; set; }

        public decimal? DjEgresosInscriptoPrueba { get; set; }

        public long? CanFamCursaInscriptoPrueba { get; set; }

        public long? PtosRedAntInscriptoPrueba { get; set; }

        public long? PuntosRedacInscriptoPrueba { get; set; }

        public long? GtoInteriorInscriptoPrueba { get; set; }

        [StringLength(90)]
        public string? InstitucionInscriptoPrueba { get; set; }

        [StringLength(60)]
        public string? MailInscriptoPrueba { get; set; }

        [StringLength(2)]
        [Required()]
        public string SeEnvioMailInscriptoPrueba { get; set; }

        [StringLength(60)]
        public string? SalonPaaInscriptoPrueba { get; set; }

        #endregion

        #region Navigation Properties

        public DtoEmpresaDevart Empresa { get; set; }

        public DtoProductoDevart Producto_IdProducto { get; set; }

        public DtoPersonaDevart Persona { get; set; }

        public DtoProductoDevart Producto_IdProductoOriginal { get; set; }

        public DtoPruebaDevart Prueba { get; set; }

        #endregion
    }

}
