//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoTurnoDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdTurno { get; set; }

        [StringLength(30)]
        public string? NombreTurno { get; set; }

        [StringLength(200)]
        public string? ObservacionesTurno { get; set; }

        [StringLength(1)]
        public string? CodigoRpgTurno { get; set; }

        #endregion
    }

}
