//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoVdInscriptoCreditoAlumnoDevart
    {

        #region Properties

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public long? IdProducto { get; set; }

        [Required()]
        public long IdInscripto { get; set; }

        public long? IdOferta { get; set; }

        [StringLength(30)]
        public string? NombreOferta { get; set; }

        [StringLength(3)]
        [Required()]
        public string NombreCortoOferta { get; set; }

        public long? CodigoPersona { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerApellido { get; set; }

        [StringLength(30)]
        public string? SegundoApellido { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerNombre { get; set; }

        [StringLength(30)]
        public string? SegundoNombre { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerApellidoMay { get; set; }

        [StringLength(30)]
        public string? SegundoApellidoMay { get; set; }

        [StringLength(30)]
        [Required()]
        public string PrimerNombreMay { get; set; }

        [StringLength(30)]
        public string? SegundoNombreMay { get; set; }

        [Required()]
        public long IdComienzo { get; set; }

        [StringLength(30)]
        public string? NombreComienzo { get; set; }

        public DateTime? FechaInicioComienzo { get; set; }

        public long? IdMateria { get; set; }

        [StringLength(60)]
        [Required()]
        public string DescripcionMateria { get; set; }

        #endregion
    }

}
