/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActualizarPersonaRequest { 
    primerApellido?: string | null;
    segundoApellido?: string | null;
    primerNombre?: string | null;
    segundoNombre?: string | null;
    mail?: string | null;
    verificacionMail?: string | null;
    direccion?: string | null;
    sexo?: string | null;
    fechaNacimiento?: string;
    telefono1?: string | null;
    telefono2?: string | null;
    codigoPais?: number;
    codigoEstado?: number;
    codigoCiudad?: number;
    documento?: string | null;
    tipoDocumento?: string | null;
    trabajaActualmente?: string | null;
    tipoJornada?: number;
}

