/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoProcesoDevart } from './dtoProcesoDevart';
import { DtoAccionDevart } from './dtoAccionDevart';


export interface DtoActividadDevart { 
    idActividad: number;
    idFormaContacto?: number | null;
    idTipoActividad?: number | null;
    idTipoAccion?: number | null;
    idSeleccionPersona?: number | null;
    usernameAsignadoActividad?: string | null;
    idGrupoTrabajo?: number | null;
    fechaDesdeAsignadoActividad?: string | null;
    fechaHastaAsignadoActividad?: string | null;
    horaDesdeAsignadoActividad?: string | null;
    horaHastaAsignadoActividad?: string | null;
    idEstadoAccion?: number | null;
    usernameGeneradorActividad?: string | null;
    fechaGeneradorActividad?: string | null;
    observacionesActividad?: string | null;
    fechaRealizadoActividad?: string | null;
    usernameRealizadoActividad?: string | null;
    usuarioIngreso?: string | null;
    fechaIngreso?: string | null;
    horaIngreso?: string | null;
    idEvento?: number | null;
    idProceso: number;
    proceso?: DtoProcesoDevart;
    accions?: Array<DtoAccionDevart> | null;
}

