/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoPersonaDevart } from './dtoPersonaDevart';


export interface DtoCaracteristicaPaiDevart { 
    idCaracteristicaPais: number;
    nombrePais: string;
    iso2: string;
    caracteristica: number;
    usuarioIngreso: string;
    fechaIngreso: string;
    horaIngreso: string;
    personas_IdCaracteristicaPaisTel1?: Array<DtoPersonaDevart> | null;
    personas_IdCaracteristicaPaisTel2?: Array<DtoPersonaDevart> | null;
}

