/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoDatosPreInscripcion } from './dtoDatosPreInscripcion';


export interface DtoDatosPreInscripcionOperationResult { 
    success?: boolean;
    httpCode?: number;
    errorCode?: string | null;
    method?: string | null;
    message?: string | null;
    data: DtoDatosPreInscripcion;
}

