/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoInscriptoPruebaDevart } from './dtoInscriptoPruebaDevart';
import { DtoBachilleratoPersonaDevart } from './dtoBachilleratoPersonaDevart';
import { DtoCiudadDevart } from './dtoCiudadDevart';
import { DtoInscriptoDevart } from './dtoInscriptoDevart';
import { DtoSolicitudAltaDevart } from './dtoSolicitudAltaDevart';
import { DtoPersonaDevart } from './dtoPersonaDevart';
import { DtoEncuestaIniAdmisionDevart } from './dtoEncuestaIniAdmisionDevart';


export interface DtoEmpresaDevart { 
    codigoEmpresa: number;
    nombre: string;
    observaciones?: string | null;
    direccion?: string | null;
    codigoPais?: number | null;
    codigoEstado?: number | null;
    codigoCiudad?: number | null;
    codigoPostal?: string | null;
    codigoFidelidadDireccion?: string | null;
    telefono1?: string | null;
    telefono2?: string | null;
    telefono3?: string | null;
    telefono4?: string | null;
    telefono5?: string | null;
    fax1?: string | null;
    fax2?: string | null;
    email?: string | null;
    fechaFidelidadDireccion?: string | null;
    codigoTipoEmpresa: number;
    codigoVigencia: string;
    institucionEducativa?: string | null;
    codigoGiroEmpresa: number;
    rucEmpresa?: string | null;
    razonsocial?: string | null;
    paraFacturacion?: string | null;
    habilitadaInscripciones?: string | null;
    paraPagosFinanciadosEmpresa?: string | null;
    paraCanjeContableEmpresa?: string | null;
    paraVoucherEmpresa?: string | null;
    clientePsig?: string | null;
    paraBachilleratoEmpresa?: string | null;
    paraGradoEmpresa?: string | null;
    paraPostgradoEmpresa?: string | null;
    paraCuidantiasEmpresa?: string | null;
    emailCuidantiasEmpresa?: string | null;
    nombreMayEmpresa?: string | null;
    paraSgiEmpresa: string;
    idSegmentoLiceo?: number | null;
    ciudad?: DtoCiudadDevart;
    personas?: Array<DtoPersonaDevart> | null;
    encuestaIniAdmisions?: Array<DtoEncuestaIniAdmisionDevart> | null;
    solicitudAltas?: Array<DtoSolicitudAltaDevart> | null;
    inscriptos?: Array<DtoInscriptoDevart> | null;
    bachilleratoPersonas?: Array<DtoBachilleratoPersonaDevart> | null;
    inscriptoPruebas?: Array<DtoInscriptoPruebaDevart> | null;
}

