/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DtoInscripcionRealizada { 
    fechaInscripcion?: string;
    idProducto?: number;
    nombreProducto?: string | null;
    nombreComienzo?: string | null;
    nombreTurno?: string | null;
}

