/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoComienzoDevart } from './dtoComienzoDevart';
import { DtoTipoBecaNivelProductoDevart } from './dtoTipoBecaNivelProductoDevart';
import { DtoProductoDevart } from './dtoProductoDevart';


export interface DtoNivelProductoDevart { 
    idNivelProducto: number;
    nombreNivelProducto: string;
    observacionesNivelProducto?: string | null;
    ordenListadoNivelProducto?: number | null;
    tipoEntregaNivelProducto?: number | null;
    idComienzoActivo?: number | null;
    desdeComienzoNivelProducto?: string | null;
    hastaComienzoNivelProducto?: string | null;
    cantAluConsiderarDictado?: number | null;
    cantAluParaRaquitico?: number | null;
    nombreNivelEnInforme?: string | null;
    ordenFormNivelProducto?: number | null;
    agrupNivelProducto?: string | null;
    productos?: Array<DtoProductoDevart> | null;
    tipoBecaNivelProductos?: Array<DtoTipoBecaNivelProductoDevart> | null;
    comienzo?: DtoComienzoDevart;
}

