/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoOfertaDevart } from './dtoOfertaDevart';


export interface DtoOfertaDevartIEnumerableOperationResult { 
    success?: boolean;
    httpCode?: number;
    errorCode?: string | null;
    method?: string | null;
    message?: string | null;
    data: Array<DtoOfertaDevart> | null;
}

