/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoProductoDevart } from './dtoProductoDevart';
import { DtoTituloOrtDevart } from './dtoTituloOrtDevart';


export interface DtoPaqueteDevart { 
    idPaquete: number;
    nombrePaquete?: string | null;
    idProducto?: number | null;
    idTitulo?: number | null;
    semestrePaquete?: number | null;
    generaPlanAnclaPaquete: string;
    minimoCreditosPaquete: number;
    observacionesPaquete?: string | null;
    carreraRpg?: string | null;
    idTipoPaqCom?: number | null;
    visibleInternetPaquete?: string | null;
    admiteDescuentosPaquete?: string | null;
    estadoPaquete?: string | null;
    cantCuotasAjustePaquete?: number | null;
    producto?: DtoProductoDevart;
    tituloOrt?: DtoTituloOrtDevart;
}

