/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoPersonaDevart } from './dtoPersonaDevart';


export interface DtoPersonaAdmiteDevart { 
    codigoPersona: number;
    nroAdmite2?: number | null;
    estadoAdmite?: string | null;
    nroAdmite1?: number | null;
    horaIngreso?: string | null;
    fechaIngreso?: string | null;
    usuarioIngreso?: string | null;
    procesadoPersonaAdmite?: string | null;
    procesahistoriaPersonaAdmite?: string | null;
    preferenciaPersonaAdmite?: string | null;
    fechaFrescoPersonaAdmite?: string | null;
    persona?: DtoPersonaDevart;
}

