/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistroConfirmarSolicitudAltaRequest { 
    tipoDocumento: string;
    documento: string;
    idProducto?: number;
    idProceso?: number;
    primerApellido: string;
    segundoApellido?: string | null;
    primerNombre: string;
    segundoNombre?: string | null;
    fechaNacimiento?: string;
    sexo: string;
    direccion?: string | null;
    telefono1: string;
    telefono2?: string | null;
    mail: string;
    verificacionMail: string;
}

