/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArchivoPayload } from './archivoPayload';


export interface UploadArchivoIngresoRequest { 
    idIngresoMensualNF: number;
    archivoAdjunto?: ArchivoPayload;
}

