sonar.sources=src
sonar.tests=src
sonar.exclusions=**/*.spec.ts,src/environments/**
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/admisiones/lcov.info
sonar.sourceEncoding=UTF-8