//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoAccionDevart
    {

        #region Properties

        [Key]
        [Required()]
        public decimal IdAccion { get; set; }

        [StringLength(30)]
        public string? UsuarioLockeadorAccion { get; set; }

        [StringLength(12)]
        public string? ProcesoLockeadorAccion { get; set; }

        [Required()]
        public decimal IdActividad { get; set; }

        public long? CodigoPersona { get; set; }

        [StringLength(8)]
        public string? HoraIngreso { get; set; }

        public DateTime? FechaRealizadoAccion { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        public decimal? IdEstadoAccion { get; set; }

        [StringLength(30)]
        public string? UsuarioRealizadoAccion { get; set; }

        public decimal? IdAccionResultado { get; set; }

        [StringLength(1000)]
        public string? ObservacionesAccion { get; set; }

        public long? IdPrueba { get; set; }

        #endregion

        #region Navigation Properties

        public DtoPersonaDevart Persona { get; set; }

        public DtoPruebaDevart Prueba { get; set; }

        #endregion
    }

}
