//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoCiudadDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long CodigoPais { get; set; }

        [Key]
        [Required()]
        public long CodigoEstado { get; set; }

        [Key]
        [Required()]
        public long CodigoCiudad { get; set; }

        [StringLength(30)]
        [Required()]
        public string Nombre { get; set; }

        [StringLength(10)]
        public string? DgiCiudad { get; set; }

        #endregion

        #region Navigation Properties

        public List<DtoEmpresaDevart> Empresas { get; set; }

        public DtoEstadoDevart Estado { get; set; }

        public List<DtoPersonaDevart> Personas { get; set; }

        public List<DtoSolicitudAltaDevart> SolicitudAltas { get; set; }

        #endregion
    }

}
