//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoCausalInscrPagoDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdCausalInscrPago { get; set; }

        [StringLength(30)]
        [Required()]
        public string NombreCausalInscrPago { get; set; }

        [StringLength(400)]
        public string? ObservacionesCausalInscrPag { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(12)]
        public string? HoraIngreso { get; set; }

        #endregion

        #region Navigation Properties

        public List<DtoInscriptoDevart> Inscriptos { get; set; }

        #endregion
    }

}
