//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoEmpresaDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long CodigoEmpresa { get; set; }

        [StringLength(90)]
        [Required()]
        public string Nombre { get; set; }

        [StringLength(200)]
        public string? Observaciones { get; set; }

        [StringLength(60)]
        public string? Direccion { get; set; }

        public long? CodigoPais { get; set; }

        public long? CodigoEstado { get; set; }

        public long? CodigoCiudad { get; set; }

        [StringLength(20)]
        public string? CodigoPostal { get; set; }

        [StringLength(2)]
        public string? CodigoFidelidadDireccion { get; set; }

        [StringLength(20)]
        public string? Telefono1 { get; set; }

        [StringLength(20)]
        public string? Telefono2 { get; set; }

        [StringLength(20)]
        public string? Telefono3 { get; set; }

        [StringLength(20)]
        public string? Telefono4 { get; set; }

        [StringLength(20)]
        public string? Telefono5 { get; set; }

        [StringLength(20)]
        public string? Fax1 { get; set; }

        [StringLength(20)]
        public string? Fax2 { get; set; }

        [StringLength(60)]
        public string? Email { get; set; }

        public DateTime? FechaFidelidadDireccion { get; set; }

        [Required()]
        public long CodigoTipoEmpresa { get; set; }

        [StringLength(2)]
        [Required()]
        public string CodigoVigencia { get; set; }

        [StringLength(2)]
        public string? InstitucionEducativa { get; set; }

        [Required()]
        public long CodigoGiroEmpresa { get; set; }

        [StringLength(22)]
        public string? RucEmpresa { get; set; }

        [StringLength(105)]
        public string? Razonsocial { get; set; }

        [StringLength(2)]
        public string? ParaFacturacion { get; set; }

        [StringLength(2)]
        public string? HabilitadaInscripciones { get; set; }

        [StringLength(2)]
        public string? ParaPagosFinanciadosEmpresa { get; set; }

        [StringLength(2)]
        public string? ParaCanjeContableEmpresa { get; set; }

        [StringLength(2)]
        public string? ParaVoucherEmpresa { get; set; }

        [StringLength(6)]
        public string? ClientePsig { get; set; }

        [StringLength(2)]
        public string? ParaBachilleratoEmpresa { get; set; }

        [StringLength(2)]
        public string? ParaGradoEmpresa { get; set; }

        [StringLength(2)]
        public string? ParaPostgradoEmpresa { get; set; }

        [StringLength(2)]
        public string? ParaCuidantiasEmpresa { get; set; }

        [StringLength(60)]
        public string? EmailCuidantiasEmpresa { get; set; }

        [StringLength(90)]
        public string? NombreMayEmpresa { get; set; }

        [StringLength(2)]
        [Required()]
        public string ParaSgiEmpresa { get; set; }

        public long? IdSegmentoLiceo { get; set; }

        #endregion

        #region Navigation Properties

        public DtoCiudadDevart Ciudad { get; set; }

        public List<DtoPersonaDevart> Personas { get; set; }

        public List<DtoEncuestaIniAdmisionDevart> EncuestaIniAdmisions { get; set; }

        public List<DtoSolicitudAltaDevart> SolicitudAltas { get; set; }

        public List<DtoInscriptoDevart> Inscriptos { get; set; }

        public List<DtoBachilleratoPersonaDevart> BachilleratoPersonas { get; set; }

        public List<DtoInscriptoPruebaDevart> InscriptoPruebas { get; set; }

        public List<DtoEncuestaIniDevart> EncuestaInis { get; set; }

        public List<DtoEmpresaConsideradaAdmisionDevart> EmpresaConsideradaAdmisions { get; set; }

        public List<DtoEducacionSuperiorAdmisionDevart> EducacionSuperiorAdmisions { get; set; }

        #endregion
    }

}
