//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoInteresProductoDevart
    {

        #region Properties

        [Key]
        [Required()]
        public decimal IdInteres { get; set; }

        [Key]
        [Required()]
        public long IdProducto { get; set; }

        [Required()]
        public decimal IdTipoInteres { get; set; }

        [Required()]
        public decimal IdGradoInteres { get; set; }

        [StringLength(8)]
        public string? HoraIngreso { get; set; }

        public DateTime? FechaInteresProd { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(200)]
        public string? ObservacionesInteresProd { get; set; }

        public decimal? IdGradoInteresAnt { get; set; }

        public long? IdTurno { get; set; }

        public DateTime? FechaAltaInteresProd { get; set; }

        [StringLength(30)]
        public string? UsuarioModifInteresProd { get; set; }

        public DateTime? FechaModifInteresProd { get; set; }

        public decimal? IdgradoantModifInteresProd { get; set; }

        #endregion

        #region Navigation Properties

        public DtoIntereDevart Intere { get; set; }

        public DtoProductoDevart Producto { get; set; }

        public DtoTurnoDevart Turno { get; set; }

        #endregion
    }

}
