//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoIntereDevart
    {

        #region Properties

        [Key]
        [Required()]
        public decimal IdInteres { get; set; }

        [Required()]
        public long CodigoPersona { get; set; }

        [Required()]
        public long IdProceso { get; set; }

        [Required()]
        public decimal IdFormaContacto { get; set; }

        [StringLength(8)]
        [Required()]
        public string HoraIngreso { get; set; }

        [StringLength(31)]
        [Required()]
        public string ContactadorInteres { get; set; }

        [StringLength(200)]
        public string? ObservacionesInteres { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [Required()]
        public decimal IdLugar { get; set; }

        [Required()]
        public decimal IdGradoPureza { get; set; }

        #endregion

        #region Navigation Properties

        public DtoPersonaDevart Persona { get; set; }

        public DtoProcesoDevart Proceso { get; set; }

        public List<DtoInteresProductoDevart> InteresProductos { get; set; }

        #endregion
    }

}
