//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoMateriaDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdMateria { get; set; }

        [StringLength(30)]
        [Required()]
        public string NombreMateria { get; set; }

        [StringLength(60)]
        [Required()]
        public string DescripcionMateria { get; set; }

        [StringLength(200)]
        public string? ObjetivoMateria { get; set; }

        [StringLength(200)]
        public string? MetodologiaMateria { get; set; }

        [StringLength(200)]
        public string? ObservacionesMateria { get; set; }

        [Required()]
        public DateTime FechaCreacionMateria { get; set; }

        public DateTime? FechaCaducidadMateria { get; set; }

        public long? IdNivelMateria { get; set; }

        [Required()]
        public long IdTipoMateria { get; set; }

        public long? SesionesClaseSemanaMateria { get; set; }

        public long? MinutosSesionClaseMateria { get; set; }

        public long? SesionesClaseLabMateria { get; set; }

        public long? MinutosSesionLabMateria { get; set; }

        public long? OtrasSesionesSemanaMateria { get; set; }

        public long? MinutosOtraSesionMateria { get; set; }

        public long? DuracionSemanasMateria { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(12)]
        [Required()]
        public string HoraIngreso { get; set; }

        [StringLength(1)]
        public string? DepartamentoMateriaRpg { get; set; }

        [StringLength(2)]
        public string? CarreraMateriaRpg { get; set; }

        [StringLength(2)]
        public string? PlanMateriaRpg { get; set; }

        [StringLength(2)]
        public string? CodigoMateriaRpg { get; set; }

        [StringLength(2)]
        [Required()]
        public string ExamenObligatorioMateria { get; set; }

        [StringLength(2)]
        public string? CursoObligatorioMateria { get; set; }

        public long? PesoMateria { get; set; }

        [StringLength(3)]
        public string? SemestreMateria { get; set; }

        [StringLength(3)]
        public string? SupraSemestreMateria { get; set; }

        [StringLength(2)]
        public string? FicticiaMateria { get; set; }

        public long? MinimoAprobacionMateria { get; set; }

        public decimal? CargaHorariaSemanalMateria { get; set; }

        [Required()]
        public decimal CargaHorariaTotalMateria { get; set; }

        [StringLength(2)]
        public string? PrerequisitoMateria { get; set; }

        [StringLength(1)]
        [Required()]
        public string EstadoMateria { get; set; }

        [Required()]
        public long IdDepartamentoCreador { get; set; }

        [StringLength(2)]
        [Required()]
        public string TieneRepechajeMateria { get; set; }

        public long? MinimoParaRepechajeMateria { get; set; }

        [Required()]
        public decimal IndiceDocenteMateria { get; set; }

        public long? MinimoExamenMateria { get; set; }

        public long? MaxBonificacionExamenMat { get; set; }

        public long? IdCatedra { get; set; }

        public decimal? CargaHorariaSemFrontalMat { get; set; }

        public decimal? CargaHorariaTotFrontalMat { get; set; }

        public long? MinimoExoneracionMateria { get; set; }

        [StringLength(60)]
        public string? TituloLibroMateria { get; set; }

        public decimal? PrecioLibroMateria { get; set; }

        [StringLength(10)]
        public string? IdMoneda { get; set; }

        public long? CodigoBachillerato { get; set; }

        public long? MaxIntegrantesEquipoMat { get; set; }

        public decimal? IdPrereqIncompletoMateria { get; set; }

        public decimal? PesoCostoMateria { get; set; }

        [StringLength(60)]
        public string? DescripcionInglesMateria { get; set; }

        public decimal? EctsMateria { get; set; }

        [Required()]
        public decimal CreditosImpresionMateria { get; set; }

        [StringLength(2)]
        public string? PrecioCero6m6Materia { get; set; }

        public decimal? IdTipoTrabajoFinal { get; set; }

        public decimal? MaxAlumnosPordictadoMateria { get; set; }

        public decimal? CantalumDictraquiticoMateria { get; set; }

        public decimal? DuracionExamenMateria { get; set; }

        [StringLength(2)]
        public string? AdmiteExamenConsigna { get; set; }

        public decimal? PesoCreditosMateria { get; set; }

        #endregion

        #region Navigation Properties

        public DtoTituloDevart Titulo { get; set; }

        public DtoDepartamentoDevart Departamento { get; set; }

        public List<DtoOfertaCreditoMateriaDevart> OfertaCreditoMaterias { get; set; }

        #endregion
    }

}
