//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoOfertaDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdOferta { get; set; }

        [Required()]
        public long IdSupraoferta { get; set; }

        [StringLength(30)]
        public string? NombreOferta { get; set; }

        [Required()]
        public long IdTurno { get; set; }

        [Required()]
        public long IdLocalidad { get; set; }

        public long? CupoOferta { get; set; }

        [StringLength(2)]
        [Required()]
        public string InscripcionesAbiertasOferta { get; set; }

        [Required()]
        public decimal PorcentPrecioPaqueteOferta { get; set; }

        [StringLength(2)]
        [Required()]
        public string AceptaCondicionalesOferta { get; set; }

        [StringLength(200)]
        public string? HorarioReferenciaOferta { get; set; }

        [StringLength(200)]
        public string? ObservacionesOferta { get; set; }

        [Required()]
        public long MinimoCreditosOferta { get; set; }

        [Required()]
        public long CantidadInscriptosOferta { get; set; }

        [StringLength(3)]
        [Required()]
        public string NombreCortoOferta { get; set; }

        [StringLength(1)]
        public string? TurnoRpg { get; set; }

        [StringLength(1)]
        public string? DepRpg { get; set; }

        [StringLength(2)]
        public string? CarrRpg { get; set; }

        [StringLength(8)]
        public string? FechaComRpg { get; set; }

        [StringLength(3)]
        public string? SemestreRpg { get; set; }

        [StringLength(1)]
        public string? GrupoRpg { get; set; }

        public DateTime? FechaNormal { get; set; }

        [StringLength(2)]
        public string? CupoRestringidoOferta { get; set; }

        [StringLength(2)]
        public string? IncompanyOferta { get; set; }

        #endregion

        #region Navigation Properties

        public DtoSupraofertaDevart Supraoferta { get; set; }

        public DtoLocalidadDevart Localidad { get; set; }

        public DtoTurnoDevart Turno { get; set; }

        #endregion
    }

}
