//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoProcesoProductoDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdProceso { get; set; }

        [Key]
        [Required()]
        public long IdProducto { get; set; }

        [StringLength(8)]
        public string? HoraIngreso { get; set; }

        public DateTime? FechaIngreso { get; set; }

        [StringLength(30)]
        public string? UsuarioIngreso { get; set; }

        #endregion

        #region Navigation Properties

        public DtoProductoDevart Producto { get; set; }

        public DtoProcesoDevart Proceso { get; set; }

        #endregion
    }

}
