//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoPublicidadEleccionAdmisionDevart
    {

        #region Properties

        [Key]
        [Required()]
        public long IdPublicidad { get; set; }

        [Key]
        [Required()]
        public long CodigoPersona { get; set; }

        [Required()]
        public DateTime FechaIngreso { get; set; }

        [StringLength(8)]
        [Required()]
        public string HoraIngreso { get; set; }

        [StringLength(30)]
        [Required()]
        public string UsuarioIngreso { get; set; }

        #endregion

        #region Navigation Properties

        public DtoPersonaDevart Persona { get; set; }

        public DtoPublicidadOpcionesAdmisionDevart PublicidadOpcionesAdmision { get; set; }

        #endregion
    }

}
