//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 21/08/2026 15:09:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class EscuelaRepository : EntityFrameworkRepository<BusinessLogic.Entities.Escuela>, IEscuelaRepository
    {
        public EscuelaRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Escuela> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Escuela GetByKey(long _IdEscuela)
        {
            return objectSet.SingleOrDefault(e => e.IdEscuela == _IdEscuela);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
