//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class TipoEgresoDjRepository
    {
        public virtual ICollection<BusinessLogic.Entities.TipoEgresoDj> GetActivosOrdenados()
        {
            return objectSet
                .Where(e => e.Activo == "SI")
                .OrderBy(e => e.Orden)
                .ToList();
        }
    }
}
