//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class InscriptoSeniaMinimumConverter
    {

        public static DtoInscriptoSeniaMinimumDevart ToDto(this BusinessLogic.Entities.InscriptoSeniaMinimum source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoInscriptoSeniaMinimumDevart ToDtoWithRelated(this BusinessLogic.Entities.InscriptoSeniaMinimum source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoInscriptoSeniaMinimumDevart();

            // Properties
            target.IdInscripto = source.IdInscripto;
            target.MetodoPagoSeniaMinima = source.MetodoPagoSeniaMinima;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.InscriptoSeniaMinimum ToEntity(this DtoInscriptoSeniaMinimumDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.InscriptoSeniaMinimum();

            // Properties
            target.IdInscripto = source.IdInscripto;
            target.MetodoPagoSeniaMinima = source.MetodoPagoSeniaMinima;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoInscriptoSeniaMinimumDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.InscriptoSeniaMinimum> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoInscriptoSeniaMinimumDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.InscriptoSeniaMinimum> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.InscriptoSeniaMinimum> ToEntities(this IEnumerable<DtoInscriptoSeniaMinimumDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.InscriptoSeniaMinimum source, DtoInscriptoSeniaMinimumDevart target);

        static partial void OnEntityCreating(DtoInscriptoSeniaMinimumDevart source, BusinessLogic.Entities.InscriptoSeniaMinimum target);

    }

}
