//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PlanPagoConverter
    {

        public static DtoPlanPagoDevart ToDto(this BusinessLogic.Entities.PlanPago source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPlanPagoDevart ToDtoWithRelated(this BusinessLogic.Entities.PlanPago source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPlanPagoDevart();

            // Properties
            target.IdPlanPago = source.IdPlanPago;
            target.NombrePlanPago = source.NombrePlanPago;
            target.CantidadCuotasPlanPago = source.CantidadCuotasPlanPago;
            target.PorcentajeRecargo = source.PorcentajeRecargo;
            target.PorcentajeMatricula = source.PorcentajeMatricula;
            target.PorcentajeSeniaMinima = source.PorcentajeSeniaMinima;
            target.IdMoneda = source.IdMoneda;
            target.ObservacionesPlanPago = source.ObservacionesPlanPago;
            target.IdRegimenPlanPago = source.IdRegimenPlanPago;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.PlanPago ToEntity(this DtoPlanPagoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.PlanPago();

            // Properties
            target.IdPlanPago = source.IdPlanPago;
            target.NombrePlanPago = source.NombrePlanPago;
            target.CantidadCuotasPlanPago = source.CantidadCuotasPlanPago;
            target.PorcentajeRecargo = source.PorcentajeRecargo;
            target.PorcentajeMatricula = source.PorcentajeMatricula;
            target.PorcentajeSeniaMinima = source.PorcentajeSeniaMinima;
            target.IdMoneda = source.IdMoneda;
            target.ObservacionesPlanPago = source.ObservacionesPlanPago;
            target.IdRegimenPlanPago = source.IdRegimenPlanPago;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPlanPagoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.PlanPago> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPlanPagoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.PlanPago> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.PlanPago> ToEntities(this IEnumerable<DtoPlanPagoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.PlanPago source, DtoPlanPagoDevart target);

        static partial void OnEntityCreating(DtoPlanPagoDevart source, BusinessLogic.Entities.PlanPago target);

    }

}
