//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class VdInscripcionesFresco3y4Converter
    {

        public static DtoVdInscripcionesFresco3y4Devart ToDto(this BusinessLogic.Entities.VdInscripcionesFresco3y4 source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoVdInscripcionesFresco3y4Devart ToDtoWithRelated(this BusinessLogic.Entities.VdInscripcionesFresco3y4 source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoVdInscripcionesFresco3y4Devart();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.FechaInscripcion = source.FechaInscripcion;
            target.UsuarioInscripcion = source.UsuarioInscripcion;
            target.IdTurno = source.IdTurno;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaInicioComienzo = source.FechaInicioComienzo;
            target.NombreExtensoProducto = source.NombreExtensoProducto;
            target.IdNivelProducto = source.IdNivelProducto;
            target.NombreComienzo = source.NombreComienzo;
            target.NombreTurno = source.NombreTurno;
            target.IdProceso = source.IdProceso;
            target.FechaReferencia = source.FechaReferencia;
            target.IdInscripto = source.IdInscripto;
            target.EstadoInscripcion = source.EstadoInscripcion;
            target.VengoDe = source.VengoDe;
            target.IdOferta = source.IdOferta;
            target.DescripcionOferta = source.DescripcionOferta;
            target.ProgConSeminariosProducto = source.ProgConSeminariosProducto;
            target.FechaVtoInscr = source.FechaVtoInscr;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.VdInscripcionesFresco3y4 ToEntity(this DtoVdInscripcionesFresco3y4Devart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.VdInscripcionesFresco3y4();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.FechaInscripcion = source.FechaInscripcion;
            target.UsuarioInscripcion = source.UsuarioInscripcion;
            target.IdTurno = source.IdTurno;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaInicioComienzo = source.FechaInicioComienzo;
            target.NombreExtensoProducto = source.NombreExtensoProducto;
            target.IdNivelProducto = source.IdNivelProducto;
            target.NombreComienzo = source.NombreComienzo;
            target.NombreTurno = source.NombreTurno;
            target.IdProceso = source.IdProceso;
            target.FechaReferencia = source.FechaReferencia;
            target.IdInscripto = source.IdInscripto;
            target.EstadoInscripcion = source.EstadoInscripcion;
            target.VengoDe = source.VengoDe;
            target.IdOferta = source.IdOferta;
            target.DescripcionOferta = source.DescripcionOferta;
            target.ProgConSeminariosProducto = source.ProgConSeminariosProducto;
            target.FechaVtoInscr = source.FechaVtoInscr;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoVdInscripcionesFresco3y4Devart> ToDtos(this IEnumerable<BusinessLogic.Entities.VdInscripcionesFresco3y4> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoVdInscripcionesFresco3y4Devart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.VdInscripcionesFresco3y4> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.VdInscripcionesFresco3y4> ToEntities(this IEnumerable<DtoVdInscripcionesFresco3y4Devart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.VdInscripcionesFresco3y4 source, DtoVdInscripcionesFresco3y4Devart target);

        static partial void OnEntityCreating(DtoVdInscripcionesFresco3y4Devart source, BusinessLogic.Entities.VdInscripcionesFresco3y4 target);

    }

}
