//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class AccesoSitiosantanderConverter
    {

        public static DtoAccesoSitiosantanderDevart ToDto(this BusinessLogic.Entities.AccesoSitiosantander source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoAccesoSitiosantanderDevart ToDtoWithRelated(this BusinessLogic.Entities.AccesoSitiosantander source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoAccesoSitiosantanderDevart();

            // Properties
            target.FechaAccesoSitiosantander = source.FechaAccesoSitiosantander;
            target.HoraAccesoSitiosantander = source.HoraAccesoSitiosantander;
            target.CodigoPersona = source.CodigoPersona;
            target.IdSistema = source.IdSistema;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;

            // Navigation Properties
            if (level > 0) {
              target.Persona = source.Persona.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.AccesoSitiosantander ToEntity(this DtoAccesoSitiosantanderDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.AccesoSitiosantander();

            // Properties
            target.FechaAccesoSitiosantander = source.FechaAccesoSitiosantander;
            target.HoraAccesoSitiosantander = source.HoraAccesoSitiosantander;
            target.CodigoPersona = source.CodigoPersona;
            target.IdSistema = source.IdSistema;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoAccesoSitiosantanderDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.AccesoSitiosantander> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoAccesoSitiosantanderDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.AccesoSitiosantander> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.AccesoSitiosantander> ToEntities(this IEnumerable<DtoAccesoSitiosantanderDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.AccesoSitiosantander source, DtoAccesoSitiosantanderDevart target);

        static partial void OnEntityCreating(DtoAccesoSitiosantanderDevart source, BusinessLogic.Entities.AccesoSitiosantander target);

    }

}
