//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class AccionConverter
    {

        public static DtoAccionDevart ToDto(this BusinessLogic.Entities.Accion source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoAccionDevart ToDtoWithRelated(this BusinessLogic.Entities.Accion source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoAccionDevart();

            // Properties
            target.IdAccion = source.IdAccion;
            target.UsuarioLockeadorAccion = source.UsuarioLockeadorAccion;
            target.ProcesoLockeadorAccion = source.ProcesoLockeadorAccion;
            target.IdActividad = source.IdActividad;
            target.CodigoPersona = source.CodigoPersona;
            target.HoraIngreso = source.HoraIngreso;
            target.FechaRealizadoAccion = source.FechaRealizadoAccion;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.IdEstadoAccion = source.IdEstadoAccion;
            target.UsuarioRealizadoAccion = source.UsuarioRealizadoAccion;
            target.IdAccionResultado = source.IdAccionResultado;
            target.ObservacionesAccion = source.ObservacionesAccion;
            target.IdPrueba = source.IdPrueba;

            // Navigation Properties
            if (level > 0) {
              target.Persona = source.Persona.ToDtoWithRelated(level - 1);
              target.Prueba = source.Prueba.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Accion ToEntity(this DtoAccionDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Accion();

            // Properties
            target.IdAccion = source.IdAccion;
            target.UsuarioLockeadorAccion = source.UsuarioLockeadorAccion;
            target.ProcesoLockeadorAccion = source.ProcesoLockeadorAccion;
            target.IdActividad = source.IdActividad;
            target.CodigoPersona = source.CodigoPersona;
            target.HoraIngreso = source.HoraIngreso;
            target.FechaRealizadoAccion = source.FechaRealizadoAccion;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.IdEstadoAccion = source.IdEstadoAccion;
            target.UsuarioRealizadoAccion = source.UsuarioRealizadoAccion;
            target.IdAccionResultado = source.IdAccionResultado;
            target.ObservacionesAccion = source.ObservacionesAccion;
            target.IdPrueba = source.IdPrueba;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoAccionDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Accion> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoAccionDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Accion> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Accion> ToEntities(this IEnumerable<DtoAccionDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Accion source, DtoAccionDevart target);

        static partial void OnEntityCreating(DtoAccionDevart source, BusinessLogic.Entities.Accion target);

    }

}
