//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class DepartamentoConverter
    {

        public static DtoDepartamentoDevart ToDto(this BusinessLogic.Entities.Departamento source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoDepartamentoDevart ToDtoWithRelated(this BusinessLogic.Entities.Departamento source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoDepartamentoDevart();

            // Properties
            target.IdDepartamento = source.IdDepartamento;
            target.NombreDepartamento = source.NombreDepartamento;
            target.NombreExtensoDepartamento = source.NombreExtensoDepartamento;
            target.DescripcionDepartamento = source.DescripcionDepartamento;
            target.FechaCreacionDepartamento = source.FechaCreacionDepartamento;
            target.IdEscuela = source.IdEscuela;
            target.ObservacionesDepartamento = source.ObservacionesDepartamento;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.ClaveDeptoRpg = source.ClaveDeptoRpg;
            target.UsernameResponsable = source.UsernameResponsable;
            target.Ptoid = source.Ptoid;
            target.NombreCoordDepartamento = source.NombreCoordDepartamento;
            target.EmailCoordDepartamento = source.EmailCoordDepartamento;
            target.UsuarioLockeadorDepartamento = source.UsuarioLockeadorDepartamento;
            target.FechaLockeadorDepartamento = source.FechaLockeadorDepartamento;
            target.HoraLockeadorDepartamento = source.HoraLockeadorDepartamento;
            target.ProcesoLockeadorDepartamento = source.ProcesoLockeadorDepartamento;
            target.UsernameSecretario = source.UsernameSecretario;
            target.AliasDepartamento = source.AliasDepartamento;
            target.GeneroDepartamento = source.GeneroDepartamento;
            target.IdEscuelaReal = source.IdEscuelaReal;
            target.UsernameConestDepartamento = source.UsernameConestDepartamento;
            target.UsernameCoogradDepartamento = source.UsernameCoogradDepartamento;
            target.UsernameSecretarioAdjunto = source.UsernameSecretarioAdjunto;
            target.MailBedeliaDepartamento = source.MailBedeliaDepartamento;
            target.MailFirmaOnlineDepartamento = source.MailFirmaOnlineDepartamento;
            target.UsernameCooacadDepartamento = source.UsernameCooacadDepartamento;
            target.IdEscuelaContable = source.IdEscuelaContable;
            target.IpLockeadorDepartamento = source.IpLockeadorDepartamento;
            target.RedSocialDepartamento = source.RedSocialDepartamento;

            // Navigation Properties
            if (level > 0) {
              target.Productos = source.Productos.ToDtosWithRelated(level - 1);
              target.Escuela = source.Escuela.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Departamento ToEntity(this DtoDepartamentoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Departamento();

            // Properties
            target.IdDepartamento = source.IdDepartamento;
            target.NombreDepartamento = source.NombreDepartamento;
            target.NombreExtensoDepartamento = source.NombreExtensoDepartamento;
            target.DescripcionDepartamento = source.DescripcionDepartamento;
            target.FechaCreacionDepartamento = source.FechaCreacionDepartamento;
            target.IdEscuela = source.IdEscuela;
            target.ObservacionesDepartamento = source.ObservacionesDepartamento;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.ClaveDeptoRpg = source.ClaveDeptoRpg;
            target.UsernameResponsable = source.UsernameResponsable;
            target.Ptoid = source.Ptoid;
            target.NombreCoordDepartamento = source.NombreCoordDepartamento;
            target.EmailCoordDepartamento = source.EmailCoordDepartamento;
            target.UsuarioLockeadorDepartamento = source.UsuarioLockeadorDepartamento;
            target.FechaLockeadorDepartamento = source.FechaLockeadorDepartamento;
            target.HoraLockeadorDepartamento = source.HoraLockeadorDepartamento;
            target.ProcesoLockeadorDepartamento = source.ProcesoLockeadorDepartamento;
            target.UsernameSecretario = source.UsernameSecretario;
            target.AliasDepartamento = source.AliasDepartamento;
            target.GeneroDepartamento = source.GeneroDepartamento;
            target.IdEscuelaReal = source.IdEscuelaReal;
            target.UsernameConestDepartamento = source.UsernameConestDepartamento;
            target.UsernameCoogradDepartamento = source.UsernameCoogradDepartamento;
            target.UsernameSecretarioAdjunto = source.UsernameSecretarioAdjunto;
            target.MailBedeliaDepartamento = source.MailBedeliaDepartamento;
            target.MailFirmaOnlineDepartamento = source.MailFirmaOnlineDepartamento;
            target.UsernameCooacadDepartamento = source.UsernameCooacadDepartamento;
            target.IdEscuelaContable = source.IdEscuelaContable;
            target.IpLockeadorDepartamento = source.IpLockeadorDepartamento;
            target.RedSocialDepartamento = source.RedSocialDepartamento;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoDepartamentoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Departamento> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoDepartamentoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Departamento> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Departamento> ToEntities(this IEnumerable<DtoDepartamentoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Departamento source, DtoDepartamentoDevart target);

        static partial void OnEntityCreating(DtoDepartamentoDevart source, BusinessLogic.Entities.Departamento target);

    }

}
