//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class EncuestaIniConverter
    {

        public static DtoEncuestaIniDevart ToDto(this BusinessLogic.Entities.EncuestaIni source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoEncuestaIniDevart ToDtoWithRelated(this BusinessLogic.Entities.EncuestaIni source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoEncuestaIniDevart();

            // Properties
            target.IdEncuestaIni = source.IdEncuestaIni;
            target.CodigoPersona = source.CodigoPersona;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaEncuestaIni = source.FechaEncuestaIni;
            target.DesertorEncuestaIni = source.DesertorEncuestaIni;
            target.ClaveEncuestaIni = source.ClaveEncuestaIni;
            target.AniosInstruccionEncuestaIni = source.AniosInstruccionEncuestaIni;
            target.CodigoInstSecEncuestaIni = source.CodigoInstSecEncuestaIni;
            target.NombreInstSecEncuestaIni = source.NombreInstSecEncuestaIni;
            target.CodigoTitulo = source.CodigoTitulo;
            target.UltimoAnioSextoEncuestaIni = source.UltimoAnioSextoEncuestaIni;
            target.VecesSextoEncuestaIni = source.VecesSextoEncuestaIni;
            target.CantidadPreviasEncuestaIni = source.CantidadPreviasEncuestaIni;
            target.EstudiosTercEncuestaIni = source.EstudiosTercEncuestaIni;
            target.CodigoInstTerEncuestaIni = source.CodigoInstTerEncuestaIni;
            target.NombreInstTerEncuestaIni = source.NombreInstTerEncuestaIni;
            target.CarreraTerEncuestaIni = source.CarreraTerEncuestaIni;
            target.UltAnioTerEncuestaIni = source.UltAnioTerEncuestaIni;
            target.UltAnioCalTerEncuestaIni = source.UltAnioCalTerEncuestaIni;
            target.AbandTerAcadEncuestaIni = source.AbandTerAcadEncuestaIni;
            target.AbandTerOrgEncuestaIni = source.AbandTerOrgEncuestaIni;
            target.AbandTerEconEncuestaIni = source.AbandTerEconEncuestaIni;
            target.AbandTerOtrosEncuestaIni = source.AbandTerOtrosEncuestaIni;
            target.TextoAbandTerEncuestaIni = source.TextoAbandTerEncuestaIni;
            target.ConocimienInglesEncuestaIni = source.ConocimienInglesEncuestaIni;
            target.InstruccionPadreEncuestaIni = source.InstruccionPadreEncuestaIni;
            target.InstruccionMadreEncuestaIni = source.InstruccionMadreEncuestaIni;
            target.DecisionCarreraEncuestaIni = source.DecisionCarreraEncuestaIni;
            target.DecisionUniverEncuestaIni = source.DecisionUniverEncuestaIni;
            target.UtiFeriasEncuestaIni = source.UtiFeriasEncuestaIni;
            target.UtiCharlasEncuestaIni = source.UtiCharlasEncuestaIni;
            target.UtiActividadesEncuestaIni = source.UtiActividadesEncuestaIni;
            target.UtiTalleresEncuestaIni = source.UtiTalleresEncuestaIni;
            target.UtiGuiasEncuestaIni = source.UtiGuiasEncuestaIni;
            target.UtiWebEncuestaIni = source.UtiWebEncuestaIni;
            target.InforOtrasAntesEncuestaIni = source.InforOtrasAntesEncuestaIni;
            target.InforUcudalEncuestaIni = source.InforUcudalEncuestaIni;
            target.InforUrEncuestaIni = source.InforUrEncuestaIni;
            target.InforUmEncuestaIni = source.InforUmEncuestaIni;
            target.InforOtrasEncuestaIni = source.InforOtrasEncuestaIni;
            target.InforUdeEncuestaIni = source.InforUdeEncuestaIni;
            target.ComparPadresEncuestaIni = source.ComparPadresEncuestaIni;
            target.ComparOtrosEncuestaIni = source.ComparOtrosEncuestaIni;
            target.ComparAmigoFamEncuestaIni = source.ComparAmigoFamEncuestaIni;
            target.ComparNadieEncuestaIni = source.ComparNadieEncuestaIni;
            target.ComparAmigoPropEncuestaIni = source.ComparAmigoPropEncuestaIni;
            target.AspectoPrestEncuestaIni = source.AspectoPrestEncuestaIni;
            target.AspectoInfraEncuestaIni = source.AspectoInfraEncuestaIni;
            target.AspectoAcadEncuestaIni = source.AspectoAcadEncuestaIni;
            target.AspectoPrecioEncuestaIni = source.AspectoPrecioEncuestaIni;
            target.AspectoLabEncuestaIni = source.AspectoLabEncuestaIni;
            target.AspectoBecaEncuestaIni = source.AspectoBecaEncuestaIni;
            target.AsististeCharlaEncuestaIni = source.AsististeCharlaEncuestaIni;
            target.OpinionCharlasEncuestaIni = source.OpinionCharlasEncuestaIni;
            target.PlantTodasParEncuestaIni = source.PlantTodasParEncuestaIni;
            target.PlantCadaUnaEncuestaIni = source.PlantCadaUnaEncuestaIni;
            target.PlantPrivParEncuestaIni = source.PlantPrivParEncuestaIni;
            target.PlantCadaDestacEncuestaIni = source.PlantCadaDestacEncuestaIni;
            target.ImpresoEncuestaIni = source.ImpresoEncuestaIni;
            target.InforOtrasLinea1Ini = source.InforOtrasLinea1Ini;
            target.InforOtrasLinea2Ini = source.InforOtrasLinea2Ini;
            target.CodigoInstitucionBac = source.CodigoInstitucionBac;
            target.NuevaversionEncuestaIni = source.NuevaversionEncuestaIni;
            target.UltimoanioSecundariaEncuestaIni = source.UltimoanioSecundariaEncuestaIni;
            target.TieneEducacionSuperiorEncuestaIni = source.TieneEducacionSuperiorEncuestaIni;
            target.NivelDecisionEncuestaIni = source.NivelDecisionEncuestaIni;
            target.AsesoramientoOrtEncuestaIni = source.AsesoramientoOrtEncuestaIni;
            target.ValoracionAsesoramientoOrtEncuestaIni = source.ValoracionAsesoramientoOrtEncuestaIni;
            target.VistaSitioWebOrtEncuestaIni = source.VistaSitioWebOrtEncuestaIni;
            target.ValoracionSitioWebOrtEncuestaIni = source.ValoracionSitioWebOrtEncuestaIni;
            target.VistaInstalacionesOrtEncuestaIni = source.VistaInstalacionesOrtEncuestaIni;
            target.ValoracionInstalacionesOrtEncuestaIni = source.ValoracionInstalacionesOrtEncuestaIni;
            target.PublicidadOrtEncuestaIni = source.PublicidadOrtEncuestaIni;
            target.InstruccionMadreOrtEncuestaIni = source.InstruccionMadreOrtEncuestaIni;
            target.InstruccionPadreOrtEncuestaIni = source.InstruccionPadreOrtEncuestaIni;
            target.TipoBachillerato = source.TipoBachillerato;

            // Navigation Properties
            if (level > 0) {
              target.Empresa = source.Empresa.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.EncuestaIni ToEntity(this DtoEncuestaIniDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.EncuestaIni();

            // Properties
            target.IdEncuestaIni = source.IdEncuestaIni;
            target.CodigoPersona = source.CodigoPersona;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaEncuestaIni = source.FechaEncuestaIni;
            target.DesertorEncuestaIni = source.DesertorEncuestaIni;
            target.ClaveEncuestaIni = source.ClaveEncuestaIni;
            target.AniosInstruccionEncuestaIni = source.AniosInstruccionEncuestaIni;
            target.CodigoInstSecEncuestaIni = source.CodigoInstSecEncuestaIni;
            target.NombreInstSecEncuestaIni = source.NombreInstSecEncuestaIni;
            target.CodigoTitulo = source.CodigoTitulo;
            target.UltimoAnioSextoEncuestaIni = source.UltimoAnioSextoEncuestaIni;
            target.VecesSextoEncuestaIni = source.VecesSextoEncuestaIni;
            target.CantidadPreviasEncuestaIni = source.CantidadPreviasEncuestaIni;
            target.EstudiosTercEncuestaIni = source.EstudiosTercEncuestaIni;
            target.CodigoInstTerEncuestaIni = source.CodigoInstTerEncuestaIni;
            target.NombreInstTerEncuestaIni = source.NombreInstTerEncuestaIni;
            target.CarreraTerEncuestaIni = source.CarreraTerEncuestaIni;
            target.UltAnioTerEncuestaIni = source.UltAnioTerEncuestaIni;
            target.UltAnioCalTerEncuestaIni = source.UltAnioCalTerEncuestaIni;
            target.AbandTerAcadEncuestaIni = source.AbandTerAcadEncuestaIni;
            target.AbandTerOrgEncuestaIni = source.AbandTerOrgEncuestaIni;
            target.AbandTerEconEncuestaIni = source.AbandTerEconEncuestaIni;
            target.AbandTerOtrosEncuestaIni = source.AbandTerOtrosEncuestaIni;
            target.TextoAbandTerEncuestaIni = source.TextoAbandTerEncuestaIni;
            target.ConocimienInglesEncuestaIni = source.ConocimienInglesEncuestaIni;
            target.InstruccionPadreEncuestaIni = source.InstruccionPadreEncuestaIni;
            target.InstruccionMadreEncuestaIni = source.InstruccionMadreEncuestaIni;
            target.DecisionCarreraEncuestaIni = source.DecisionCarreraEncuestaIni;
            target.DecisionUniverEncuestaIni = source.DecisionUniverEncuestaIni;
            target.UtiFeriasEncuestaIni = source.UtiFeriasEncuestaIni;
            target.UtiCharlasEncuestaIni = source.UtiCharlasEncuestaIni;
            target.UtiActividadesEncuestaIni = source.UtiActividadesEncuestaIni;
            target.UtiTalleresEncuestaIni = source.UtiTalleresEncuestaIni;
            target.UtiGuiasEncuestaIni = source.UtiGuiasEncuestaIni;
            target.UtiWebEncuestaIni = source.UtiWebEncuestaIni;
            target.InforOtrasAntesEncuestaIni = source.InforOtrasAntesEncuestaIni;
            target.InforUcudalEncuestaIni = source.InforUcudalEncuestaIni;
            target.InforUrEncuestaIni = source.InforUrEncuestaIni;
            target.InforUmEncuestaIni = source.InforUmEncuestaIni;
            target.InforOtrasEncuestaIni = source.InforOtrasEncuestaIni;
            target.InforUdeEncuestaIni = source.InforUdeEncuestaIni;
            target.ComparPadresEncuestaIni = source.ComparPadresEncuestaIni;
            target.ComparOtrosEncuestaIni = source.ComparOtrosEncuestaIni;
            target.ComparAmigoFamEncuestaIni = source.ComparAmigoFamEncuestaIni;
            target.ComparNadieEncuestaIni = source.ComparNadieEncuestaIni;
            target.ComparAmigoPropEncuestaIni = source.ComparAmigoPropEncuestaIni;
            target.AspectoPrestEncuestaIni = source.AspectoPrestEncuestaIni;
            target.AspectoInfraEncuestaIni = source.AspectoInfraEncuestaIni;
            target.AspectoAcadEncuestaIni = source.AspectoAcadEncuestaIni;
            target.AspectoPrecioEncuestaIni = source.AspectoPrecioEncuestaIni;
            target.AspectoLabEncuestaIni = source.AspectoLabEncuestaIni;
            target.AspectoBecaEncuestaIni = source.AspectoBecaEncuestaIni;
            target.AsististeCharlaEncuestaIni = source.AsististeCharlaEncuestaIni;
            target.OpinionCharlasEncuestaIni = source.OpinionCharlasEncuestaIni;
            target.PlantTodasParEncuestaIni = source.PlantTodasParEncuestaIni;
            target.PlantCadaUnaEncuestaIni = source.PlantCadaUnaEncuestaIni;
            target.PlantPrivParEncuestaIni = source.PlantPrivParEncuestaIni;
            target.PlantCadaDestacEncuestaIni = source.PlantCadaDestacEncuestaIni;
            target.ImpresoEncuestaIni = source.ImpresoEncuestaIni;
            target.InforOtrasLinea1Ini = source.InforOtrasLinea1Ini;
            target.InforOtrasLinea2Ini = source.InforOtrasLinea2Ini;
            target.CodigoInstitucionBac = source.CodigoInstitucionBac;
            target.NuevaversionEncuestaIni = source.NuevaversionEncuestaIni;
            target.UltimoanioSecundariaEncuestaIni = source.UltimoanioSecundariaEncuestaIni;
            target.TieneEducacionSuperiorEncuestaIni = source.TieneEducacionSuperiorEncuestaIni;
            target.NivelDecisionEncuestaIni = source.NivelDecisionEncuestaIni;
            target.AsesoramientoOrtEncuestaIni = source.AsesoramientoOrtEncuestaIni;
            target.ValoracionAsesoramientoOrtEncuestaIni = source.ValoracionAsesoramientoOrtEncuestaIni;
            target.VistaSitioWebOrtEncuestaIni = source.VistaSitioWebOrtEncuestaIni;
            target.ValoracionSitioWebOrtEncuestaIni = source.ValoracionSitioWebOrtEncuestaIni;
            target.VistaInstalacionesOrtEncuestaIni = source.VistaInstalacionesOrtEncuestaIni;
            target.ValoracionInstalacionesOrtEncuestaIni = source.ValoracionInstalacionesOrtEncuestaIni;
            target.PublicidadOrtEncuestaIni = source.PublicidadOrtEncuestaIni;
            target.InstruccionMadreOrtEncuestaIni = source.InstruccionMadreOrtEncuestaIni;
            target.InstruccionPadreOrtEncuestaIni = source.InstruccionPadreOrtEncuestaIni;
            target.TipoBachillerato = source.TipoBachillerato;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoEncuestaIniDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.EncuestaIni> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoEncuestaIniDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.EncuestaIni> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.EncuestaIni> ToEntities(this IEnumerable<DtoEncuestaIniDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.EncuestaIni source, DtoEncuestaIniDevart target);

        static partial void OnEntityCreating(DtoEncuestaIniDevart source, BusinessLogic.Entities.EncuestaIni target);

    }

}
