//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class EscuelaConverter
    {

        public static DtoEscuelaDevart ToDto(this BusinessLogic.Entities.Escuela source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoEscuelaDevart ToDtoWithRelated(this BusinessLogic.Entities.Escuela source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoEscuelaDevart();

            // Properties
            target.IdEscuela = source.IdEscuela;
            target.NombreEscuela = source.NombreEscuela;
            target.NombreExtensoEscuela = source.NombreExtensoEscuela;
            target.ObservacionesEscuela = source.ObservacionesEscuela;
            target.FechaCreacionEscuela = source.FechaCreacionEscuela;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.DescripcionEscuela = source.DescripcionEscuela;
            target.UsernameResponsable = source.UsernameResponsable;
            target.OrdenListadoEscuela = source.OrdenListadoEscuela;
            target.AliasEscuela = source.AliasEscuela;
            target.IdCentroGastosEscuela = source.IdCentroGastosEscuela;
            target.GeneroEscuela = source.GeneroEscuela;
            target.ParawebEscuela = source.ParawebEscuela;
            target.UsernameVicedecanoEscuela = source.UsernameVicedecanoEscuela;
            target.EsFacultadEscuela = source.EsFacultadEscuela;
            target.UsernameSecretarioEscuela = source.UsernameSecretarioEscuela;

            // Navigation Properties
            if (level > 0) {
              target.Departamentos = source.Departamentos.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Escuela ToEntity(this DtoEscuelaDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Escuela();

            // Properties
            target.IdEscuela = source.IdEscuela;
            target.NombreEscuela = source.NombreEscuela;
            target.NombreExtensoEscuela = source.NombreExtensoEscuela;
            target.ObservacionesEscuela = source.ObservacionesEscuela;
            target.FechaCreacionEscuela = source.FechaCreacionEscuela;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.DescripcionEscuela = source.DescripcionEscuela;
            target.UsernameResponsable = source.UsernameResponsable;
            target.OrdenListadoEscuela = source.OrdenListadoEscuela;
            target.AliasEscuela = source.AliasEscuela;
            target.IdCentroGastosEscuela = source.IdCentroGastosEscuela;
            target.GeneroEscuela = source.GeneroEscuela;
            target.ParawebEscuela = source.ParawebEscuela;
            target.UsernameVicedecanoEscuela = source.UsernameVicedecanoEscuela;
            target.EsFacultadEscuela = source.EsFacultadEscuela;
            target.UsernameSecretarioEscuela = source.UsernameSecretarioEscuela;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoEscuelaDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Escuela> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoEscuelaDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Escuela> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Escuela> ToEntities(this IEnumerable<DtoEscuelaDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Escuela source, DtoEscuelaDevart target);

        static partial void OnEntityCreating(DtoEscuelaDevart source, BusinessLogic.Entities.Escuela target);

    }

}
