//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/WebApiAdmisiones.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

#nullable enable annotations
#nullable disable warnings

using System.Collections.Generic;
using System.Linq;

namespace AppLogic.DevartDTOs
{

    public static partial class EstadoConverter
    {

        public static DtoEstadoDevart ToDto(this BusinessLogic.Entities.Estado source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoEstadoDevart ToDtoWithRelated(this BusinessLogic.Entities.Estado source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoEstadoDevart();

            // Properties
            target.CodigoPais = source.CodigoPais;
            target.CodigoEstado = source.CodigoEstado;
            target.Nombre = source.Nombre;
            target.DgiEstado = source.DgiEstado;

            // Navigation Properties
            if (level > 0) {
              target.Pai = source.Pai.ToDtoWithRelated(level - 1);
              target.Ciudad = source.Ciudad.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Estado ToEntity(this DtoEstadoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Estado();

            // Properties
            target.CodigoPais = source.CodigoPais;
            target.CodigoEstado = source.CodigoEstado;
            target.Nombre = source.Nombre;
            target.DgiEstado = source.DgiEstado;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoEstadoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Estado> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoEstadoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Estado> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Estado> ToEntities(this IEnumerable<DtoEstadoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Estado source, DtoEstadoDevart target);

        static partial void OnEntityCreating(DtoEstadoDevart source, BusinessLogic.Entities.Estado target);

    }

}
