//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class IntegranteNfDjConverter
    {

        public static DtoIntegranteNfDjDevart ToDto(this BusinessLogic.Entities.IntegranteNfDj source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoIntegranteNfDjDevart ToDtoWithRelated(this BusinessLogic.Entities.IntegranteNfDj source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoIntegranteNfDjDevart();

            // Properties
            target.IdIntegranteNfDj = source.IdIntegranteNfDj;
            target.IdTipoParentesco = source.IdTipoParentesco;
            target.NombreIntegranteNfDj = source.NombreIntegranteNfDj;
            target.EdadIntegranteNfDj = source.EdadIntegranteNfDj;
            target.ActividadIntegranteNfDj = source.ActividadIntegranteNfDj;
            target.DetalleOtroParentesco = source.DetalleOtroParentesco;
            target.IdDeclaracionjuradaWeb = source.IdDeclaracionjuradaWeb;

            // Navigation Properties
            if (level > 0) {
              target.DeclaracionJuradaWeb = source.DeclaracionJuradaWeb.ToDtoWithRelated(level - 1);
              target.TipoParentesco = source.TipoParentesco.ToDtoWithRelated(level - 1);
              target.IngresoMensualNfDjs = source.IngresoMensualNfDjs.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.IntegranteNfDj ToEntity(this DtoIntegranteNfDjDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.IntegranteNfDj();

            // Properties
            target.IdIntegranteNfDj = source.IdIntegranteNfDj;
            target.IdTipoParentesco = source.IdTipoParentesco;
            target.NombreIntegranteNfDj = source.NombreIntegranteNfDj;
            target.EdadIntegranteNfDj = source.EdadIntegranteNfDj;
            target.ActividadIntegranteNfDj = source.ActividadIntegranteNfDj;
            target.DetalleOtroParentesco = source.DetalleOtroParentesco;
            target.IdDeclaracionjuradaWeb = source.IdDeclaracionjuradaWeb;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoIntegranteNfDjDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.IntegranteNfDj> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoIntegranteNfDjDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.IntegranteNfDj> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.IntegranteNfDj> ToEntities(this IEnumerable<DtoIntegranteNfDjDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.IntegranteNfDj source, DtoIntegranteNfDjDevart target);

        static partial void OnEntityCreating(DtoIntegranteNfDjDevart source, BusinessLogic.Entities.IntegranteNfDj target);

    }

}
