//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class InteresProductoOfertaConverter
    {

        public static DtoInteresProductoOfertaDevart ToDto(this BusinessLogic.Entities.InteresProductoOferta source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoInteresProductoOfertaDevart ToDtoWithRelated(this BusinessLogic.Entities.InteresProductoOferta source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoInteresProductoOfertaDevart();

            // Properties
            target.IdInteres = source.IdInteres;
            target.IdProducto = source.IdProducto;
            target.IdOferta = source.IdOferta;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.InteresProductoOferta ToEntity(this DtoInteresProductoOfertaDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.InteresProductoOferta();

            // Properties
            target.IdInteres = source.IdInteres;
            target.IdProducto = source.IdProducto;
            target.IdOferta = source.IdOferta;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoInteresProductoOfertaDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.InteresProductoOferta> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoInteresProductoOfertaDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.InteresProductoOferta> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.InteresProductoOferta> ToEntities(this IEnumerable<DtoInteresProductoOfertaDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.InteresProductoOferta source, DtoInteresProductoOfertaDevart target);

        static partial void OnEntityCreating(DtoInteresProductoOfertaDevart source, BusinessLogic.Entities.InteresProductoOferta target);

    }

}
