//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class OfertaCreditoConverter
    {

        public static DtoOfertaCreditoDevart ToDto(this BusinessLogic.Entities.OfertaCredito source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoOfertaCreditoDevart ToDtoWithRelated(this BusinessLogic.Entities.OfertaCredito source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoOfertaCreditoDevart();

            // Properties
            target.IdOfertaCredito = source.IdOfertaCredito;
            target.IdOferta = source.IdOferta;
            target.PorcentValorOfertaCredito = source.PorcentValorOfertaCredito;
            target.UnicaInscrOfertaCredito = source.UnicaInscrOfertaCredito;
            target.TipoOfertaCredito = source.TipoOfertaCredito;
            target.NombreOfertaCredito = source.NombreOfertaCredito;
            target.IdCreditoPaquete = source.IdCreditoPaquete;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.GenericOfertaCredito = source.GenericOfertaCredito;
            target.CupoOfertaCredito = source.CupoOfertaCredito;
            target.CantInscriptosOfertaCredito = source.CantInscriptosOfertaCredito;
            target.PorcentVal6m6OfertaCredito = source.PorcentVal6m6OfertaCredito;

            // Navigation Properties
            if (level > 0) {
              target.Oferta = source.Oferta.ToDtoWithRelated(level - 1);
              target.OfertaCreditoMaterias = source.OfertaCreditoMaterias.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.OfertaCredito ToEntity(this DtoOfertaCreditoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.OfertaCredito();

            // Properties
            target.IdOfertaCredito = source.IdOfertaCredito;
            target.IdOferta = source.IdOferta;
            target.PorcentValorOfertaCredito = source.PorcentValorOfertaCredito;
            target.UnicaInscrOfertaCredito = source.UnicaInscrOfertaCredito;
            target.TipoOfertaCredito = source.TipoOfertaCredito;
            target.NombreOfertaCredito = source.NombreOfertaCredito;
            target.IdCreditoPaquete = source.IdCreditoPaquete;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.GenericOfertaCredito = source.GenericOfertaCredito;
            target.CupoOfertaCredito = source.CupoOfertaCredito;
            target.CantInscriptosOfertaCredito = source.CantInscriptosOfertaCredito;
            target.PorcentVal6m6OfertaCredito = source.PorcentVal6m6OfertaCredito;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoOfertaCreditoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.OfertaCredito> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoOfertaCreditoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.OfertaCredito> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.OfertaCredito> ToEntities(this IEnumerable<DtoOfertaCreditoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.OfertaCredito source, DtoOfertaCreditoDevart target);

        static partial void OnEntityCreating(DtoOfertaCreditoDevart source, BusinessLogic.Entities.OfertaCredito target);

    }

}
