//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class OfertaConverter
    {

        public static DtoOfertaDevart ToDto(this BusinessLogic.Entities.Oferta source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoOfertaDevart ToDtoWithRelated(this BusinessLogic.Entities.Oferta source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoOfertaDevart();

            // Properties
            target.IdOferta = source.IdOferta;
            target.IdSupraoferta = source.IdSupraoferta;
            target.NombreOferta = source.NombreOferta;
            target.IdTurno = source.IdTurno;
            target.IdLocalidad = source.IdLocalidad;
            target.CupoOferta = source.CupoOferta;
            target.InscripcionesAbiertasOferta = source.InscripcionesAbiertasOferta;
            target.PorcentPrecioPaqueteOferta = source.PorcentPrecioPaqueteOferta;
            target.AceptaCondicionalesOferta = source.AceptaCondicionalesOferta;
            target.HorarioReferenciaOferta = source.HorarioReferenciaOferta;
            target.ObservacionesOferta = source.ObservacionesOferta;
            target.MinimoCreditosOferta = source.MinimoCreditosOferta;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.CantidadInscriptosOferta = source.CantidadInscriptosOferta;
            target.NombreCortoOferta = source.NombreCortoOferta;
            target.TurnoRpg = source.TurnoRpg;
            target.DepRpg = source.DepRpg;
            target.CarrRpg = source.CarrRpg;
            target.FechaComRpg = source.FechaComRpg;
            target.SemestreRpg = source.SemestreRpg;
            target.GrupoRpg = source.GrupoRpg;
            target.FechaNormal = source.FechaNormal;
            target.CupoRestringidoOferta = source.CupoRestringidoOferta;

            // Navigation Properties
            if (level > 0) {
              target.Supraoferta = source.Supraoferta.ToDtoWithRelated(level - 1);
              target.Inscriptos = source.Inscriptos.ToDtosWithRelated(level - 1);
              target.Localidad = source.Localidad.ToDtoWithRelated(level - 1);
              target.Turno = source.Turno.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Oferta ToEntity(this DtoOfertaDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Oferta();

            // Properties
            target.IdOferta = source.IdOferta;
            target.IdSupraoferta = source.IdSupraoferta;
            target.NombreOferta = source.NombreOferta;
            target.IdTurno = source.IdTurno;
            target.IdLocalidad = source.IdLocalidad;
            target.CupoOferta = source.CupoOferta;
            target.InscripcionesAbiertasOferta = source.InscripcionesAbiertasOferta;
            target.PorcentPrecioPaqueteOferta = source.PorcentPrecioPaqueteOferta;
            target.AceptaCondicionalesOferta = source.AceptaCondicionalesOferta;
            target.HorarioReferenciaOferta = source.HorarioReferenciaOferta;
            target.ObservacionesOferta = source.ObservacionesOferta;
            target.MinimoCreditosOferta = source.MinimoCreditosOferta;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.CantidadInscriptosOferta = source.CantidadInscriptosOferta;
            target.NombreCortoOferta = source.NombreCortoOferta;
            target.TurnoRpg = source.TurnoRpg;
            target.DepRpg = source.DepRpg;
            target.CarrRpg = source.CarrRpg;
            target.FechaComRpg = source.FechaComRpg;
            target.SemestreRpg = source.SemestreRpg;
            target.GrupoRpg = source.GrupoRpg;
            target.FechaNormal = source.FechaNormal;
            target.CupoRestringidoOferta = source.CupoRestringidoOferta;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoOfertaDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Oferta> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoOfertaDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Oferta> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Oferta> ToEntities(this IEnumerable<DtoOfertaDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Oferta source, DtoOfertaDevart target);

        static partial void OnEntityCreating(DtoOfertaDevart source, BusinessLogic.Entities.Oferta target);

    }

}
