//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PaisConverter
    {

        public static DtoPaisDevart ToDto(this BusinessLogic.Entities.Pais source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPaisDevart ToDtoWithRelated(this BusinessLogic.Entities.Pais source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPaisDevart();

            // Properties
            target.CodigoPais = source.CodigoPais;
            target.Nombre = source.Nombre;
            target.DgiPais = source.DgiPais;

            // Navigation Properties
            if (level > 0) {
              target.Estado = source.Estado.ToDtosWithRelated(level - 1);
              target.Personas = source.Personas.ToDtosWithRelated(level - 1);
              target.SolicitudAltas = source.SolicitudAltas.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Pais ToEntity(this DtoPaisDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Pais();

            // Properties
            target.CodigoPais = source.CodigoPais;
            target.Nombre = source.Nombre;
            target.DgiPais = source.DgiPais;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPaisDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Pais> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPaisDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Pais> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Pais> ToEntities(this IEnumerable<DtoPaisDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Pais source, DtoPaisDevart target);

        static partial void OnEntityCreating(DtoPaisDevart source, BusinessLogic.Entities.Pais target);

    }

}
