//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PaqueteConverter
    {

        public static DtoPaqueteDevart ToDto(this BusinessLogic.Entities.Paquete source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPaqueteDevart ToDtoWithRelated(this BusinessLogic.Entities.Paquete source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPaqueteDevart();

            // Properties
            target.IdPaquete = source.IdPaquete;
            target.NombrePaquete = source.NombrePaquete;
            target.IdProducto = source.IdProducto;
            target.IdTitulo = source.IdTitulo;
            target.SemestrePaquete = source.SemestrePaquete;
            target.GeneraPlanAnclaPaquete = source.GeneraPlanAnclaPaquete;
            target.MinimoCreditosPaquete = source.MinimoCreditosPaquete;
            target.ObservacionesPaquete = source.ObservacionesPaquete;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.CarreraRpg = source.CarreraRpg;
            target.IdTipoPaqCom = source.IdTipoPaqCom;
            target.VisibleInternetPaquete = source.VisibleInternetPaquete;
            target.AdmiteDescuentosPaquete = source.AdmiteDescuentosPaquete;
            target.EstadoPaquete = source.EstadoPaquete;
            target.CantCuotasAjustePaquete = source.CantCuotasAjustePaquete;

            // Navigation Properties
            if (level > 0) {
              target.Producto = source.Producto.ToDtoWithRelated(level - 1);
              target.Supraofertas = source.Supraofertas.ToDtosWithRelated(level - 1);
              target.TituloOrt = source.TituloOrt.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Paquete ToEntity(this DtoPaqueteDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Paquete();

            // Properties
            target.IdPaquete = source.IdPaquete;
            target.NombrePaquete = source.NombrePaquete;
            target.IdProducto = source.IdProducto;
            target.IdTitulo = source.IdTitulo;
            target.SemestrePaquete = source.SemestrePaquete;
            target.GeneraPlanAnclaPaquete = source.GeneraPlanAnclaPaquete;
            target.MinimoCreditosPaquete = source.MinimoCreditosPaquete;
            target.ObservacionesPaquete = source.ObservacionesPaquete;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.CarreraRpg = source.CarreraRpg;
            target.IdTipoPaqCom = source.IdTipoPaqCom;
            target.VisibleInternetPaquete = source.VisibleInternetPaquete;
            target.AdmiteDescuentosPaquete = source.AdmiteDescuentosPaquete;
            target.EstadoPaquete = source.EstadoPaquete;
            target.CantCuotasAjustePaquete = source.CantCuotasAjustePaquete;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPaqueteDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Paquete> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPaqueteDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Paquete> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Paquete> ToEntities(this IEnumerable<DtoPaqueteDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Paquete source, DtoPaqueteDevart target);

        static partial void OnEntityCreating(DtoPaqueteDevart source, BusinessLogic.Entities.Paquete target);

    }

}
