//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PersonaConverter
    {

        public static DtoPersonaDevart ToDto(this BusinessLogic.Entities.Persona source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPersonaDevart ToDtoWithRelated(this BusinessLogic.Entities.Persona source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPersonaDevart();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.PrimerApellido = source.PrimerApellido;
            target.SegundoApellido = source.SegundoApellido;
            target.PrimerNombre = source.PrimerNombre;
            target.SegundoNombre = source.SegundoNombre;
            target.Direccion = source.Direccion;
            target.CodigoPais = source.CodigoPais;
            target.CodigoEstado = source.CodigoEstado;
            target.CodigoCiudad = source.CodigoCiudad;
            target.CodigoPostal = source.CodigoPostal;
            target.CodigoFidelidadDireccion = source.CodigoFidelidadDireccion;
            target.Telefono1 = source.Telefono1;
            target.Telefono2 = source.Telefono2;
            target.Email = source.Email;
            target.FechaNacimiento = source.FechaNacimiento;
            target.Sexo = source.Sexo;
            target.NumeroAlumnoViejo = source.NumeroAlumnoViejo;
            target.CodigoRecibeBoletin = source.CodigoRecibeBoletin;
            target.UsuarioUltimaActualizacion = source.UsuarioUltimaActualizacion;
            target.FechaUltimaActualizacion = source.FechaUltimaActualizacion;
            target.HoraUltimaActualizacion = source.HoraUltimaActualizacion;
            target.Documento = source.Documento;
            target.FechaFidelidadDireccion = source.FechaFidelidadDireccion;
            target.TipoDocumento = source.TipoDocumento;
            target.CodigoVigencia = source.CodigoVigencia;
            target.CodigoFuenteDatos = source.CodigoFuenteDatos;
            target.Observaciones = source.Observaciones;
            target.PrimerNombreMay = source.PrimerNombreMay;
            target.SegundoNombreMay = source.SegundoNombreMay;
            target.PrimerApellidoMay = source.PrimerApellidoMay;
            target.SegundoApellidoMay = source.SegundoApellidoMay;
            target.IdFuncionario = source.IdFuncionario;
            target.CredencialCivica = source.CredencialCivica;
            target.CodigoPaisNacimiento = source.CodigoPaisNacimiento;
            target.EstadoCivil = source.EstadoCivil;
            target.EntreCalles = source.EntreCalles;
            target.Barrio = source.Barrio;
            target.SeccionalPolicial = source.SeccionalPolicial;
            target.CodigoBachillerato = source.CodigoBachillerato;
            target.FechaIngresoOrt = source.FechaIngresoOrt;
            target.FechaExclusividad = source.FechaExclusividad;
            target.Contratable = source.Contratable;
            target.FechaContratable = source.FechaContratable;
            target.Empresa = source.Empresa;
            target.Afap = source.Afap;
            target.Bancomat = source.Bancomat;
            target.TipoCuenta = source.TipoCuenta;
            target.NroCuenta = source.NroCuenta;
            target.FechaActualizacionLegajo = source.FechaActualizacionLegajo;
            target.FechaBachillerato = source.FechaBachillerato;
            target.CodigoInstitucionBac = source.CodigoInstitucionBac;
            target.IdNivelEducacion = source.IdNivelEducacion;
            target.FechaUltModifPassword = source.FechaUltModifPassword;
            target.UsuarioUltModifPassword = source.UsuarioUltModifPassword;
            target.FechaExpiracionPassword = source.FechaExpiracionPassword;
            target.PasswordOld = source.PasswordOld;
            target.NumeroAlumnoAnterior = source.NumeroAlumnoAnterior;
            target.UltimaconexionwebPersona = source.UltimaconexionwebPersona;
            target.TelefonoLaboralPersona = source.TelefonoLaboralPersona;
            target.PercibeJubilacionPersona = source.PercibeJubilacionPersona;
            target.CajaJubilacionPersona = source.CajaJubilacionPersona;
            target.NacionalidadPersona = source.NacionalidadPersona;
            target.IdBanco = source.IdBanco;
            target.SerieCredencialPersona = source.SerieCredencialPersona;
            target.NumeroCredencialPersona = source.NumeroCredencialPersona;
            target.FuncionarioActivoPersona = source.FuncionarioActivoPersona;
            target.FechaActivoPersona = source.FechaActivoPersona;
            target.LpdPersona = source.LpdPersona;
            target.PagaOrtBancomatPersona = source.PagaOrtBancomatPersona;
            target.IdSeguroSaludPersona = source.IdSeguroSaludPersona;
            target.BancoCuentaPersona = source.BancoCuentaPersona;
            target.FaxEmpresa = source.FaxEmpresa;
            target.AsistenciaObtencionEmpleo = source.AsistenciaObtencionEmpleo;
            target.ActualizacionOk = source.ActualizacionOk;
            target.RecibeCartasPersona = source.RecibeCartasPersona;
            target.RecibeEmailsPersona = source.RecibeEmailsPersona;
            target.UsuarioConfDatosPersona = source.UsuarioConfDatosPersona;
            target.FechaConfDatosPersona = source.FechaConfDatosPersona;
            target.HoraConfDatosPersona = source.HoraConfDatosPersona;
            target.BuscaTrabajoPersona = source.BuscaTrabajoPersona;
            target.Contacto1Persona = source.Contacto1Persona;
            target.Contacto2Persona = source.Contacto2Persona;
            target.IdSucursal = source.IdSucursal;
            target.CodigoSucursal = source.CodigoSucursal;
            target.CreoEmpresaPersona = source.CreoEmpresaPersona;
            target.RetiraReciboPersona = source.RetiraReciboPersona;
            target.TopeAfapPersona = source.TopeAfapPersona;
            target.TipoFechaBachillerato = source.TipoFechaBachillerato;
            target.FechaBajaOrt = source.FechaBajaOrt;
            target.TicketDocentePersona = source.TicketDocentePersona;
            target.TicketAdmPersona = source.TicketAdmPersona;
            target.RecibeNoticiasDeportivas = source.RecibeNoticiasDeportivas;
            target.TipoRetencionPersona = source.TipoRetencionPersona;
            target.ValorRetencionPersona = source.ValorRetencionPersona;
            target.AlumnoExtranjeroPersona = source.AlumnoExtranjeroPersona;
            target.SancionGravePersona = source.SancionGravePersona;
            target.ObservacionesSancionPersona = source.ObservacionesSancionPersona;
            target.FechaSancionPersona = source.FechaSancionPersona;
            target.EntrevistadoCatalogoPersona = source.EntrevistadoCatalogoPersona;
            target.FechaIngresoOrtBps = source.FechaIngresoOrtBps;
            target.FechaVtoDocumentoPersona = source.FechaVtoDocumentoPersona;
            target.ExclusividadIndefPersona = source.ExclusividadIndefPersona;
            target.RecibeResultMailPersona = source.RecibeResultMailPersona;
            target.IdFuncionarioViejo = source.IdFuncionarioViejo;
            target.ExtranjeroFuncionarioPersona = source.ExtranjeroFuncionarioPersona;
            target.TipoPersona = source.TipoPersona;
            target.GraduadoEstrellaPersona = source.GraduadoEstrellaPersona;
            target.TrabajaExteriorPersona = source.TrabajaExteriorPersona;
            target.ComentarioCargoPersona = source.ComentarioCargoPersona;
            target.IdEmpleadorPersona = source.IdEmpleadorPersona;
            target.FechaclasiflaboralPersona = source.FechaclasiflaboralPersona;
            target.IdTipoOcupacionActual = source.IdTipoOcupacionActual;
            target.FueraProfesionPersona = source.FueraProfesionPersona;
            target.FechaInduccionPersona = source.FechaInduccionPersona;
            target.ObservaInduccionPersona = source.ObservaInduccionPersona;
            target.TituloGradoPersona = source.TituloGradoPersona;
            target.UsoexclusivodbaPersona = source.UsoexclusivodbaPersona;
            target.IdBuscaTrabajo = source.IdBuscaTrabajo;
            target.CorrectorPersona = source.CorrectorPersona;
            target.FechaCorrectorPersona = source.FechaCorrectorPersona;
            target.IntentosCambioPassword = source.IntentosCambioPassword;
            target.OtrasactividadesCargoPersona = source.OtrasactividadesCargoPersona;
            target.TrabajaActualmente = source.TrabajaActualmente;
            target.ComputoEspecialPersona = source.ComputoEspecialPersona;
            target.DatosWebPersona = source.DatosWebPersona;
            target.MarcaVerificadoPersona = source.MarcaVerificadoPersona;
            target.FechaVerificadoPersona = source.FechaVerificadoPersona;
            target.FechaVerifDocPersona = source.FechaVerifDocPersona;
            target.EstadoCuidantePersona = source.EstadoCuidantePersona;
            target.VigenciaCuidantePersona = source.VigenciaCuidantePersona;
            target.ObservacionesCuidantePersona = source.ObservacionesCuidantePersona;
            target.AplicaPrimerTopeBpsPersona = source.AplicaPrimerTopeBpsPersona;
            target.IdCausalEgresoPersona = source.IdCausalEgresoPersona;
            target.Fechaexoneraexclusivapersona = source.Fechaexoneraexclusivapersona;
            target.Observacexoneraexclusivpersona = source.Observacexoneraexclusivpersona;
            target.CodadmPersona = source.CodadmPersona;
            target.CodadmObservacionPersona = source.CodadmObservacionPersona;
            target.RegimenFluctuantePersona = source.RegimenFluctuantePersona;
            target.OpcionAdelantosPersona = source.OpcionAdelantosPersona;
            target.ModoTicketsPersona = source.ModoTicketsPersona;
            target.TipoLegajoPersona = source.TipoLegajoPersona;
            target.FechaInformeRegimenPersona = source.FechaInformeRegimenPersona;
            target.UsuarioInformeRegimenPer = source.UsuarioInformeRegimenPer;
            target.ObsInformeRegimenPersona = source.ObsInformeRegimenPersona;
            target.HabilitadoAdelantoPersona = source.HabilitadoAdelantoPersona;
            target.FechaConfOpcionAdelanto = source.FechaConfOpcionAdelanto;
            target.FechaFirmaDocumentoRegimen = source.FechaFirmaDocumentoRegimen;
            target.PartidasAdelantosPersona = source.PartidasAdelantosPersona;
            target.TarjetaEmitidaPersona = source.TarjetaEmitidaPersona;
            target.FechaemisionTarjetaPersona = source.FechaemisionTarjetaPersona;
            target.FechasolicitudTarjetaPersona = source.FechasolicitudTarjetaPersona;
            target.FechaVtoCarneSalud = source.FechaVtoCarneSalud;
            target.RecepcionDocumentoRegimen = source.RecepcionDocumentoRegimen;
            target.InscribiblePersona = source.InscribiblePersona;
            target.ObservacionesInscribiblePer = source.ObservacionesInscribiblePer;
            target.FechaEgresoLiqDoc = source.FechaEgresoLiqDoc;
            target.VinculoFuncionalPersona = source.VinculoFuncionalPersona;
            target.PercibeJubilacionafapPersona = source.PercibeJubilacionafapPersona;
            target.UsuarioModifFdp = source.UsuarioModifFdp;
            target.IdCajaJubilacionPersona = source.IdCajaJubilacionPersona;
            target.JubiladoPersona = source.JubiladoPersona;
            target.CodigoAcumulacionLaboral = source.CodigoAcumulacionLaboral;
            target.ObservacionesNocontratablePe = source.ObservacionesNocontratablePe;
            target.FechaConfSnisPersona = source.FechaConfSnisPersona;
            target.FechaConf3100Persona = source.FechaConf3100Persona;
            target.LinkedinPersona = source.LinkedinPersona;
            target.FechaJubiladoAfapPersona = source.FechaJubiladoAfapPersona;
            target.FechaJubiladoBpsPersona = source.FechaJubiladoBpsPersona;
            target.EmailEmpresa = source.EmailEmpresa;
            target.TipoJornada = source.TipoJornada;
            target.IdCaracteristicaPaisTel1 = source.IdCaracteristicaPaisTel1;
            target.IdCaracteristicaPaisTel2 = source.IdCaracteristicaPaisTel2;
            target.EmailOrtPersona = source.EmailOrtPersona;

            // Navigation Properties
            if (level > 0) {
              target.Pai = source.Pai.ToDtoWithRelated(level - 1);
              target.Ciudad = source.Ciudad.ToDtoWithRelated(level - 1);
              target.Empresa1 = source.Empresa1.ToDtoWithRelated(level - 1);
              target.Imagens = source.Imagens.ToDtosWithRelated(level - 1);
              target.Titulo = source.Titulo.ToDtoWithRelated(level - 1);
              target.SolicitudAltas = source.SolicitudAltas.ToDtosWithRelated(level - 1);
              target.Intere = source.Intere.ToDtoWithRelated(level - 1);
              target.Inscriptos = source.Inscriptos.ToDtosWithRelated(level - 1);
              target.InstanciaWorkflows = source.InstanciaWorkflows.ToDtosWithRelated(level - 1);
              target.AccesoSitiosantanders = source.AccesoSitiosantanders.ToDtosWithRelated(level - 1);
              target.BachilleratoPersona = source.BachilleratoPersona.ToDtoWithRelated(level - 1);
              target.Accions = source.Accions.ToDtosWithRelated(level - 1);
              target.DeclaracionJuradaWebs = source.DeclaracionJuradaWebs.ToDtosWithRelated(level - 1);
              target.InscriptoPruebas = source.InscriptoPruebas.ToDtosWithRelated(level - 1);
              target.AceptacionReglamentoEsts = source.AceptacionReglamentoEsts.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Persona ToEntity(this DtoPersonaDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Persona();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.PrimerApellido = source.PrimerApellido;
            target.SegundoApellido = source.SegundoApellido;
            target.PrimerNombre = source.PrimerNombre;
            target.SegundoNombre = source.SegundoNombre;
            target.Direccion = source.Direccion;
            target.CodigoPais = source.CodigoPais;
            target.CodigoEstado = source.CodigoEstado;
            target.CodigoCiudad = source.CodigoCiudad;
            target.CodigoPostal = source.CodigoPostal;
            target.CodigoFidelidadDireccion = source.CodigoFidelidadDireccion;
            target.Telefono1 = source.Telefono1;
            target.Telefono2 = source.Telefono2;
            target.Email = source.Email;
            target.FechaNacimiento = source.FechaNacimiento;
            target.Sexo = source.Sexo;
            target.NumeroAlumnoViejo = source.NumeroAlumnoViejo;
            target.CodigoRecibeBoletin = source.CodigoRecibeBoletin;
            target.UsuarioUltimaActualizacion = source.UsuarioUltimaActualizacion;
            target.FechaUltimaActualizacion = source.FechaUltimaActualizacion;
            target.HoraUltimaActualizacion = source.HoraUltimaActualizacion;
            target.Documento = source.Documento;
            target.FechaFidelidadDireccion = source.FechaFidelidadDireccion;
            target.TipoDocumento = source.TipoDocumento;
            target.CodigoVigencia = source.CodigoVigencia;
            target.CodigoFuenteDatos = source.CodigoFuenteDatos;
            target.Observaciones = source.Observaciones;
            target.PrimerNombreMay = source.PrimerNombreMay;
            target.SegundoNombreMay = source.SegundoNombreMay;
            target.PrimerApellidoMay = source.PrimerApellidoMay;
            target.SegundoApellidoMay = source.SegundoApellidoMay;
            target.IdFuncionario = source.IdFuncionario;
            target.CredencialCivica = source.CredencialCivica;
            target.CodigoPaisNacimiento = source.CodigoPaisNacimiento;
            target.EstadoCivil = source.EstadoCivil;
            target.EntreCalles = source.EntreCalles;
            target.Barrio = source.Barrio;
            target.SeccionalPolicial = source.SeccionalPolicial;
            target.CodigoBachillerato = source.CodigoBachillerato;
            target.FechaIngresoOrt = source.FechaIngresoOrt;
            target.FechaExclusividad = source.FechaExclusividad;
            target.Contratable = source.Contratable;
            target.FechaContratable = source.FechaContratable;
            target.Empresa = source.Empresa;
            target.Afap = source.Afap;
            target.Bancomat = source.Bancomat;
            target.TipoCuenta = source.TipoCuenta;
            target.NroCuenta = source.NroCuenta;
            target.FechaActualizacionLegajo = source.FechaActualizacionLegajo;
            target.FechaBachillerato = source.FechaBachillerato;
            target.CodigoInstitucionBac = source.CodigoInstitucionBac;
            target.IdNivelEducacion = source.IdNivelEducacion;
            target.FechaUltModifPassword = source.FechaUltModifPassword;
            target.UsuarioUltModifPassword = source.UsuarioUltModifPassword;
            target.FechaExpiracionPassword = source.FechaExpiracionPassword;
            target.PasswordOld = source.PasswordOld;
            target.NumeroAlumnoAnterior = source.NumeroAlumnoAnterior;
            target.UltimaconexionwebPersona = source.UltimaconexionwebPersona;
            target.TelefonoLaboralPersona = source.TelefonoLaboralPersona;
            target.PercibeJubilacionPersona = source.PercibeJubilacionPersona;
            target.CajaJubilacionPersona = source.CajaJubilacionPersona;
            target.NacionalidadPersona = source.NacionalidadPersona;
            target.IdBanco = source.IdBanco;
            target.SerieCredencialPersona = source.SerieCredencialPersona;
            target.NumeroCredencialPersona = source.NumeroCredencialPersona;
            target.FuncionarioActivoPersona = source.FuncionarioActivoPersona;
            target.FechaActivoPersona = source.FechaActivoPersona;
            target.LpdPersona = source.LpdPersona;
            target.PagaOrtBancomatPersona = source.PagaOrtBancomatPersona;
            target.IdSeguroSaludPersona = source.IdSeguroSaludPersona;
            target.BancoCuentaPersona = source.BancoCuentaPersona;
            target.FaxEmpresa = source.FaxEmpresa;
            target.AsistenciaObtencionEmpleo = source.AsistenciaObtencionEmpleo;
            target.ActualizacionOk = source.ActualizacionOk;
            target.RecibeCartasPersona = source.RecibeCartasPersona;
            target.RecibeEmailsPersona = source.RecibeEmailsPersona;
            target.UsuarioConfDatosPersona = source.UsuarioConfDatosPersona;
            target.FechaConfDatosPersona = source.FechaConfDatosPersona;
            target.HoraConfDatosPersona = source.HoraConfDatosPersona;
            target.BuscaTrabajoPersona = source.BuscaTrabajoPersona;
            target.Contacto1Persona = source.Contacto1Persona;
            target.Contacto2Persona = source.Contacto2Persona;
            target.IdSucursal = source.IdSucursal;
            target.CodigoSucursal = source.CodigoSucursal;
            target.CreoEmpresaPersona = source.CreoEmpresaPersona;
            target.RetiraReciboPersona = source.RetiraReciboPersona;
            target.TopeAfapPersona = source.TopeAfapPersona;
            target.TipoFechaBachillerato = source.TipoFechaBachillerato;
            target.FechaBajaOrt = source.FechaBajaOrt;
            target.TicketDocentePersona = source.TicketDocentePersona;
            target.TicketAdmPersona = source.TicketAdmPersona;
            target.RecibeNoticiasDeportivas = source.RecibeNoticiasDeportivas;
            target.TipoRetencionPersona = source.TipoRetencionPersona;
            target.ValorRetencionPersona = source.ValorRetencionPersona;
            target.AlumnoExtranjeroPersona = source.AlumnoExtranjeroPersona;
            target.SancionGravePersona = source.SancionGravePersona;
            target.ObservacionesSancionPersona = source.ObservacionesSancionPersona;
            target.FechaSancionPersona = source.FechaSancionPersona;
            target.EntrevistadoCatalogoPersona = source.EntrevistadoCatalogoPersona;
            target.FechaIngresoOrtBps = source.FechaIngresoOrtBps;
            target.FechaVtoDocumentoPersona = source.FechaVtoDocumentoPersona;
            target.ExclusividadIndefPersona = source.ExclusividadIndefPersona;
            target.RecibeResultMailPersona = source.RecibeResultMailPersona;
            target.IdFuncionarioViejo = source.IdFuncionarioViejo;
            target.ExtranjeroFuncionarioPersona = source.ExtranjeroFuncionarioPersona;
            target.TipoPersona = source.TipoPersona;
            target.GraduadoEstrellaPersona = source.GraduadoEstrellaPersona;
            target.TrabajaExteriorPersona = source.TrabajaExteriorPersona;
            target.ComentarioCargoPersona = source.ComentarioCargoPersona;
            target.IdEmpleadorPersona = source.IdEmpleadorPersona;
            target.FechaclasiflaboralPersona = source.FechaclasiflaboralPersona;
            target.IdTipoOcupacionActual = source.IdTipoOcupacionActual;
            target.FueraProfesionPersona = source.FueraProfesionPersona;
            target.FechaInduccionPersona = source.FechaInduccionPersona;
            target.ObservaInduccionPersona = source.ObservaInduccionPersona;
            target.TituloGradoPersona = source.TituloGradoPersona;
            target.UsoexclusivodbaPersona = source.UsoexclusivodbaPersona;
            target.IdBuscaTrabajo = source.IdBuscaTrabajo;
            target.CorrectorPersona = source.CorrectorPersona;
            target.FechaCorrectorPersona = source.FechaCorrectorPersona;
            target.IntentosCambioPassword = source.IntentosCambioPassword;
            target.OtrasactividadesCargoPersona = source.OtrasactividadesCargoPersona;
            target.TrabajaActualmente = source.TrabajaActualmente;
            target.ComputoEspecialPersona = source.ComputoEspecialPersona;
            target.DatosWebPersona = source.DatosWebPersona;
            target.MarcaVerificadoPersona = source.MarcaVerificadoPersona;
            target.FechaVerificadoPersona = source.FechaVerificadoPersona;
            target.FechaVerifDocPersona = source.FechaVerifDocPersona;
            target.EstadoCuidantePersona = source.EstadoCuidantePersona;
            target.VigenciaCuidantePersona = source.VigenciaCuidantePersona;
            target.ObservacionesCuidantePersona = source.ObservacionesCuidantePersona;
            target.AplicaPrimerTopeBpsPersona = source.AplicaPrimerTopeBpsPersona;
            target.IdCausalEgresoPersona = source.IdCausalEgresoPersona;
            target.Fechaexoneraexclusivapersona = source.Fechaexoneraexclusivapersona;
            target.Observacexoneraexclusivpersona = source.Observacexoneraexclusivpersona;
            target.CodadmPersona = source.CodadmPersona;
            target.CodadmObservacionPersona = source.CodadmObservacionPersona;
            target.RegimenFluctuantePersona = source.RegimenFluctuantePersona;
            target.OpcionAdelantosPersona = source.OpcionAdelantosPersona;
            target.ModoTicketsPersona = source.ModoTicketsPersona;
            target.TipoLegajoPersona = source.TipoLegajoPersona;
            target.FechaInformeRegimenPersona = source.FechaInformeRegimenPersona;
            target.UsuarioInformeRegimenPer = source.UsuarioInformeRegimenPer;
            target.ObsInformeRegimenPersona = source.ObsInformeRegimenPersona;
            target.HabilitadoAdelantoPersona = source.HabilitadoAdelantoPersona;
            target.FechaConfOpcionAdelanto = source.FechaConfOpcionAdelanto;
            target.FechaFirmaDocumentoRegimen = source.FechaFirmaDocumentoRegimen;
            target.PartidasAdelantosPersona = source.PartidasAdelantosPersona;
            target.TarjetaEmitidaPersona = source.TarjetaEmitidaPersona;
            target.FechaemisionTarjetaPersona = source.FechaemisionTarjetaPersona;
            target.FechasolicitudTarjetaPersona = source.FechasolicitudTarjetaPersona;
            target.FechaVtoCarneSalud = source.FechaVtoCarneSalud;
            target.RecepcionDocumentoRegimen = source.RecepcionDocumentoRegimen;
            target.InscribiblePersona = source.InscribiblePersona;
            target.ObservacionesInscribiblePer = source.ObservacionesInscribiblePer;
            target.FechaEgresoLiqDoc = source.FechaEgresoLiqDoc;
            target.VinculoFuncionalPersona = source.VinculoFuncionalPersona;
            target.PercibeJubilacionafapPersona = source.PercibeJubilacionafapPersona;
            target.UsuarioModifFdp = source.UsuarioModifFdp;
            target.IdCajaJubilacionPersona = source.IdCajaJubilacionPersona;
            target.JubiladoPersona = source.JubiladoPersona;
            target.CodigoAcumulacionLaboral = source.CodigoAcumulacionLaboral;
            target.ObservacionesNocontratablePe = source.ObservacionesNocontratablePe;
            target.FechaConfSnisPersona = source.FechaConfSnisPersona;
            target.FechaConf3100Persona = source.FechaConf3100Persona;
            target.LinkedinPersona = source.LinkedinPersona;
            target.FechaJubiladoAfapPersona = source.FechaJubiladoAfapPersona;
            target.FechaJubiladoBpsPersona = source.FechaJubiladoBpsPersona;
            target.EmailEmpresa = source.EmailEmpresa;
            target.TipoJornada = source.TipoJornada;
            target.IdCaracteristicaPaisTel1 = source.IdCaracteristicaPaisTel1;
            target.IdCaracteristicaPaisTel2 = source.IdCaracteristicaPaisTel2;
            target.EmailOrtPersona = source.EmailOrtPersona;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPersonaDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Persona> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPersonaDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Persona> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Persona> ToEntities(this IEnumerable<DtoPersonaDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Persona source, DtoPersonaDevart target);

        static partial void OnEntityCreating(DtoPersonaDevart source, BusinessLogic.Entities.Persona target);

    }

}
