//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class ProcesoComienzoConverter
    {

        public static DtoProcesoComienzoDevart ToDto(this BusinessLogic.Entities.ProcesoComienzo source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoProcesoComienzoDevart ToDtoWithRelated(this BusinessLogic.Entities.ProcesoComienzo source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoProcesoComienzoDevart();

            // Properties
            target.IdProceso = source.IdProceso;
            target.IdComienzo = source.IdComienzo;
            target.HoraIngreso = source.HoraIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // Navigation Properties
            if (level > 0) {
              target.Proceso = source.Proceso.ToDtoWithRelated(level - 1);
              target.Comienzo = source.Comienzo.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.ProcesoComienzo ToEntity(this DtoProcesoComienzoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.ProcesoComienzo();

            // Properties
            target.IdProceso = source.IdProceso;
            target.IdComienzo = source.IdComienzo;
            target.HoraIngreso = source.HoraIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoProcesoComienzoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.ProcesoComienzo> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoProcesoComienzoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.ProcesoComienzo> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.ProcesoComienzo> ToEntities(this IEnumerable<DtoProcesoComienzoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.ProcesoComienzo source, DtoProcesoComienzoDevart target);

        static partial void OnEntityCreating(DtoProcesoComienzoDevart source, BusinessLogic.Entities.ProcesoComienzo target);

    }

}
