//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class ProductoConverter
    {

        public static DtoProductoDevart ToDto(this BusinessLogic.Entities.Producto source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoProductoDevart ToDtoWithRelated(this BusinessLogic.Entities.Producto source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoProductoDevart();

            // Properties
            target.IdProducto = source.IdProducto;
            target.NombreProducto = source.NombreProducto;
            target.NombreExtensoProducto = source.NombreExtensoProducto;
            target.DescripcionProducto = source.DescripcionProducto;
            target.ObservacionesProducto = source.ObservacionesProducto;
            target.FechaCreacionProducto = source.FechaCreacionProducto;
            target.FechaCaducidadProducto = source.FechaCaducidadProducto;
            target.DestinoRegaliaProducto = source.DestinoRegaliaProducto;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.IdDepartamento = source.IdDepartamento;
            target.DepartamentoRpg = source.DepartamentoRpg;
            target.CarreraRpg = source.CarreraRpg;
            target.FicticioProducto = source.FicticioProducto;
            target.PermiteInteresadoProducto = source.PermiteInteresadoProducto;
            target.IdNivelProducto = source.IdNivelProducto;
            target.IdCentroCostos = source.IdCentroCostos;
            target.IdCentroGastos = source.IdCentroGastos;
            target.AliasProducto = source.AliasProducto;
            target.IntermedioProducto = source.IntermedioProducto;
            target.InscribibleProducto = source.InscribibleProducto;
            target.MesesDuracionProducto = source.MesesDuracionProducto;
            target.IdAgrupacion = source.IdAgrupacion;
            target.EmailDistribProducto = source.EmailDistribProducto;
            target.ComputoEspecialHlProducto = source.ComputoEspecialHlProducto;
            target.MinPacHonoresProducto = source.MinPacHonoresProducto;
            target.NombreCoordAcadProducto = source.NombreCoordAcadProducto;
            target.EmailCoordAcadProducto = source.EmailCoordAcadProducto;
            target.CertificacionExternaProducto = source.CertificacionExternaProducto;
            target.IdCcAntesPsig = source.IdCcAntesPsig;
            target.IdCgAntesPsig = source.IdCgAntesPsig;
            target.IdNivelPostgrado = source.IdNivelPostgrado;
            target.IdNivelWebProducto = source.IdNivelWebProducto;
            target.OrientacionProducto = source.OrientacionProducto;
            target.UsernameCooacadProducto = source.UsernameCooacadProducto;
            target.TituloIntermedioProducto = source.TituloIntermedioProducto;
            target.TituloFinalProducto = source.TituloFinalProducto;
            target.ReconocimientoMecProducto = source.ReconocimientoMecProducto;
            target.TramiteReconocimProducto = source.TramiteReconocimProducto;
            target.OtroReconocimientoProducto = source.OtroReconocimientoProducto;
            target.EmailContactoProducto = source.EmailContactoProducto;
            target.TelefonoContactoProducto = source.TelefonoContactoProducto;
            target.DuracionProducto = source.DuracionProducto;
            target.HorarioProducto = source.HorarioProducto;
            target.RequisitoIngresoProducto = source.RequisitoIngresoProducto;
            target.CostoProducto = source.CostoProducto;
            target.RequisitoGradProducto = source.RequisitoGradProducto;
            target.FolletoProducto = source.FolletoProducto;
            target.ActivoWebProducto = source.ActivoWebProducto;
            target.NombreWebProducto = source.NombreWebProducto;
            target.EmailActividadesProducto = source.EmailActividadesProducto;
            target.DescAutoGraduadoProducto = source.DescAutoGraduadoProducto;
            target.EncgradRectorProducto = source.EncgradRectorProducto;
            target.VisibleAdmisionesProducto = source.VisibleAdmisionesProducto;
            target.ComienzoenagostoProducto = source.ComienzoenagostoProducto;
            target.AplicaCanillaProducto = source.AplicaCanillaProducto;
            target.UsernameCooadjProducto = source.UsernameCooadjProducto;
            target.UsernameCooadjSegProducto = source.UsernameCooadjSegProducto;
            target.ExcluirCartaFrescoProducto = source.ExcluirCartaFrescoProducto;
            target.CajaProfesionalProducto = source.CajaProfesionalProducto;
            target.ProgConSeminariosProducto = source.ProgConSeminariosProducto;

            // Navigation Properties
            if (level > 0) {
              target.NivelProducto = source.NivelProducto.ToDtoWithRelated(level - 1);
              target.SolicitudAltas = source.SolicitudAltas.ToDtosWithRelated(level - 1);
              target.ProcesoProductos = source.ProcesoProductos.ToDtosWithRelated(level - 1);
              target.Departamento = source.Departamento.ToDtoWithRelated(level - 1);
              target.Paquetes = source.Paquetes.ToDtosWithRelated(level - 1);
              target.InteresProductos = source.InteresProductos.ToDtosWithRelated(level - 1);
              target.Inscriptos_IdProductoReal = source.Inscriptos_IdProductoReal.ToDtosWithRelated(level - 1);
              target.Inscriptos_IdProductoPcounter = source.Inscriptos_IdProductoPcounter.ToDtosWithRelated(level - 1);
              target.TituloOrts = source.TituloOrts.ToDtosWithRelated(level - 1);
              target.DeclaracionJuradaWebs = source.DeclaracionJuradaWebs.ToDtosWithRelated(level - 1);
              target.CentroCosto = source.CentroCosto.ToDtoWithRelated(level - 1);
              target.InscriptoPruebas_IdProducto = source.InscriptoPruebas_IdProducto.ToDtosWithRelated(level - 1);
              target.InscriptoPruebas_IdProductoOriginal = source.InscriptoPruebas_IdProductoOriginal.ToDtosWithRelated(level - 1);
              target.EncuestaIniAdmisions = source.EncuestaIniAdmisions.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Producto ToEntity(this DtoProductoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Producto();

            // Properties
            target.IdProducto = source.IdProducto;
            target.NombreProducto = source.NombreProducto;
            target.NombreExtensoProducto = source.NombreExtensoProducto;
            target.DescripcionProducto = source.DescripcionProducto;
            target.ObservacionesProducto = source.ObservacionesProducto;
            target.FechaCreacionProducto = source.FechaCreacionProducto;
            target.FechaCaducidadProducto = source.FechaCaducidadProducto;
            target.DestinoRegaliaProducto = source.DestinoRegaliaProducto;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.IdDepartamento = source.IdDepartamento;
            target.DepartamentoRpg = source.DepartamentoRpg;
            target.CarreraRpg = source.CarreraRpg;
            target.FicticioProducto = source.FicticioProducto;
            target.PermiteInteresadoProducto = source.PermiteInteresadoProducto;
            target.IdNivelProducto = source.IdNivelProducto;
            target.IdCentroCostos = source.IdCentroCostos;
            target.IdCentroGastos = source.IdCentroGastos;
            target.AliasProducto = source.AliasProducto;
            target.IntermedioProducto = source.IntermedioProducto;
            target.InscribibleProducto = source.InscribibleProducto;
            target.MesesDuracionProducto = source.MesesDuracionProducto;
            target.IdAgrupacion = source.IdAgrupacion;
            target.EmailDistribProducto = source.EmailDistribProducto;
            target.ComputoEspecialHlProducto = source.ComputoEspecialHlProducto;
            target.MinPacHonoresProducto = source.MinPacHonoresProducto;
            target.NombreCoordAcadProducto = source.NombreCoordAcadProducto;
            target.EmailCoordAcadProducto = source.EmailCoordAcadProducto;
            target.CertificacionExternaProducto = source.CertificacionExternaProducto;
            target.IdCcAntesPsig = source.IdCcAntesPsig;
            target.IdCgAntesPsig = source.IdCgAntesPsig;
            target.IdNivelPostgrado = source.IdNivelPostgrado;
            target.IdNivelWebProducto = source.IdNivelWebProducto;
            target.OrientacionProducto = source.OrientacionProducto;
            target.UsernameCooacadProducto = source.UsernameCooacadProducto;
            target.TituloIntermedioProducto = source.TituloIntermedioProducto;
            target.TituloFinalProducto = source.TituloFinalProducto;
            target.ReconocimientoMecProducto = source.ReconocimientoMecProducto;
            target.TramiteReconocimProducto = source.TramiteReconocimProducto;
            target.OtroReconocimientoProducto = source.OtroReconocimientoProducto;
            target.EmailContactoProducto = source.EmailContactoProducto;
            target.TelefonoContactoProducto = source.TelefonoContactoProducto;
            target.DuracionProducto = source.DuracionProducto;
            target.HorarioProducto = source.HorarioProducto;
            target.RequisitoIngresoProducto = source.RequisitoIngresoProducto;
            target.CostoProducto = source.CostoProducto;
            target.RequisitoGradProducto = source.RequisitoGradProducto;
            target.FolletoProducto = source.FolletoProducto;
            target.ActivoWebProducto = source.ActivoWebProducto;
            target.NombreWebProducto = source.NombreWebProducto;
            target.EmailActividadesProducto = source.EmailActividadesProducto;
            target.DescAutoGraduadoProducto = source.DescAutoGraduadoProducto;
            target.EncgradRectorProducto = source.EncgradRectorProducto;
            target.VisibleAdmisionesProducto = source.VisibleAdmisionesProducto;
            target.ComienzoenagostoProducto = source.ComienzoenagostoProducto;
            target.AplicaCanillaProducto = source.AplicaCanillaProducto;
            target.UsernameCooadjProducto = source.UsernameCooadjProducto;
            target.UsernameCooadjSegProducto = source.UsernameCooadjSegProducto;
            target.ExcluirCartaFrescoProducto = source.ExcluirCartaFrescoProducto;
            target.CajaProfesionalProducto = source.CajaProfesionalProducto;
            target.ProgConSeminariosProducto = source.ProgConSeminariosProducto;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoProductoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Producto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoProductoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Producto> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Producto> ToEntities(this IEnumerable<DtoProductoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Producto source, DtoProductoDevart target);

        static partial void OnEntityCreating(DtoProductoDevart source, BusinessLogic.Entities.Producto target);

    }

}
