//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PruebaConverter
    {

        public static DtoPruebaDevart ToDto(this BusinessLogic.Entities.Prueba source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPruebaDevart ToDtoWithRelated(this BusinessLogic.Entities.Prueba source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPruebaDevart();

            // Properties
            target.IdPrueba = source.IdPrueba;
            target.IdComienzo = source.IdComienzo;
            target.IdComienzoPrueba = source.IdComienzoPrueba;
            target.IdTipoBeca = source.IdTipoBeca;
            target.FechaLimiteGuiaPrueba = source.FechaLimiteGuiaPrueba;
            target.FechaEntregaDjPrueba = source.FechaEntregaDjPrueba;
            target.HoraExamenPrueba = source.HoraExamenPrueba;
            target.CupoPrueba = source.CupoPrueba;
            target.FechaExamenPrueba = source.FechaExamenPrueba;
            target.HoraPresentacionPrueba = source.HoraPresentacionPrueba;
            target.HoraLimiteGuiaPrueba = source.HoraLimiteGuiaPrueba;
            target.HoraEntregaDjPrueba = source.HoraEntregaDjPrueba;
            target.FechaResultadoPrueba = source.FechaResultadoPrueba;
            target.HoraResultadoPrueba = source.HoraResultadoPrueba;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.IdLocalidad = source.IdLocalidad;
            target.EstadoPrueba = source.EstadoPrueba;
            target.FechaCaducidadPrueba = source.FechaCaducidadPrueba;
            target.ControlInscrPrueba = source.ControlInscrPrueba;
            target.HabilitadaPrueba = source.HabilitadaPrueba;
            target.LugarResultadoPrueba = source.LugarResultadoPrueba;
            target.DuracionPrueba = source.DuracionPrueba;
            target.FechaDifusionwebPrueba = source.FechaDifusionwebPrueba;
            target.HabilitadoSitioadmiPrueba = source.HabilitadoSitioadmiPrueba;

            // Navigation Properties
            if (level > 0) {
              target.Comienzo = source.Comienzo.ToDtoWithRelated(level - 1);
              target.TipoDescuento = source.TipoDescuento.ToDtoWithRelated(level - 1);
              target.Accions = source.Accions.ToDtosWithRelated(level - 1);
              target.InscriptoPruebas = source.InscriptoPruebas.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Prueba ToEntity(this DtoPruebaDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Prueba();

            // Properties
            target.IdPrueba = source.IdPrueba;
            target.IdComienzo = source.IdComienzo;
            target.IdComienzoPrueba = source.IdComienzoPrueba;
            target.IdTipoBeca = source.IdTipoBeca;
            target.FechaLimiteGuiaPrueba = source.FechaLimiteGuiaPrueba;
            target.FechaEntregaDjPrueba = source.FechaEntregaDjPrueba;
            target.HoraExamenPrueba = source.HoraExamenPrueba;
            target.CupoPrueba = source.CupoPrueba;
            target.FechaExamenPrueba = source.FechaExamenPrueba;
            target.HoraPresentacionPrueba = source.HoraPresentacionPrueba;
            target.HoraLimiteGuiaPrueba = source.HoraLimiteGuiaPrueba;
            target.HoraEntregaDjPrueba = source.HoraEntregaDjPrueba;
            target.FechaResultadoPrueba = source.FechaResultadoPrueba;
            target.HoraResultadoPrueba = source.HoraResultadoPrueba;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;
            target.IdLocalidad = source.IdLocalidad;
            target.EstadoPrueba = source.EstadoPrueba;
            target.FechaCaducidadPrueba = source.FechaCaducidadPrueba;
            target.ControlInscrPrueba = source.ControlInscrPrueba;
            target.HabilitadaPrueba = source.HabilitadaPrueba;
            target.LugarResultadoPrueba = source.LugarResultadoPrueba;
            target.DuracionPrueba = source.DuracionPrueba;
            target.FechaDifusionwebPrueba = source.FechaDifusionwebPrueba;
            target.HabilitadoSitioadmiPrueba = source.HabilitadoSitioadmiPrueba;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPruebaDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Prueba> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPruebaDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Prueba> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Prueba> ToEntities(this IEnumerable<DtoPruebaDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Prueba source, DtoPruebaDevart target);

        static partial void OnEntityCreating(DtoPruebaDevart source, BusinessLogic.Entities.Prueba target);

    }

}
