//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class PublicidadOpcionesAdmisionConverter
    {

        public static DtoPublicidadOpcionesAdmisionDevart ToDto(this BusinessLogic.Entities.PublicidadOpcionesAdmision source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoPublicidadOpcionesAdmisionDevart ToDtoWithRelated(this BusinessLogic.Entities.PublicidadOpcionesAdmision source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoPublicidadOpcionesAdmisionDevart();

            // Properties
            target.IdPublicidad = source.IdPublicidad;
            target.NombrePublicidad = source.NombrePublicidad;

            // Navigation Properties
            if (level > 0) {
              target.PublicidadEleccionAdmisions = source.PublicidadEleccionAdmisions.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.PublicidadOpcionesAdmision ToEntity(this DtoPublicidadOpcionesAdmisionDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.PublicidadOpcionesAdmision();

            // Properties
            target.IdPublicidad = source.IdPublicidad;
            target.NombrePublicidad = source.NombrePublicidad;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoPublicidadOpcionesAdmisionDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.PublicidadOpcionesAdmision> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoPublicidadOpcionesAdmisionDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.PublicidadOpcionesAdmision> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.PublicidadOpcionesAdmision> ToEntities(this IEnumerable<DtoPublicidadOpcionesAdmisionDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.PublicidadOpcionesAdmision source, DtoPublicidadOpcionesAdmisionDevart target);

        static partial void OnEntityCreating(DtoPublicidadOpcionesAdmisionDevart source, BusinessLogic.Entities.PublicidadOpcionesAdmision target);

    }

}
