//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class RefreshTokenConverter
    {

        public static DtoRefreshTokenDevart ToDto(this BusinessLogic.Entities.RefreshToken source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoRefreshTokenDevart ToDtoWithRelated(this BusinessLogic.Entities.RefreshToken source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoRefreshTokenDevart();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.Sistema = source.Sistema;
            target.TokenHash = source.TokenHash;
            target.ExpiresAt = source.ExpiresAt;
            target.CreatedAt = source.CreatedAt;
            target.RevokedAt = source.RevokedAt;
            target.RemplaceByTokenId = source.RemplaceByTokenId;
            target.IsActive = source.IsActive;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // Navigation Properties
            if (level > 0) {
              target.Persona = source.Persona.ToDtoWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.RefreshToken ToEntity(this DtoRefreshTokenDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.RefreshToken();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.Sistema = source.Sistema;
            target.TokenHash = source.TokenHash;
            target.ExpiresAt = source.ExpiresAt;
            target.CreatedAt = source.CreatedAt;
            target.RevokedAt = source.RevokedAt;
            target.RemplaceByTokenId = source.RemplaceByTokenId;
            target.IsActive = source.IsActive;
            target.FechaIngreso = source.FechaIngreso;
            target.HoraIngreso = source.HoraIngreso;
            target.UsuarioIngreso = source.UsuarioIngreso;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoRefreshTokenDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.RefreshToken> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoRefreshTokenDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.RefreshToken> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.RefreshToken> ToEntities(this IEnumerable<DtoRefreshTokenDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.RefreshToken source, DtoRefreshTokenDevart target);

        static partial void OnEntityCreating(DtoRefreshTokenDevart source, BusinessLogic.Entities.RefreshToken target);

    }

}
