//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class TipoDescuentoConverter
    {

        public static DtoTipoDescuentoDevart ToDto(this BusinessLogic.Entities.TipoDescuento source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoTipoDescuentoDevart ToDtoWithRelated(this BusinessLogic.Entities.TipoDescuento source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoTipoDescuentoDevart();

            // Properties
            target.IdTipoDescuento = source.IdTipoDescuento;
            target.NombreTipoDescuento = source.NombreTipoDescuento;
            target.CodigoRpgDescuento = source.CodigoRpgDescuento;
            target.PorcentajeTipoDescuento = source.PorcentajeTipoDescuento;
            target.ObservacionesTipoDescuento = source.ObservacionesTipoDescuento;
            target.EsFijoTipoDescuento = source.EsFijoTipoDescuento;
            target.AliasTipoDescuento = source.AliasTipoDescuento;
            target.ReimputableTipoDescuento = source.ReimputableTipoDescuento;
            target.VigenciaTipoDescuento = source.VigenciaTipoDescuento;
            target.IdFamiliaTipoDescuento = source.IdFamiliaTipoDescuento;
            target.ReimputablelpdTipoDescuento = source.ReimputablelpdTipoDescuento;
            target.IdGrupoTipoDescuento = source.IdGrupoTipoDescuento;
            target.DetalleTipoDescuento = source.DetalleTipoDescuento;
            target.TopeadoTipoDescuento = source.TopeadoTipoDescuento;
            target.AplicaIdtTipoDescuento = source.AplicaIdtTipoDescuento;

            // Navigation Properties
            if (level > 0) {
              target.DeclaracionJuradaWebs = source.DeclaracionJuradaWebs.ToDtosWithRelated(level - 1);
              target.Pruebas = source.Pruebas.ToDtosWithRelated(level - 1);
              target.TipoBecaNivelProductos = source.TipoBecaNivelProductos.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.TipoDescuento ToEntity(this DtoTipoDescuentoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.TipoDescuento();

            // Properties
            target.IdTipoDescuento = source.IdTipoDescuento;
            target.NombreTipoDescuento = source.NombreTipoDescuento;
            target.CodigoRpgDescuento = source.CodigoRpgDescuento;
            target.PorcentajeTipoDescuento = source.PorcentajeTipoDescuento;
            target.ObservacionesTipoDescuento = source.ObservacionesTipoDescuento;
            target.EsFijoTipoDescuento = source.EsFijoTipoDescuento;
            target.AliasTipoDescuento = source.AliasTipoDescuento;
            target.ReimputableTipoDescuento = source.ReimputableTipoDescuento;
            target.VigenciaTipoDescuento = source.VigenciaTipoDescuento;
            target.IdFamiliaTipoDescuento = source.IdFamiliaTipoDescuento;
            target.ReimputablelpdTipoDescuento = source.ReimputablelpdTipoDescuento;
            target.IdGrupoTipoDescuento = source.IdGrupoTipoDescuento;
            target.DetalleTipoDescuento = source.DetalleTipoDescuento;
            target.TopeadoTipoDescuento = source.TopeadoTipoDescuento;
            target.AplicaIdtTipoDescuento = source.AplicaIdtTipoDescuento;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoTipoDescuentoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.TipoDescuento> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoTipoDescuentoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.TipoDescuento> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.TipoDescuento> ToEntities(this IEnumerable<DtoTipoDescuentoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.TipoDescuento source, DtoTipoDescuentoDevart target);

        static partial void OnEntityCreating(DtoTipoDescuentoDevart source, BusinessLogic.Entities.TipoDescuento target);

    }

}
