//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoAccesoSitiosantanderDevart
    {

        #region Properties

        [Key]
        [Required()]
        public DateTime FechaAccesoSitiosantander { get; set; }

        [Key]
        [StringLength(8)]
        [Required()]
        public string HoraAccesoSitiosantander { get; set; }

        [Key]
        [Required()]
        public long CodigoPersona { get; set; }

        public decimal? IdSistema { get; set; }

        #endregion

        #region Navigation Properties

        public DtoPersonaDevart Persona { get; set; }

        #endregion
    }

}
