//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public partial class DtoVdInscripcionesFresco3y4Devart
    {

        #region Properties

        public decimal? CodigoPersona { get; set; }

        public DateTime? FechaInscripcion { get; set; }

        [StringLength(30)]
        public string? UsuarioInscripcion { get; set; }

        public decimal? IdTurno { get; set; }

        public decimal? IdProducto { get; set; }

        public decimal? IdComienzo { get; set; }

        public DateTime? FechaInicioComienzo { get; set; }

        [StringLength(90)]
        public string? NombreExtensoProducto { get; set; }

        public long? IdNivelProducto { get; set; }

        [StringLength(30)]
        public string? NombreComienzo { get; set; }

        [StringLength(30)]
        public string? NombreTurno { get; set; }

        public decimal? IdProceso { get; set; }

        public DateTime? FechaReferencia { get; set; }

        public decimal? IdInscripto { get; set; }

        [StringLength(14)]
        public string? EstadoInscripcion { get; set; }

        [StringLength(63)]
        public string? VengoDe { get; set; }

        public long? IdOferta { get; set; }

        [StringLength(1000)]
        public string? DescripcionOferta { get; set; }

        [StringLength(2)]
        public string? ProgConSeminariosProducto { get; set; }

        public DateTime? FechaVtoInscr { get; set; }

        #endregion
    }

}
