//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 03/03/2026 15:37:20
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IAccionRepository : IRepository<BusinessLogic.Entities.Accion>
    {
        ICollection<BusinessLogic.Entities.Accion> GetAll();
        BusinessLogic.Entities.Accion GetByKey(decimal _IdAccion);
    }
}
