//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 26/06/2026 10:52:37
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IAceptacionReglamentoEstRepository : IRepository<BusinessLogic.Entities.AceptacionReglamentoEst>
    {
        ICollection<BusinessLogic.Entities.AceptacionReglamentoEst> GetAll();
        BusinessLogic.Entities.AceptacionReglamentoEst GetByKey(decimal _IdAceptacionReglamentoEst);
    }
}
