//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 12/06/2026 13:55:25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IBachilleratoPersonaRepository : IRepository<BusinessLogic.Entities.BachilleratoPersona>
    {
        ICollection<BusinessLogic.Entities.BachilleratoPersona> GetAll();
        BusinessLogic.Entities.BachilleratoPersona GetByKey(long _CodigoPersona);
    }
}
