//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 29/06/2026 14:04:22
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IEmpresaConsideradaAdmisionRepository : IRepository<BusinessLogic.Entities.EmpresaConsideradaAdmision>
    {
        ICollection<BusinessLogic.Entities.EmpresaConsideradaAdmision> GetAll();
        BusinessLogic.Entities.EmpresaConsideradaAdmision GetByKey(long _IdEmpresaConsiderada);
    }
}
