//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using BusinessLogic.Entities;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IInscriptoRepository
    {
        Inscripto GetUltimaInscripcionActiva(long codigoPersona);
        IEnumerable<Inscripto> GetInscripcionesRealizadas(long codigoPersona);
        bool TieneInscripcionActiva(long codigoPersona);
        bool TieneInscripcionAdmisiones(long codigoPersona, long idProducto, long idProceso);
        bool TieneInscripcionPreviaAProducto(long codigoPersona, long idProducto);
    }
}
