//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 28/07/2026 16:32:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IIntegranteNfDjRepository : IRepository<BusinessLogic.Entities.IntegranteNfDj>
    {
        ICollection<BusinessLogic.Entities.IntegranteNfDj> GetAll();
        BusinessLogic.Entities.IntegranteNfDj GetByKey(decimal _IdIntegranteNfDj);
    }
}
