//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 30/07/2026 11:50:00
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IOfertaCreditoMateriaRepository : IRepository<BusinessLogic.Entities.OfertaCreditoMateria>
    {
        ICollection<BusinessLogic.Entities.OfertaCreditoMateria> GetAll();
        BusinessLogic.Entities.OfertaCreditoMateria GetByKey(long _IdOfertaCredito, long _IdMateria);
    }
}
