//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 22/07/2026 9:49:45
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IOfertaCreditoRepository : IRepository<BusinessLogic.Entities.OfertaCredito>
    {
        ICollection<BusinessLogic.Entities.OfertaCredito> GetAll();
        BusinessLogic.Entities.OfertaCredito GetByKey(long _IdOfertaCredito);
    }
}
