//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 24/06/2026 9:25:48
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IPersonaAdmiteRepository : IRepository<BusinessLogic.Entities.PersonaAdmite>
    {
        ICollection<BusinessLogic.Entities.PersonaAdmite> GetAll();
        BusinessLogic.Entities.PersonaAdmite GetByKey(long _CodigoPersona);
    }
}
