//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System.Collections.Generic;
using BusinessLogic.Entities;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IProcesoComienzoRepository
    {
        BusinessLogic.Entities.ProcesoComienzo GetByKeyWithRelated(long idProceso, long idComienzo);
        ICollection<BusinessLogic.Entities.ProcesoComienzo> GetAllWithRelated();
    }
}