//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 25/05/2026 16:54:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IProductoRepository : IRepository<BusinessLogic.Entities.Producto>
    {
        ICollection<BusinessLogic.Entities.Producto> GetAll();
        BusinessLogic.Entities.Producto GetByKey(long _IdProducto);
    }
}
