//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 10/06/2026 16:51:55
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface ITipoBecaNivelProductoRepository : IRepository<BusinessLogic.Entities.TipoBecaNivelProducto>
    {
        ICollection<BusinessLogic.Entities.TipoBecaNivelProducto> GetAll();
        BusinessLogic.Entities.TipoBecaNivelProducto GetByKey(long _IdTipoBeca, long _IdNivelProducto);
    }
}
