//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 11/06/2026 9:46:56
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface ITipoDescuentoRepository : IRepository<BusinessLogic.Entities.TipoDescuento>
    {
        ICollection<BusinessLogic.Entities.TipoDescuento> GetAll();
        BusinessLogic.Entities.TipoDescuento GetByKey(long _IdTipoDescuento);
    }
}
