//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 03/03/2026 10:15:05
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
namespace BusinessLogic.IDevartRepositories
{
    public partial interface IUnitOfWorkFactory
    {
        IUnitOfWork Create();
    }
}
