//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 11/06/2026 9:46:56
//
//------------------------------------------------------------------------------
using BusinessLogic.Entities;
using System;
using System.Collections.Generic;

namespace BusinessLogic.IDevartRepositories
{
    public partial interface IVdInscripcionesFresco1y2Repository
    {
        ICollection<VdInscripcionesFresco1y2> GetInscripcionesFrescoHabilitadas(long codigoPersona);

        ICollection<VdInscripcionesFresco1y2> GetInscripcionesFrescoHabilitadas(long codigoPersona, long idProducto, long idProceso);
    }
}
