//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class IntereConverter
    {

        public static DtoIntereDevart ToDto(this BusinessLogic.Entities.Intere source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoIntereDevart ToDtoWithRelated(this BusinessLogic.Entities.Intere source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoIntereDevart();

            // Properties
            target.IdInteres = source.IdInteres;
            target.CodigoPersona = source.CodigoPersona;
            target.IdProceso = source.IdProceso;
            target.IdFormaContacto = source.IdFormaContacto;
            target.ContactadorInteres = source.ContactadorInteres;
            target.ObservacionesInteres = source.ObservacionesInteres;
            target.IdLugar = source.IdLugar;
            target.IdGradoPureza = source.IdGradoPureza;

            // Navigation Properties
            if (level > 0) {
              target.Persona = source.Persona.ToDtoWithRelated(level - 1);
              target.Proceso = source.Proceso.ToDtoWithRelated(level - 1);
              target.InteresProductos = source.InteresProductos.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Intere ToEntity(this DtoIntereDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Intere();

            // Properties
            target.IdInteres = source.IdInteres;
            target.CodigoPersona = source.CodigoPersona;
            target.IdProceso = source.IdProceso;
            target.IdFormaContacto = source.IdFormaContacto;
            target.ContactadorInteres = source.ContactadorInteres;
            target.ObservacionesInteres = source.ObservacionesInteres;
            target.IdLugar = source.IdLugar;
            target.IdGradoPureza = source.IdGradoPureza;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoIntereDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Intere> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoIntereDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Intere> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Intere> ToEntities(this IEnumerable<DtoIntereDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Intere source, DtoIntereDevart target);

        static partial void OnEntityCreating(DtoIntereDevart source, BusinessLogic.Entities.Intere target);

    }

}
