//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class VdFrescoProductoAdmisioneConverter
    {

        public static DtoVdFrescoProductoAdmisioneDevart ToDto(this BusinessLogic.Entities.VdFrescoProductoAdmisione source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoVdFrescoProductoAdmisioneDevart ToDtoWithRelated(this BusinessLogic.Entities.VdFrescoProductoAdmisione source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoVdFrescoProductoAdmisioneDevart();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.IdProducto = source.IdProducto;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.VdFrescoProductoAdmisione ToEntity(this DtoVdFrescoProductoAdmisioneDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.VdFrescoProductoAdmisione();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.IdProducto = source.IdProducto;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoVdFrescoProductoAdmisioneDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.VdFrescoProductoAdmisione> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoVdFrescoProductoAdmisioneDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.VdFrescoProductoAdmisione> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.VdFrescoProductoAdmisione> ToEntities(this IEnumerable<DtoVdFrescoProductoAdmisioneDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.VdFrescoProductoAdmisione source, DtoVdFrescoProductoAdmisioneDevart target);

        static partial void OnEntityCreating(DtoVdFrescoProductoAdmisioneDevart source, BusinessLogic.Entities.VdFrescoProductoAdmisione target);

    }

}
