//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class VdProcesosDisponibles1y2Converter
    {

        public static DtoVdProcesosDisponibles1y2Devart ToDto(this BusinessLogic.Entities.VdProcesosDisponibles1y2 source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoVdProcesosDisponibles1y2Devart ToDtoWithRelated(this BusinessLogic.Entities.VdProcesosDisponibles1y2 source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoVdProcesosDisponibles1y2Devart();

            // Properties
            target.IdProducto = source.IdProducto;
            target.IdProceso = source.IdProceso;
            target.IdTipoProceso = source.IdTipoProceso;
            target.NombreProceso = source.NombreProceso;
            target.ObservacionesProceso = source.ObservacionesProceso;
            target.FechaFinProceso = source.FechaFinProceso;
            target.ComienzoSemestre1Proceso = source.ComienzoSemestre1Proceso;
            target.Anticipada20porcientoProceso = source.Anticipada20porcientoProceso;
            target.Anticipada30porcientoProceso = source.Anticipada30porcientoProceso;
            target.Anticipada40porcientoProceso = source.Anticipada40porcientoProceso;
            target.Anticipada50porcientoProceso = source.Anticipada50porcientoProceso;
            target.Anticipada60porcientoProceso = source.Anticipada60porcientoProceso;
            target.Anticipada70porcientoProceso = source.Anticipada70porcientoProceso;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.VdProcesosDisponibles1y2 ToEntity(this DtoVdProcesosDisponibles1y2Devart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.VdProcesosDisponibles1y2();

            // Properties
            target.IdProducto = source.IdProducto;
            target.IdProceso = source.IdProceso;
            target.IdTipoProceso = source.IdTipoProceso;
            target.NombreProceso = source.NombreProceso;
            target.ObservacionesProceso = source.ObservacionesProceso;
            target.FechaFinProceso = source.FechaFinProceso;
            target.ComienzoSemestre1Proceso = source.ComienzoSemestre1Proceso;
            target.Anticipada20porcientoProceso = source.Anticipada20porcientoProceso;
            target.Anticipada30porcientoProceso = source.Anticipada30porcientoProceso;
            target.Anticipada40porcientoProceso = source.Anticipada40porcientoProceso;
            target.Anticipada50porcientoProceso = source.Anticipada50porcientoProceso;
            target.Anticipada60porcientoProceso = source.Anticipada60porcientoProceso;
            target.Anticipada70porcientoProceso = source.Anticipada70porcientoProceso;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoVdProcesosDisponibles1y2Devart> ToDtos(this IEnumerable<BusinessLogic.Entities.VdProcesosDisponibles1y2> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoVdProcesosDisponibles1y2Devart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.VdProcesosDisponibles1y2> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.VdProcesosDisponibles1y2> ToEntities(this IEnumerable<DtoVdProcesosDisponibles1y2Devart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.VdProcesosDisponibles1y2 source, DtoVdProcesosDisponibles1y2Devart target);

        static partial void OnEntityCreating(DtoVdProcesosDisponibles1y2Devart source, BusinessLogic.Entities.VdProcesosDisponibles1y2 target);

    }

}
