//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class ParametrosAdmisioneConverter
    {

        public static DtoParametrosAdmisioneDevart ToDto(this BusinessLogic.Entities.ParametrosAdmisione source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoParametrosAdmisioneDevart ToDtoWithRelated(this BusinessLogic.Entities.ParametrosAdmisione source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoParametrosAdmisioneDevart();

            // Properties
            target.DiasExtraPermiteInscr1y2 = source.DiasExtraPermiteInscr1y2;
            target.DiasExtraPermiteInscr3 = source.DiasExtraPermiteInscr3;
            target.DiasBorrarDatosEncuesta = source.DiasBorrarDatosEncuesta;
            target.DiasExtraPermiteInscr4 = source.DiasExtraPermiteInscr4;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.ParametrosAdmisione ToEntity(this DtoParametrosAdmisioneDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.ParametrosAdmisione();

            // Properties
            target.DiasExtraPermiteInscr1y2 = source.DiasExtraPermiteInscr1y2;
            target.DiasExtraPermiteInscr3 = source.DiasExtraPermiteInscr3;
            target.DiasBorrarDatosEncuesta = source.DiasBorrarDatosEncuesta;
            target.DiasExtraPermiteInscr4 = source.DiasExtraPermiteInscr4;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoParametrosAdmisioneDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.ParametrosAdmisione> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoParametrosAdmisioneDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.ParametrosAdmisione> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.ParametrosAdmisione> ToEntities(this IEnumerable<DtoParametrosAdmisioneDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.ParametrosAdmisione source, DtoParametrosAdmisioneDevart target);

        static partial void OnEntityCreating(DtoParametrosAdmisioneDevart source, BusinessLogic.Entities.ParametrosAdmisione target);

    }

}
