//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class TituloOrtConverter
    {

        public static DtoTituloOrtDevart ToDto(this BusinessLogic.Entities.TituloOrt source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoTituloOrtDevart ToDtoWithRelated(this BusinessLogic.Entities.TituloOrt source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoTituloOrtDevart();

            // Properties
            target.IdTitulo = source.IdTitulo;
            target.NombreTitulo = source.NombreTitulo;
            target.DescripcionTitulo = source.DescripcionTitulo;
            target.ObjetivoTitulo = source.ObjetivoTitulo;
            target.MetodologiaTitulo = source.MetodologiaTitulo;
            target.ObservacionesTitulo = source.ObservacionesTitulo;
            target.FechaCreacionTitulo = source.FechaCreacionTitulo;
            target.FechaCaducidadTitulo = source.FechaCaducidadTitulo;
            target.FechaReconocimientoTitulo = source.FechaReconocimientoTitulo;
            target.DuracionTitulo = source.DuracionTitulo;
            target.DepartamentoTituloRpg = source.DepartamentoTituloRpg;
            target.CarreraTituloRpg = source.CarreraTituloRpg;
            target.PlanTituloRpg = source.PlanTituloRpg;
            target.MinimoMateriasTitulo = source.MinimoMateriasTitulo;
            target.MinimoCreditosTitulo = source.MinimoCreditosTitulo;
            target.MinimoPacTitulo = source.MinimoPacTitulo;
            target.MaximoRevalidasTitulo = source.MaximoRevalidasTitulo;
            target.IdTipoDiploma = source.IdTipoDiploma;
            target.NombreExtenso1Titulo = source.NombreExtenso1Titulo;
            target.NombreExtenso2Titulo = source.NombreExtenso2Titulo;
            target.IdUnidadTiempo = source.IdUnidadTiempo;
            target.IdProducto = source.IdProducto;
            target.IdRequisitoPac = source.IdRequisitoPac;
            target.EstadoTitulo = source.EstadoTitulo;
            target.PlanTitulo = source.PlanTitulo;
            target.NombreExtensoMasc1Titulo = source.NombreExtensoMasc1Titulo;
            target.NombreExtensoMasc2Titulo = source.NombreExtensoMasc2Titulo;
            target.NombreExtensoFem1Titulo = source.NombreExtensoFem1Titulo;
            target.NombreExtensoFem2Titulo = source.NombreExtensoFem2Titulo;
            target.ActualizacionTitulo = source.ActualizacionTitulo;
            target.PermiteAltaPlanGuiaTitulo = source.PermiteAltaPlanGuiaTitulo;
            target.IntermedioTitulo = source.IntermedioTitulo;
            target.AnioMesPlan = source.AnioMesPlan;
            target.SePresentaMecTitulo = source.SePresentaMecTitulo;
            target.FechaPresentacionMecTitulo = source.FechaPresentacionMecTitulo;
            target.CodigoTitulo = source.CodigoTitulo;
            target.CertificadoTitulo = source.CertificadoTitulo;
            target.CantBloquesTitulo = source.CantBloquesTitulo;
            target.IdRequisitoPrevia = source.IdRequisitoPrevia;
            target.IdRequisitoPreviaAlt = source.IdRequisitoPreviaAlt;
            target.IdRequisitoPreviaOtr = source.IdRequisitoPreviaOtr;
            target.FechaUltActPrereq = source.FechaUltActPrereq;
            target.CuarentenaTitulo = source.CuarentenaTitulo;
            target.IdFamiliaTitulo = source.IdFamiliaTitulo;
            target.TipoTituloOrt = source.TipoTituloOrt;
            target.MaximoCreditosRev = source.MaximoCreditosRev;
            target.ValidadoTituloOrt = source.ValidadoTituloOrt;
            target.PreviasParcialIgualTotal = source.PreviasParcialIgualTotal;
            target.GenericoFamilia = source.GenericoFamilia;

            // Navigation Properties
            if (level > 0) {
              target.Producto = source.Producto.ToDtoWithRelated(level - 1);
              target.Titulo = source.Titulo.ToDtoWithRelated(level - 1);
              target.Paquetes = source.Paquetes.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.TituloOrt ToEntity(this DtoTituloOrtDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.TituloOrt();

            // Properties
            target.IdTitulo = source.IdTitulo;
            target.NombreTitulo = source.NombreTitulo;
            target.DescripcionTitulo = source.DescripcionTitulo;
            target.ObjetivoTitulo = source.ObjetivoTitulo;
            target.MetodologiaTitulo = source.MetodologiaTitulo;
            target.ObservacionesTitulo = source.ObservacionesTitulo;
            target.FechaCreacionTitulo = source.FechaCreacionTitulo;
            target.FechaCaducidadTitulo = source.FechaCaducidadTitulo;
            target.FechaReconocimientoTitulo = source.FechaReconocimientoTitulo;
            target.DuracionTitulo = source.DuracionTitulo;
            target.DepartamentoTituloRpg = source.DepartamentoTituloRpg;
            target.CarreraTituloRpg = source.CarreraTituloRpg;
            target.PlanTituloRpg = source.PlanTituloRpg;
            target.MinimoMateriasTitulo = source.MinimoMateriasTitulo;
            target.MinimoCreditosTitulo = source.MinimoCreditosTitulo;
            target.MinimoPacTitulo = source.MinimoPacTitulo;
            target.MaximoRevalidasTitulo = source.MaximoRevalidasTitulo;
            target.IdTipoDiploma = source.IdTipoDiploma;
            target.NombreExtenso1Titulo = source.NombreExtenso1Titulo;
            target.NombreExtenso2Titulo = source.NombreExtenso2Titulo;
            target.IdUnidadTiempo = source.IdUnidadTiempo;
            target.IdProducto = source.IdProducto;
            target.IdRequisitoPac = source.IdRequisitoPac;
            target.EstadoTitulo = source.EstadoTitulo;
            target.PlanTitulo = source.PlanTitulo;
            target.NombreExtensoMasc1Titulo = source.NombreExtensoMasc1Titulo;
            target.NombreExtensoMasc2Titulo = source.NombreExtensoMasc2Titulo;
            target.NombreExtensoFem1Titulo = source.NombreExtensoFem1Titulo;
            target.NombreExtensoFem2Titulo = source.NombreExtensoFem2Titulo;
            target.ActualizacionTitulo = source.ActualizacionTitulo;
            target.PermiteAltaPlanGuiaTitulo = source.PermiteAltaPlanGuiaTitulo;
            target.IntermedioTitulo = source.IntermedioTitulo;
            target.AnioMesPlan = source.AnioMesPlan;
            target.SePresentaMecTitulo = source.SePresentaMecTitulo;
            target.FechaPresentacionMecTitulo = source.FechaPresentacionMecTitulo;
            target.CodigoTitulo = source.CodigoTitulo;
            target.CertificadoTitulo = source.CertificadoTitulo;
            target.CantBloquesTitulo = source.CantBloquesTitulo;
            target.IdRequisitoPrevia = source.IdRequisitoPrevia;
            target.IdRequisitoPreviaAlt = source.IdRequisitoPreviaAlt;
            target.IdRequisitoPreviaOtr = source.IdRequisitoPreviaOtr;
            target.FechaUltActPrereq = source.FechaUltActPrereq;
            target.CuarentenaTitulo = source.CuarentenaTitulo;
            target.IdFamiliaTitulo = source.IdFamiliaTitulo;
            target.TipoTituloOrt = source.TipoTituloOrt;
            target.MaximoCreditosRev = source.MaximoCreditosRev;
            target.ValidadoTituloOrt = source.ValidadoTituloOrt;
            target.PreviasParcialIgualTotal = source.PreviasParcialIgualTotal;
            target.GenericoFamilia = source.GenericoFamilia;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoTituloOrtDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.TituloOrt> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoTituloOrtDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.TituloOrt> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.TituloOrt> ToEntities(this IEnumerable<DtoTituloOrtDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.TituloOrt source, DtoTituloOrtDevart target);

        static partial void OnEntityCreating(DtoTituloOrtDevart source, BusinessLogic.Entities.TituloOrt target);

    }

}
