//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class TurnoConverter
    {

        public static DtoTurnoDevart ToDto(this BusinessLogic.Entities.Turno source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoTurnoDevart ToDtoWithRelated(this BusinessLogic.Entities.Turno source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoTurnoDevart();

            // Properties
            target.IdTurno = source.IdTurno;
            target.NombreTurno = source.NombreTurno;
            target.ObservacionesTurno = source.ObservacionesTurno;
            target.CodigoRpgTurno = source.CodigoRpgTurno;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.Turno ToEntity(this DtoTurnoDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.Turno();

            // Properties
            target.IdTurno = source.IdTurno;
            target.NombreTurno = source.NombreTurno;
            target.ObservacionesTurno = source.ObservacionesTurno;
            target.CodigoRpgTurno = source.CodigoRpgTurno;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoTurnoDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.Turno> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoTurnoDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.Turno> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.Turno> ToEntities(this IEnumerable<DtoTurnoDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.Turno source, DtoTurnoDevart target);

        static partial void OnEntityCreating(DtoTurnoDevart source, BusinessLogic.Entities.Turno target);

    }

}
