//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// https://github.com/DesarrolloORT/api-fdp.git

//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

#nullable enable annotations
#nullable disable warnings

namespace AppLogic.DevartDTOs
{

    public static partial class VdEsFrescoAdmisionConverter
    {

        public static DtoVdEsFrescoAdmisionDevart ToDto(this BusinessLogic.Entities.VdEsFrescoAdmision source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static DtoVdEsFrescoAdmisionDevart ToDtoWithRelated(this BusinessLogic.Entities.VdEsFrescoAdmision source, int level)
        {
            if (source == null)
              return null;

            var target = new DtoVdEsFrescoAdmisionDevart();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.FechaInscr = source.FechaInscr;
            target.IdTurno = source.IdTurno;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaInicioComienzo = source.FechaInicioComienzo;
            target.TipoDocumento = source.TipoDocumento;
            target.Documento = source.Documento;

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static BusinessLogic.Entities.VdEsFrescoAdmision ToEntity(this DtoVdEsFrescoAdmisionDevart source)
        {
            if (source == null)
              return null;

            var target = new BusinessLogic.Entities.VdEsFrescoAdmision();

            // Properties
            target.CodigoPersona = source.CodigoPersona;
            target.FechaInscr = source.FechaInscr;
            target.IdTurno = source.IdTurno;
            target.IdProducto = source.IdProducto;
            target.IdComienzo = source.IdComienzo;
            target.FechaInicioComienzo = source.FechaInicioComienzo;
            target.TipoDocumento = source.TipoDocumento;
            target.Documento = source.Documento;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<DtoVdEsFrescoAdmisionDevart> ToDtos(this IEnumerable<BusinessLogic.Entities.VdEsFrescoAdmision> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<DtoVdEsFrescoAdmisionDevart> ToDtosWithRelated(this IEnumerable<BusinessLogic.Entities.VdEsFrescoAdmision> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<BusinessLogic.Entities.VdEsFrescoAdmision> ToEntities(this IEnumerable<DtoVdEsFrescoAdmisionDevart> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(BusinessLogic.Entities.VdEsFrescoAdmision source, DtoVdEsFrescoAdmisionDevart target);

        static partial void OnEntityCreating(DtoVdEsFrescoAdmisionDevart source, BusinessLogic.Entities.VdEsFrescoAdmision target);

    }

}
