/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoPersonaDevart } from './dtoPersonaDevart';


export interface DtoAccesoSitiosantanderDevart { 
    fechaAccesoSitiosantander: string;
    horaAccesoSitiosantander: string;
    codigoPersona: number;
    idSistema?: number | null;
    usuarioIngreso: string;
    fechaIngreso: string;
    horaIngreso: string;
    persona?: DtoPersonaDevart;
}

