/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoAceptacionReglamentoEstDevart } from './dtoAceptacionReglamentoEstDevart';


export interface DtoAceptacionReglamentoEstDevartOperationResult { 
    success?: boolean;
    httpCode?: number;
    errorCode?: string | null;
    method?: string | null;
    message?: string | null;
    data: DtoAceptacionReglamentoEstDevart;
}

