/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoEstadoDevart } from './dtoEstadoDevart';
import { DtoSolicitudAltaDevart } from './dtoSolicitudAltaDevart';
import { DtoEmpresaDevart } from './dtoEmpresaDevart';
import { DtoPersonaDevart } from './dtoPersonaDevart';


export interface DtoCiudadDevart { 
    codigoPais: number;
    codigoEstado: number;
    codigoCiudad: number;
    nombre: string;
    dgiCiudad?: string | null;
    empresas?: Array<DtoEmpresaDevart> | null;
    estado?: DtoEstadoDevart;
    personas?: Array<DtoPersonaDevart> | null;
    solicitudAltas?: Array<DtoSolicitudAltaDevart> | null;
}

