/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoEncuestaIniAdmisionDevart } from './dtoEncuestaIniAdmisionDevart';


export interface DtoEncuestaIniAdmisionDevartOperationResult { 
    success?: boolean;
    httpCode?: number;
    errorCode?: string | null;
    method?: string | null;
    message?: string | null;
    data: DtoEncuestaIniAdmisionDevart;
}

