/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoTipoEgresoDjDevart } from './dtoTipoEgresoDjDevart';
import { DtoDeclaracionJuradaWebDevart } from './dtoDeclaracionJuradaWebDevart';


export interface DtoEgresoMensualNfDjDevart { 
    idEgresoMensualNfDj: number;
    idTipoEgresoDj: number;
    montoEgresoMensualNfDj?: number | null;
    archivoEgresoMensualNfDj?: string | null;
    idDeclaracionjuradaWeb: number;
    detalleOtroEgreso?: string | null;
    idEgresoFront?: string | null;
    extensionArchivoEgreso?: string | null;
    nombreArchivoEgreso?: string | null;
    fechaIngreso?: string | null;
    horaIngreso?: string | null;
    usuarioIngreso?: string | null;
    tipoEgresoDj?: DtoTipoEgresoDjDevart;
    declaracionJuradaWeb?: DtoDeclaracionJuradaWebDevart;
}

