/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoIntereDevart } from './dtoIntereDevart';
import { DtoSolicitudAltaDevart } from './dtoSolicitudAltaDevart';
import { DtoActividadDevart } from './dtoActividadDevart';
import { DtoEncuestaIniAdmisionDevart } from './dtoEncuestaIniAdmisionDevart';


export interface DtoProcesoDevart { 
    idProceso: number;
    estadoProceso?: string | null;
    fechaFinProceso?: string | null;
    idTipoProceso?: number | null;
    observacionesProceso?: string | null;
    nombreProceso: string;
    zafid?: number | null;
    marcadoParawebProceso?: string | null;
    nroMesParawebProceso?: number | null;
    nroAnioParawebProceso?: number | null;
    comienzoSemestre1Proceso?: string | null;
    anticipada40porcientoProceso?: string | null;
    anticipada20porcientoProceso?: string | null;
    inicioPeriodoProceso?: string | null;
    finPeriodoProceso?: string | null;
    habilitadoInteresSitio?: string | null;
    anticipada50porcientoProceso?: string | null;
    anticipada60porcientoProceso?: string | null;
    anticipada30porcientoProceso?: string | null;
    anticipada70porcientoProceso?: string | null;
    encuestaIniAdmisions?: Array<DtoEncuestaIniAdmisionDevart> | null;
    solicitudAltas?: Array<DtoSolicitudAltaDevart> | null;
    intere?: DtoIntereDevart;
    actividads?: Array<DtoActividadDevart> | null;
}

