/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoEstadoDevart } from './dtoEstadoDevart';


export interface DtoPaisDevart { 
    codigoPais: number;
    nombre: string;
    dgiPais?: string | null;
    estado?: Array<DtoEstadoDevart> | null;
}

