/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DtoNivelProductoDevart } from './dtoNivelProductoDevart';
import { DtoTipoDescuentoDevart } from './dtoTipoDescuentoDevart';


export interface DtoTipoBecaNivelProductoDevart { 
    idTipoBeca: number;
    idNivelProducto: number;
    usuarioIngreso: string;
    fechaIngreso: string;
    horaIngreso: string;
    habilitadoSitioOrt?: string | null;
    tipoDescuento?: DtoTipoDescuentoDevart;
    nivelProducto?: DtoNivelProductoDevart;
}

