/**
 * WebApiAdmisiones
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MotivoEncuestaRequest } from './motivoEncuestaRequest';
import { EmpresaEncuestaRequest } from './empresaEncuestaRequest';
import { PublicidadEncuestaRequest } from './publicidadEncuestaRequest';


export interface GuardarDatosPersonaEncuestaRequest { 
    primerApellido?: string | null;
    segundoApellido?: string | null;
    primerNombre?: string | null;
    segundoNombre?: string | null;
    mail?: string | null;
    verificacionMail?: string | null;
    direccion?: string | null;
    sexo?: string | null;
    fechaNacimiento?: string;
    trabajaActualmente?: string | null;
    tipoJornada?: number;
    telefono1?: string | null;
    telefono2?: string | null;
    codigoPais?: number;
    codigoEstado?: number;
    codigoCiudad?: number;
    documento?: string | null;
    tipoDocumento?: string | null;
    idProducto?: number;
    idProceso?: number;
    codigoTitulo?: number | null;
    ultimoAnioSexto?: number;
    vecesSexto?: number;
    vecesSextoBool?: boolean;
    instruccionPadre?: number;
    instruccionMadre?: number;
    decisionCarrera?: number | null;
    decisionUniversidad?: number | null;
    infoOtrasUniversidadesAntes?: string | null;
    infoOtrasLinea1?: string | null;
    infoOtrasLinea2?: string | null;
    compartidoCon?: number;
    codigoInstitucionBac?: number | null;
    informarEncuesta?: string | null;
    nombreInstitucion?: string | null;
    ultimoAnioSecundaria?: number;
    tieneEducacionSuperior?: boolean | null;
    nivelDecision?: number;
    asesoramientoOrt?: boolean | null;
    valoracionAsesoramientoOrt?: number;
    vistaSitioWebOrt?: boolean | null;
    valoracionSitioWeb?: number;
    vistaInstalacionesOrt?: boolean | null;
    valoracionInstalacionesOrt?: number;
    publicidadOrt?: boolean | null;
    instruccionMadreOrt?: boolean | null;
    instruccionPadreOrt?: boolean | null;
    universidadesConsideradas?: Array<EmpresaEncuestaRequest> | null;
    universidadesEducacionSuperior?: Array<EmpresaEncuestaRequest> | null;
    opcionesPublicidadSeleccionadas?: Array<PublicidadEncuestaRequest> | null;
    opcionesMotivosSeleccionados?: Array<MotivoEncuestaRequest> | null;
}

