//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:12:12
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;

namespace BusinessLogic.Entities
{
    public partial class CausalInscrPagoRepository : EntityFrameworkRepository<CausalInscrPago>, ICausalInscrPagoRepository
    {
        public CausalInscrPagoRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<CausalInscrPago> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual CausalInscrPago GetByKey(long _IdCausalInscrPago)
        {
            return objectSet.SingleOrDefault(e => e.IdCausalInscrPago == _IdCausalInscrPago);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
