//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 29/06/2026 14:04:22
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class CiudadRepository : EntityFrameworkRepository<BusinessLogic.Entities.Ciudad>, ICiudadRepository
    {
        public CiudadRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Ciudad> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Ciudad GetByKey(long _CodigoPais, long _CodigoEstado, long _CodigoCiudad)
        {
            return objectSet.SingleOrDefault(e => e.CodigoPais == _CodigoPais && e.CodigoEstado == _CodigoEstado && e.CodigoCiudad == _CodigoCiudad);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
