//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 24/06/2026 11:03:51
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class DeclaracionJuradaWebRepository : EntityFrameworkRepository<BusinessLogic.Entities.DeclaracionJuradaWeb>, IDeclaracionJuradaWebRepository
    {
        public DeclaracionJuradaWebRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.DeclaracionJuradaWeb> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.DeclaracionJuradaWeb GetByKey(decimal _IdDeclaracionjuradaWeb)
        {
            return objectSet.SingleOrDefault(e => e.IdDeclaracionjuradaWeb == _IdDeclaracionjuradaWeb);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
