//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class DeclaracionJuradaWebRepository
    {
        /// <summary>
        /// Devuelve la fecha de entrega de DJ de la prueba activa de admisiones del alumno,
        /// donde dicha fecha aún no ha pasado (>= hoy). Retorna null si no existe.
        /// </summary>
        public virtual DateTime? GetFechaEntregaDjAdmisiones(long codigoPersona)
        {
            var hoy = DateTime.Today;
            return (
                from d in objectSet
                join ip in Context.Set<BusinessLogic.Entities.InscriptoPrueba>()
                    on d.IdInscriptoPrueba equals (decimal)ip.IdInscriptoPrueba
                join p in Context.Set<BusinessLogic.Entities.Prueba>()
                    on ip.IdPrueba equals p.IdPrueba
                where d.CodigoPersona == codigoPersona
                   && p.FechaEntregaDjPrueba.HasValue
                   && p.FechaEntregaDjPrueba.Value.Date >= hoy
                orderby d.IdDeclaracionjuradaWeb descending
                select p.FechaEntregaDjPrueba
            ).FirstOrDefault();
        }
    }
}
