//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 23/06/2026 11:41:45
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class EmpresaRepository : EntityFrameworkRepository<BusinessLogic.Entities.Empresa>, IEmpresaRepository
    {
        public EmpresaRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Empresa> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Empresa GetByKey(long _CodigoEmpresa)
        {
            return objectSet.SingleOrDefault(e => e.CodigoEmpresa == _CodigoEmpresa);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
