//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 24/06/2026 16:28:43
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using ConnectionContext;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class EntityFrameworkUnitOfWorkFactory : IUnitOfWorkFactory
    {
        private readonly DbContext _ef;
        private readonly DbConnectionContext _db;

        public EntityFrameworkUnitOfWorkFactory(DataAccess.ModelContext ef, DbConnectionContext db)
        {
            _ef = ef ?? throw new ArgumentNullException(nameof(ef));
            _db = db ?? throw new ArgumentNullException(nameof(db));
        }

        public IUnitOfWork Create()
        {
            if (_db.Transaction != null)
            {
                _ef.Database.UseTransaction(_db.Transaction);
            }
            return new EntityFrameworkUnitOfWork(_ef, _db);
        }
    }
}
