//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 22/06/2026 13:59:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class EntityFrameworkRepository<T> : IRepository<T> where T : class
    {
        private DbContext context;
        protected DbSet<T> objectSet;

        public EntityFrameworkRepository(DbContext context)
        {

            if (context == null)
            {
                throw new ArgumentNullException("context");
            }

            this.context = context;
            this.objectSet = context.Set<T>();
        }

        public virtual void Add(T entity)
        {

            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }
            objectSet.Add(entity);
        }

        public virtual void Remove(T entity)
        {

            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }
            objectSet.Remove(entity);
        }

        public void Update(T entity)
        {
            if (entity == null)
            {
                throw new ArgumentNullException("entity");
            }
            objectSet.Update(entity);
        }

        public int NextId(string nombreSecuencia)
        {
            // 1) Obtengo la conexión subyacente y la abro si hace falta
            var conn = context.Database.GetDbConnection();
            if (conn.State != ConnectionState.Open)
                conn.Open();

            // 2) Creo el comando
            using var command = conn.CreateCommand();
            command.CommandText = $"SELECT {nombreSecuencia}.NEXTVAL FROM DUAL";

            // 3) Si hay transacción EF activa, la enlazo
            var currentTx = context.Database.CurrentTransaction;
            if (currentTx != null)
                command.Transaction = currentTx.GetDbTransaction();

            // 4) Ejecuto y convierto el scalar al tipo deseado
            var result = command.ExecuteScalar();
            return Convert.ToInt32(result);
        }

        public DbContext Context 
        {
            get
            {
                return context;
            }
        }
    }
}
