//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 25/06/2026 15:19:13
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class ImagenTemporalRepository : EntityFrameworkRepository<BusinessLogic.Entities.ImagenTemporal>, IImagenTemporalRepository
    {
        public ImagenTemporalRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.ImagenTemporal> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.ImagenTemporal GetByKey(long _IdImagenTemporal)
        {
            return objectSet.SingleOrDefault(e => e.IdImagenTemporal == _IdImagenTemporal);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
