//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.Entities;

namespace DataAccess.DevartRepositories
{
    public partial class ImagenRepository
    {
        public Imagen? GetFotoByPersona(long codigoPersona)
        {
            return Context.Set<Imagen>()
                .FirstOrDefault(i => i.CodigoPersona == codigoPersona
                                  && i.TipoImagen == "3");
        }
    }
}
