//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 17/03/2026 16:41:52
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class IngresoMensualNfDjRepository
    {
        public BusinessLogic.Entities.IngresoMensualNfDj? GetWithIntegranteYDeclaracion(decimal idIngresoMensualNfDj)
        {
            return objectSet
                .Include(i => i.IntegranteNfDj)
                .ThenInclude(integrante => integrante.DeclaracionJuradaWeb)
                .SingleOrDefault(i => i.IdIngresoMensualNfDj == idIngresoMensualNfDj);
        }
    }
}
