//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class InstanciaWorkflowRepository
    {
        /// <summary>
        /// Inscripciones en curso (sin fecha final ni cancelación) de la persona,
        /// para los procesos de inscripción de alumnos frescos (75 y 82).
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.InstanciaWorkflow> GetInscripcionesPendientes(long codigoPersona)
        {
            return objectSet
                .Where(iw =>
                    (iw.IdProceso == 75 || iw.IdProceso == 82)
                    && iw.SolicitanteInstanciaWorkflow == codigoPersona
                    && iw.FechaCanceladoInstanciaWf == null
                    && iw.FechaFinalInstanciaWf == null)
                .ToList();
        }

        /// <summary>
        /// Inscripciones canceladas (con fecha de cancelación) de la persona,
        /// para los procesos de inscripción de alumnos frescos (75 y 82).
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.InstanciaWorkflow> GetInscripcionesCanceladas(long codigoPersona)
        {
            return objectSet
                .Where(iw =>
                    (iw.IdProceso == 75 || iw.IdProceso == 82)
                    && iw.IdObjetoInstanciaWorkflow == (decimal?)codigoPersona
                    && iw.FechaCanceladoInstanciaWf != null)
                .ToList();
        }

        public virtual bool TieneInscripcionPendienteParaProducto(long codigoPersona, long idProducto)
        {
            return
            (
                from instancia in objectSet
                join inscripcion in Context.Set<BusinessLogic.Entities.InstWorkflowInscripcion>()
                    on instancia.IdInstanciaWorkflow equals inscripcion.IdInstanciaWorkflow
                where (instancia.IdProceso == 75 || instancia.IdProceso == 82)
                      && instancia.IdObjetoInstanciaWorkflow == (decimal?)codigoPersona
                      && instancia.FechaCanceladoInstanciaWf == null
                      && instancia.FechaFinalInstanciaWf == null
                      && inscripcion.IdProducto == (decimal?)idProducto
                select instancia.IdInstanciaWorkflow
            ).Count() > 0;
        }
    }
}
