//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class InstWorkflowInscripcionRepository
    {
        /// <summary>
        /// Devuelve los registros de InstWorkflowInscripcion para los IDs de instancia dados.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.InstWorkflowInscripcion> GetByInstanciaIds(IEnumerable<decimal> ids)
        {
            return objectSet
                .Where(iwi => ids.Contains(iwi.IdInstanciaWorkflow))
                .ToList();
        }
    }
}
