//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class InstanciaWorkflowRepository
    {
        public virtual bool TieneInscripcionPendienteParaProducto(long codigoPersona, long idProducto)
        {
            return
            (
                from instancia in objectSet
                join inscripcion in Context.Set<BusinessLogic.Entities.InstWorkflowInscripcion>()
                    on instancia.IdInstanciaWorkflow equals inscripcion.IdInstanciaWorkflow
                where (instancia.IdProceso == 75 || instancia.IdProceso == 89)
                      && instancia.IdObjetoInstanciaWorkflow == (decimal?)codigoPersona
                      && instancia.FechaCanceladoInstanciaWf == null
                      && instancia.FechaFinalInstanciaWf == null
                      && inscripcion.IdProducto == (decimal?)idProducto
                select instancia.IdInstanciaWorkflow
            ).Count() > 0;
        }
    }
}
