//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 17/06/2026 15:50:19
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class LocalidadRepository : EntityFrameworkRepository<BusinessLogic.Entities.Localidad>, ILocalidadRepository
    {
        public LocalidadRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Localidad> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Localidad GetByKey(long _IdLocalidad)
        {
            return objectSet.SingleOrDefault(e => e.IdLocalidad == _IdLocalidad);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
