//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 12/03/2026 15:16:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class MotivoOpcionesAdmisionRepository : EntityFrameworkRepository<BusinessLogic.Entities.MotivoOpcionesAdmision>, IMotivoOpcionesAdmisionRepository
    {
        public MotivoOpcionesAdmisionRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.MotivoOpcionesAdmision> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.MotivoOpcionesAdmision GetByKey(long _IdMotivo)
        {
            return objectSet.SingleOrDefault(e => e.IdMotivo == _IdMotivo);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
