//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 30/06/2026 14:16:40
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class OfertaCreditoMateriaRepository : EntityFrameworkRepository<BusinessLogic.Entities.OfertaCreditoMateria>, IOfertaCreditoMateriaRepository
    {
        public OfertaCreditoMateriaRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.OfertaCreditoMateria> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.OfertaCreditoMateria GetByKey(long _IdOfertaCredito, long _IdMateria)
        {
            return objectSet.SingleOrDefault(e => e.IdOfertaCredito == _IdOfertaCredito && e.IdMateria == _IdMateria);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
