//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class OfertaRepository
    {
        public virtual BusinessLogic.Entities.Oferta GetByKeyWithRelated(long idOferta)
        {
            return objectSet
                .Include(o => o.Turno)
                .Include(o => o.Supraoferta)
                    .ThenInclude(s => s.Paquete)
                        .ThenInclude(p => p.Producto)
                .Include(o => o.Supraoferta)
                    .ThenInclude(s => s.Comienzo)
                .FirstOrDefault(o => o.IdOferta == idOferta);
        }

        /// <summary>
        /// Materias de la oferta (T_OFERTA_CREDITO -> T_OFERTA_CREDITO_MATERIA -> T_MATERIA).
        /// Para una inscripción fresca, la oferta es la del primer semestre, así que estas son
        /// las materias a cursar en ese semestre.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Materia> GetMateriasPorOferta(long idOferta)
        {
            return objectSet
                .AsNoTracking()
                .Where(o => o.IdOferta == idOferta)
                .SelectMany(o => o.OfertaCreditos)
                .SelectMany(oc => oc.OfertaCreditoMaterias)
                .Select(ocm => ocm.Materia)
                .Distinct()
                .ToList();
        }
    }
}
