//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// https://github.com/DesarrolloORT/back-template.git
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class PaisRepository
    {
        public virtual ICollection<BusinessLogic.Entities.Pais> GetPaisesConEstadosYCiudades()
        {
            var paises = objectSet
                .Include(p => p.Estado)
                .ThenInclude(e => e.Ciudad)
                .OrderBy(p => p.CodigoPais == 1 ? 0 : 1)
                .ThenBy(p => p.Nombre)
                .ToList();

            foreach (var pais in paises)
            {
                if (pais.Estado == null)
                {
                    continue;
                }

                pais.Estado = pais.Estado.OrderBy(e => e.Nombre).ToList();
                foreach (var estado in pais.Estado)
                {
                    if (estado.Ciudad != null)
                    {
                        estado.Ciudad = estado.Ciudad.OrderBy(c => c.Nombre).ToList();
                    }
                }
            }

            return paises;
        }

        public virtual BusinessLogic.Entities.Pais GetPaisConEstadosYCiudades(long codigoPais)
        {
            return objectSet
                .Include(p => p.Estado)
                .ThenInclude(e => e.Ciudad)
                .FirstOrDefault(p => p.CodigoPais == codigoPais);
        }
    }
}
