//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// https://github.com/DesarrolloORT/back-template.git
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class PaisRepository
    {
        public virtual ICollection<BusinessLogic.Entities.Pais> GetPaisesOrdenados()
        {
            return objectSet
                .OrderBy(p => p.CodigoPais == 1 ? 0 : 1)
                .ThenBy(p => p.Nombre)
                .ToList();
        }

        public virtual BusinessLogic.Entities.Pais GetPaisConEstadosYCiudades(long codigoPais)
        {
            return objectSet
                .Include(p => p.Estado)
                .ThenInclude(e => e.Ciudad)
                .FirstOrDefault(p => p.CodigoPais == codigoPais);
        }
    }
}
