//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/07/2026 11:47:40
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class PaqueteRepository : EntityFrameworkRepository<BusinessLogic.Entities.Paquete>, IPaqueteRepository
    {
        public PaqueteRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Paquete> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Paquete GetByKey(long _IdPaquete)
        {
            return objectSet.SingleOrDefault(e => e.IdPaquete == _IdPaquete);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
