//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 28/07/2026 16:32:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class ProcesoComienzoRepository : EntityFrameworkRepository<BusinessLogic.Entities.ProcesoComienzo>, IProcesoComienzoRepository
    {
        public ProcesoComienzoRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.ProcesoComienzo> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.ProcesoComienzo GetByKey(long _IdProceso, long _IdComienzo)
        {
            return objectSet.SingleOrDefault(e => e.IdProceso == _IdProceso && e.IdComienzo == _IdComienzo);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
