//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class ProductoRepository
    {
        /// <summary>
        /// Devuelve los productos en los que una persona tiene registrado algún interés.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Producto> GetProductosConInteres(long codigoPersona)
        {
            var today = DateTime.Today;
            return objectSet
                .Where(p =>
                    p.VisibleAdmisionesProducto == "SI"
                    && p.InscribibleProducto == "SI"
                    && p.PermiteInteresadoProducto == "SI"
                    && p.ActivoWebProducto == "SI"
                    && (p.FechaCaducidadProducto == null || p.FechaCaducidadProducto >= today)
                    && p.ProcesoProductos.Any(pp => pp.Proceso.HabilitadoInteresSitio == "SI")
                    && !p.Inscriptos_IdProductoReal.Any(i =>
                        i.CodigoPersona == codigoPersona && i.BajaInscr == null)
                    && p.InteresProductos.Any(ip =>
                        ip.Intere != null
                        && ip.Intere.CodigoPersona == codigoPersona
                        && ip.IdGradoInteres != 5
                        && ip.Intere.Proceso.HabilitadoInteresSitio == "SI"))
                .Include(p => p.ProcesoProductos)
                    .ThenInclude(pp => pp.Proceso)
                .ToList();
        }

        /// <summary>
        /// Devuelve los productos en los que la persona tiene interés pero aún no tiene inscripción activa.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Producto> GetProductoInteresPersona(long codigoPersona)
        {
            var today = DateTime.Today;
            return objectSet
                .Where(p =>
                    p.VisibleAdmisionesProducto == "SI"
                    && p.InscribibleProducto == "SI"
                    && p.PermiteInteresadoProducto == "SI"
                    && p.ActivoWebProducto == "SI"
                    && (p.FechaCaducidadProducto == null || p.FechaCaducidadProducto >= today)
                    && p.ProcesoProductos.Any(pp => pp.Proceso.HabilitadoInteresSitio == "SI")
                    && !p.Inscriptos_IdProductoReal.Any(i =>
                        i.CodigoPersona == codigoPersona && i.BajaInscr == null)
                    && p.InteresProductos.Any(ip =>
                        ip.Intere != null
                        && ip.Intere.CodigoPersona == codigoPersona
                        && ip.IdGradoInteres != 5
                        && ip.Intere.Proceso.HabilitadoInteresSitio == "SI"))
                .Include(p => p.ProcesoProductos)
                    .ThenInclude(pp => pp.Proceso)
                .ToList();
        }
    }
}
