//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class ProductoRepository
    {
        /// <summary>
        /// Devuelve los productos vigentes con oferta abierta en los que la persona tiene interés,
        /// sin inscripción activa y excluyendo interés grado 5 solo si la persona es fresca en ese producto
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Producto> GetProductosVigentesConInteres(long codigoPersona)
        {
            var today = DateTime.Today;

            // 1. Comienzos válidos: proceso habilitado + producto nivel 1 o 2.
            var comienzoIds = Context.Set<BusinessLogic.Entities.ProcesoComienzo>()
                .Where(pc =>
                    pc.Proceso.HabilitadoInteresSitio == "SI"
                    && pc.Proceso.ProcesoProductos.Any(pp =>
                        pp.Producto.IdNivelProducto == 1 || pp.Producto.IdNivelProducto == 2))
                .Select(pc => pc.IdComienzo)
                .Distinct()
                .ToList();

            // 2. Productos con inscripción activa (sin baja) para la persona.
            var productosInscriptos = Context.Set<BusinessLogic.Entities.Inscripto>()
                .Where(i => i.CodigoPersona == codigoPersona && i.BajaInscr == null && i.IdProductoReal.HasValue)
                .Select(i => i.IdProductoReal!.Value)
                .Distinct()
                .ToList();

            // 3. Productos con interés grado 5 en proceso marcado para web y habilitado.
            var productosGrado5 = Context.Set<BusinessLogic.Entities.InteresProducto>()
                .Where(ip =>
                    ip.IdGradoInteres == 5m
                    && ip.Intere.CodigoPersona == codigoPersona
                    && ip.Intere.Proceso.MarcadoParawebProceso == "SI"
                    && ip.Intere.Proceso.HabilitadoInteresSitio == "SI")
                .Select(ip => ip.IdProducto)
                .Distinct()
                .ToList();

            // 4. Productos donde la persona es "fresca".
            var frescoProductoIds = Context.Set<BusinessLogic.Entities.VdFrescoProductoAdmisione>()
                .Where(vd => vd.CodigoPersona == (long?)codigoPersona && vd.IdProducto.HasValue)
                .Select(vd => vd.IdProducto!.Value)
                .Distinct()
                .ToList();

            // 5. Excluir solo los grado 5 que también son frescos (intersección).
            var productosGrado5Frescos = productosGrado5.Intersect(frescoProductoIds).ToList();

            return objectSet
                .Where(p =>
                    p.VisibleAdmisionesProducto == "SI"
                    && p.InscribibleProducto == "SI"
                    && p.PermiteInteresadoProducto == "SI"
                    && p.ActivoWebProducto == "SI"
                    && (p.FechaCaducidadProducto == null || p.FechaCaducidadProducto >= today)
                    // Tiene proceso habilitado
                    && p.ProcesoProductos.Any(pp => pp.Proceso.HabilitadoInteresSitio == "SI")
                    // Tiene oferta abierta con semestre != 99 y comienzo en proceso habilitado
                    && p.Paquetes.Any(pk =>
                        pk.SemestrePaquete != 99
                        && pk.Supraofertas.Any(so =>
                            comienzoIds.Contains(so.IdComienzo)
                            && so.Ofertas.Any(o => o.InscripcionesAbiertasOferta == "SI")))
                    // Sin inscripción activa
                    && !productosInscriptos.Contains(p.IdProducto)
                    // Sin interés grado 5 fresco
                    && !productosGrado5Frescos.Contains(p.IdProducto))
                .Include(p => p.ProcesoProductos)
                    .ThenInclude(pp => pp.Proceso)
                .Include(p => p.NivelProducto)
                .ToList();
        }

        /// <summary>
        /// Devuelve los productos en los que la persona tiene interés registrado y no tiene
        /// una inscripción pendiente en el workflow (sin baja ni finalización).
        /// No excluye productos con inscripción activa en T_INSCRIPTO.
        /// Excluye interés de grado 5 de forma simple (sin condiciones adicionales de proceso o VD_FRESCO).
        /// Equivalente al filtro: setWhereConsultaProcesoVigenteInteresadoSinInscripciones (LogicaORT).
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Producto> GetProductosConInteresActivo(long codigoPersona)
        {
            var today = DateTime.Today;

            // Comienzos válidos: proceso habilitado + producto nivel 1 o 2.
            var comienzoIds = Context.Set<BusinessLogic.Entities.ProcesoComienzo>()
                .Where(pc =>
                    pc.Proceso.HabilitadoInteresSitio == "SI"
                    && pc.Proceso.ProcesoProductos.Any(pp =>
                        pp.Producto.IdNivelProducto == 1 || pp.Producto.IdNivelProducto == 2))
                .Select(pc => pc.IdComienzo)
                .Distinct()
                .ToList();

            return objectSet
                .Where(p =>
                    p.VisibleAdmisionesProducto == "SI"
                    && p.InscribibleProducto == "SI"
                    && p.PermiteInteresadoProducto == "SI"
                    && p.ActivoWebProducto == "SI"
                    && (p.FechaCaducidadProducto == null || p.FechaCaducidadProducto >= today)
                    && p.ProcesoProductos.Any(pp => pp.Proceso.HabilitadoInteresSitio == "SI")
                    // Tiene oferta abierta con semestre != 99 y comienzo en proceso habilitado con nivel 1 o 2
                    && p.Paquetes.Any(pk =>
                        pk.SemestrePaquete != 99
                        && pk.Supraofertas.Any(so =>
                            comienzoIds.Contains(so.IdComienzo)
                            && so.Ofertas.Any(o => o.InscripcionesAbiertasOferta == "SI")))
                    // Excluye productos que ya tienen una inscripción pendiente en el workflow para esta persona
                    && !Context.Set<BusinessLogic.Entities.InstWorkflowInscripcion>().Any(iwi =>
                        iwi.IdProducto == (decimal?)p.IdProducto
                        && Context.Set<BusinessLogic.Entities.InstanciaWorkflow>().Any(iw =>
                            iw.IdInstanciaWorkflow == iwi.IdInstanciaWorkflow
                            && iw.IdObjetoInstanciaWorkflow == (decimal?)codigoPersona
                            && iw.FechaCanceladoInstanciaWf == null
                            && iw.FechaFinalInstanciaWf == null))
                    // Excluye interés grado 5 para la persona (simple, sin condiciones adicionales)
                    && !p.InteresProductos.Any(ip =>
                        ip.Intere != null
                        && ip.Intere.CodigoPersona == codigoPersona
                        && ip.IdGradoInteres == 5m)
                    // La persona tiene al menos un interés activo (grado != 0, grado != 5) en proceso habilitado
                    && p.InteresProductos.Any(ip =>
                        ip.Intere != null
                        && ip.Intere.CodigoPersona == codigoPersona
                        && ip.IdGradoInteres != 0m
                        && ip.IdGradoInteres != 5m
                        && ip.Intere.Proceso.HabilitadoInteresSitio == "SI"))
                .Include(p => p.ProcesoProductos)
                    .ThenInclude(pp => pp.Proceso)
                .Include(p => p.NivelProducto)
                .ToList();
        }
    }
}
