//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 02/03/2026 12:08:20
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.DevartRepositories
{
    public partial class PruebaRepository
    {
        /// <summary>
        /// Devuelve las pruebas (fondos de beca) habilitadas para el sitio de admisiones
        /// cuyo comienzo está vinculado al proceso indicado.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.Prueba> GetPruebasVigentesParaAdmisiones(long idProceso)
        {
            return objectSet
                .Where(p => p.HabilitadoSitioadmiPrueba == "SI"
                         && p.Comienzo.ProcesoComienzos
                                .Any(pc => pc.IdProceso == idProceso))
                .Include(p => p.TipoDescuento)
                .Include(p => p.Comienzo)
                .ToList();
        }
    }
}
