//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 19/05/2026 16:19:46
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class RefreshTokenRepository : EntityFrameworkRepository<BusinessLogic.Entities.RefreshToken>, IRefreshTokenRepository
    {
        public RefreshTokenRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.RefreshToken> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.RefreshToken GetByKey(long _CodigoPersona, string _Sistema)
        {
            return objectSet.SingleOrDefault(e => e.CodigoPersona == _CodigoPersona && e.Sistema == _Sistema);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
