//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 11/06/2026 8:53:30
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class RegistroAdmisioneRepository : EntityFrameworkRepository<BusinessLogic.Entities.RegistroAdmisione>, IRegistroAdmisioneRepository
    {
        public RegistroAdmisioneRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.RegistroAdmisione> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.RegistroAdmisione GetByKey(long _IdRegistroAdmisiones)
        {
            return objectSet.SingleOrDefault(e => e.IdRegistroAdmisiones == _IdRegistroAdmisiones);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
