//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 12/06/2026 13:55:25
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class TipoViviendaRepository : EntityFrameworkRepository<BusinessLogic.Entities.TipoVivienda>, ITipoViviendaRepository
    {
        public TipoViviendaRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.TipoVivienda> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.TipoVivienda GetByKey(decimal _IdTipoVivienda)
        {
            return objectSet.SingleOrDefault(e => e.IdTipoVivienda == _IdTipoVivienda);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
