//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 25/05/2026 16:54:44
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class TituloRepository : EntityFrameworkRepository<BusinessLogic.Entities.Titulo>, ITituloRepository
    {
        public TituloRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Titulo> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Titulo GetByKey(long _CodigoTitulo)
        {
            return objectSet.SingleOrDefault(e => e.CodigoTitulo == _CodigoTitulo);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
