//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 22/06/2026 13:59:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class TurnoRepository : EntityFrameworkRepository<BusinessLogic.Entities.Turno>, ITurnoRepository
    {
        public TurnoRepository(DataAccess.ModelContext context)
            : base(context)
        {
        }

        public virtual ICollection<BusinessLogic.Entities.Turno> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual BusinessLogic.Entities.Turno GetByKey(long _IdTurno)
        {
            return objectSet.SingleOrDefault(e => e.IdTurno == _IdTurno);
        }

        public new DataAccess.ModelContext Context 
        {
            get
            {
                return (DataAccess.ModelContext)base.Context;
            }
        }
    }
}
