//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 19/06/2026 14:19:37
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class VdInscripcionesFresco3y4Repository
    {
        public virtual ICollection<BusinessLogic.Entities.VdInscripcionesFresco3y4> GetInscripcionesFrescoHabilitadas(long codigoPersona)
        {
            var parametros = Context.ParametrosAdmisiones
                .Select(p => new
                {
                    DiasExtraPermiteInscr3 = p.DiasExtraPermiteInscr3 ?? 0,
                    DiasExtraPermiteInscr4 = p.DiasExtraPermiteInscr4 ?? 0
                })
                .FirstOrDefault();

            var diasExtra3 = (double)(parametros?.DiasExtraPermiteInscr3 ?? 0);
            var diasExtra4 = (double)(parametros?.DiasExtraPermiteInscr4 ?? 0);
            var fechaLimiteNivel3 = DateTime.Today.AddDays(-diasExtra3);
            var fechaLimiteNivel4 = DateTime.Today.AddDays(-diasExtra4);
            var fechaLimiteDefault = DateTime.Today;

            return objectSet
                .Where(x => x.CodigoPersona == (decimal)codigoPersona
                    && ((x.IdNivelProducto == 3 && x.FechaReferencia >= fechaLimiteNivel3)
                        || (x.IdNivelProducto == 4 && x.FechaReferencia >= fechaLimiteNivel4)
                        || (x.IdNivelProducto != 3 && x.IdNivelProducto != 4 && x.FechaReferencia >= fechaLimiteDefault)))
                .ToList();
        }
    }
}
