//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 11/06/2026 9:46:56
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class VdInscripcionesFresco1y2Repository
    {
        public virtual ICollection<BusinessLogic.Entities.VdInscripcionesFresco1y2> GetInscripcionesFrescoHabilitadas(long codigoPersona)
        {
            var diasExtra = (double)(Context.ParametrosAdmisiones
                .Select(p => p.DiasExtraPermiteInscr1y2 ?? 0)
                .FirstOrDefault());

            var fechaLimite = DateTime.Today.AddDays(-diasExtra);

            return objectSet
                .Where(x => x.CodigoPersona == (decimal)codigoPersona
                    && x.FechaReferencia >= fechaLimite)
                .ToList();
        }

        public virtual BusinessLogic.Entities.VdInscripcionesFresco1y2? GetInscripcionFrescoHabilitada(long codigoPersona, long idProducto, long idProceso)
        {
            var diasExtra = (double)(Context.ParametrosAdmisiones
                .Select(p => p.DiasExtraPermiteInscr1y2 ?? 0)
                .FirstOrDefault());

            var fechaLimite = DateTime.Today.AddDays(-diasExtra);

            return objectSet
                .Where(x => x.CodigoPersona == (decimal)codigoPersona
                    && x.FechaReferencia >= fechaLimite
                    && x.IdProducto == (decimal)idProducto
                    && x.IdProceso == (decimal)idProceso)
                .FirstOrDefault();
        }
    }
}
