//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 22/06/2026 13:59:49
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using BusinessLogic.IDevartRepositories;

namespace DataAccess.DevartRepositories
{
    public partial class VdOfertasDisponibles3y4Repository
    {
        /// <summary>
        /// Ofertas del producto. No excluye nada por persona: se usa para resolver descripciones de
        /// ofertas ya elegidas, donde filtrar por inscripciones frescas las dejaria afuera.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.VdOfertasDisponibles3y4> GetOfertasDisponibles(long idProducto)
        {
            return SoloPrimerSeminario()
                .Where(x => x.IdProducto == idProducto)
                .OrderBy(x => x.FechaReferencia)
                .ThenBy(x => x.DescripcionOferta)
                .ToList();
        }

        /// <summary>
        /// Ofertas del producto que la persona todavia puede elegir: excluye las ofertas en las que
        /// ya tiene una inscripcion fresca de nivel 3 o 4 dentro de la ventana vigente.
        /// </summary>
        public virtual ICollection<BusinessLogic.Entities.VdOfertasDisponibles3y4> GetOfertasDisponibles(long idProducto, long codigoPersona)
        {
            var parametros = ParametrosAdmisionesCache.Get(Context);

            var fechaLimiteNivel3 = DateTime.Today.AddDays(-(double)parametros.DiasExtra3);
            var fechaLimiteNivel4 = DateTime.Today.AddDays(-(double)parametros.DiasExtra4);
            var fechaLimiteDefault = DateTime.Today;
            var ctx = Context;

            return SoloPrimerSeminario()
                .Where(x => x.IdProducto == idProducto
                    // Misma ventana por nivel que VdInscripcionesFresco3y4Repository.GetInscripcionesFrescoHabilitadas.
                    && !ctx.VdInscripcionesFresco3y4s.Any(f => f.CodigoPersona == (decimal)codigoPersona
                        && f.IdOferta == x.IdOferta
                        && ((f.IdNivelProducto == 3 && f.FechaReferencia >= fechaLimiteNivel3)
                            || (f.IdNivelProducto == 4 && f.FechaReferencia >= fechaLimiteNivel4)
                            || (f.IdNivelProducto != 3 && f.IdNivelProducto != 4 && f.FechaReferencia >= fechaLimiteDefault))))
                .OrderBy(x => x.FechaReferencia)
                .ThenBy(x => x.DescripcionOferta)
                .ToList();
        }

        public virtual ICollection<BusinessLogic.Entities.VdOfertasDisponibles3y4> GetProductosDisponibles()
        {
            return SoloPrimerSeminario()
                .Where(x => x.IdProducto != null)
                // El ORDER BY va en la base (collation de Oracle) y el GroupBy lo respeta, así que
                // los grupos ya salen ordenados por escuela y nombre web del producto.
                .OrderBy(x => x.NombreExtensoEscuela)
                .ThenBy(x => x.NombreWebProducto)
                .ToList()
                .GroupBy(x => new { x.IdEscuela, x.NombreExtensoEscuela, x.IdProducto, x.NombreWebProducto, x.ConSeminarios })
                .Select(g => g.First())
                .ToList();
        }

        /// <summary>
        /// De los productos con seminarios deja solo el primer seminario de cada materia (el de
        /// fecha de referencia mas chica); los que no tienen seminarios pasan enteros.
        /// </summary>
        private IQueryable<BusinessLogic.Entities.VdOfertasDisponibles3y4> SoloPrimerSeminario()
        {
            return objectSet
                .Where(x => (x.ConSeminarios != null && x.ConSeminarios != "SI")
                    || x.FechaReferencia == objectSet
                        .Where(x2 => x2.IdProducto == x.IdProducto
                            && x2.IdMateria == x.IdMateria
                            && x2.ConSeminarios == "SI")
                        .Min(x2 => x2.FechaReferencia));
        }
    }
}
