name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Servidores y Operaciones: ingrese la contraseña para ejecutar el deploy'
        required: true

jobs:
  authentication:
    name: Autenticación - Servidores y Operaciones
    runs-on: ubuntu-latest
    steps:
      - name: Check password
        run: |
          if [ "${{ github.event.inputs.password }}" != "${{ secrets.AUTH_ADM_SERV }}" ]; then
            echo "Contraseña incorrecta. No se ejecutará el deploy."
            exit 1
          else
            echo "Contraseña correcta. Continuando con el deploy."
          fi
        shell: bash

  deploy:
    runs-on: production-server #TODO: set to self-hosted runner
    environment: prod
    needs: authentication
    steps:
      - name: Download build artifact from release
        id: release_downloader
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          preRelease: false
          tarBall: false
          zipBall: false
          fileName: '*.zip'
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete existing files from site directory
        run: Remove-Item -Recurse -Force '${{secrets.SERVER_SITE_PATH}}*'

      - name: Copy Build files into site directory
        run: |
          Get-ChildItem -Path .\ -Recurse | Where-Object { $_.Extension -ne ".zip" } | ForEach-Object {
            $destination = "${{secrets.SERVER_SITE_PATH}}" + $_.FullName.Substring($PWD.Path.Length)
            Copy-Item -Path $_.FullName -Destination $destination -Recurse -Force
          }

      - name: Notify to Microsoft Teams Release Channel
        uses: carriquiry-g/ms-teams-notification@v2
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_RELEASE_CHANNEL_WEBHOOK_URI }}
          notification-summary: 'angular-template: ${{ steps.release_downloader.outputs.tag_name }}'
          notification-style: good
          timezone: America/Montevideo
          verbose-logging: true

      - name: Cleanup workspace
        if: always()
        run: Remove-Item -Recurse -Force ${{ github.workspace }}\*

  notify_cd_execution:
    name: Notify workflow execution status
    if: always()
    needs: deploy
    uses: ./.github/workflows/notification.yml
    secrets: inherit
    with:
      result: ${{ needs.deploy.result }}
      workflow-name: ${{ github.workflow }}
