<Project Sdk="Microsoft.NET.Sdk.Web">  
 <PropertyGroup>  
   <TargetFramework>net10.0</TargetFramework>  
   <Nullable>enable</Nullable>  
   <ImplicitUsings>enable</ImplicitUsings>  
   <InvariantGlobalization>true</InvariantGlobalization>  
   <UserSecretsId>8d58b2fb-9540-4aaa-af90-773ebbc44030</UserSecretsId>  
   <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>  
 </PropertyGroup>  
 <ItemGroup>  
   <PackageReference Include="AutoMapper" Version="16.0.0" />  
   <PackageReference Include="HtmlSanitizer" Version="9.1.891-beta" />  
   <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.2" />  
   <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">  
     <PrivateAssets>all</PrivateAssets>  
     <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>  
   </PackageReference>  
   <PackageReference Include="Microsoft.OpenApi" Version="1.6.23" />  
   <PackageReference Include="OpenTelemetry" Version="1.15.0" />  
   <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />  
   <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />  
   <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />  
   <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />  
   <PackageReference Include="prometheus-net" Version="8.2.1" />  
   <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />  
   <PackageReference Include="Serilog" Version="4.3.1-dev-02404" />  
   <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />  
   <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1-dev-02330" />  
   <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />  
   <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />  
   <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.2" />  
   <PackageReference Include="Serilog.Sinks.OpenTelemetry" Version="4.2.1-nblumhardt-02317" />  
   <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />  
   <PackageReference Include="NJsonSchema" Version="11.5.2" />  
   <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.2" />  
 </ItemGroup>  
 <ItemGroup>  
   <ProjectReference Include="..\..\Core\DbConnectionContext\ConnectionContext.csproj" />  
   <ProjectReference Include="..\..\Core\MailORT\MailORT.csproj" />  
   <ProjectReference Include="..\..\Core\Modules\ModBandeja\ModAppLogic\ModBandejaAppLogic.csproj" />  
   <ProjectReference Include="..\..\Core\Modules\ModBandeja\ModBusinessLogic\ModBandejaBusinessLogic.csproj" />  
   <ProjectReference Include="..\..\Core\Modules\ModBandeja\ModDataAccess\ModBandejaDataAccess.csproj" />  
   <ProjectReference Include="..\..\Core\Utilities\Utilities.csproj" />  
   <ProjectReference Include="..\AppLogic\AppLogic.csproj" />  
   <ProjectReference Include="..\DataAccess\DataAccess.csproj" />  
   <ProjectReference Include="..\..\Core\LdapService\LdapService.csproj" />  
   <ProjectReference Include="..\..\Core\Modules\ModGenericBase\ModDataAccess\ModGenericBaseDataAccess.csproj" />  
 </ItemGroup>  
 <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>  
</Project>